# Frasa viral untuk hook "pemancing" (termasuk frasa politik) + cara pakai yang aman.
# Kolom: frasa, jenis, konteks singkat, contoh hook Privasimu, modul, cara pakai aman, risiko, catatan.
# PENTING: konteks & "suhu" tiap frasa berubah cepat → cek ulang sebelum tayang.

ATURAN = [
    'Yang boleh: FRASA-nya saja, ditulis sebagai teks dan diucapkan tim/TTS dengan gaya sendiri.',
    'Yang tidak dipakai di iklan: wajah, foto, video, suara asli, nama, atau tiruan suara/logat tokoh mana pun.',
    'Dasar: UU Hak Cipta No. 28/2014 Pasal 12: potret orang untuk reklame/iklan komersial wajib izin tertulis dari orangnya (ancaman denda sampai Rp500 juta).',
    'Suara dan wajah adalah data pribadi (UU PDP). Iklan Privasimu yang memakainya tanpa izin berlawanan dengan pesan produknya sendiri.',
    'Klip TV/YouTube/TikTok dan gambar meme adalah ciptaan pihak lain; myinstants dan sejenisnya hanya untuk pemakaian pribadi nonkomersial.',
    'Frasa tokoh politik yang sedang menjabat bisa dibaca sebagai dukungan atau sindiran. Klien Privasimu banyak dari korporasi, lembaga keuangan, dan BUMN: jaga netralitas.',
    'Saran pemakaian: frasa politik berisiko Sedang hanya untuk konten organik, bukan iklan berbayar. Risiko Tinggi: hindari.',
    'Ini bukan nasihat hukum; konfirmasi dengan penasihat hukum sebelum tayang.',
]

FRASA = [
    # ---------------------------------------------------------------- frasa politik
    ('“Yo ndak tahu, kok tanya saya.”', 'Frasa politik',
     'Dikenal luas sebagai YNTKTS; lekat dengan mantan Presiden Jokowi. Dipakai netizen untuk jawaban mengelak.',
     'Ketika auditor tanya: “Data pelanggan disimpan di mana?” — “Yo ndak tahu, kok tanya saya.” — FAAAH. → “Di Nexus, jawabannya ada di katalog sistem.”',
     'Data Discovery, RoPA', 'Teks di layar + suara tim dengan gaya sendiri', 'Sedang',
     'Contoh dari pengguna. Tanpa nama, wajah, suara asli, atau logat tiruan.'),
    ('“Omon-omon.”', 'Frasa politik',
     'Diucapkan Prabowo di debat capres 7 Januari 2024. Pada 2026 juga dipakai pengkritik pemerintah.',
     '“Patuh jangan cuma omon-omon. Mana buktinya?” → log persetujuan & bukti.',
     'Consent, GAP Assessment', 'Teks saja', 'Tinggi',
     'Sedang dipakai sebagai kritik politik; mudah dibaca berpihak. Sebaiknya dihindari di iklan.'),
    ('“Bocor… bocor…”', 'Frasa politik',
     'Lekat dengan pidato kampanye Prabowo tentang “kebocoran”; lama jadi bahan meme.',
     '“Bocor… bocor…” (kali ini datanya). → penghitung mundur 3×24 jam.',
     'Manajemen Insiden', 'Teks + suara tim', 'Sedang',
     'Relevan dengan “kebocoran data”. Cek ulang konteks; jangan menyindir tokohnya.'),
    ('“Aku rapopo.”', 'Frasa politik',
     'Frasa Jawa (“aku tidak apa-apa”) yang populer sejak 2014 dan lekat dengan Jokowi.',
     'Auditor datang mendadak. DPO: “Aku rapopo.” (RoPA-nya sudah rapi.)',
     'RoPA, Dasbor', 'Teks + suara tim', 'Sedang',
     'Frasa sehari-hari; asosiasi politiknya sudah melemah.'),
    ('Pola “kerja, kerja, kerja”', 'Frasa politik',
     'Slogan tiga kata yang lekat dengan pemerintahan Jokowi.',
     '“Catat, catat, catat.” (meminjam POLA tiga kata, bukan slogannya)',
     'RoPA', 'Pakai pola, ganti katanya', 'Rendah',
     'Tidak mengutip slogan aslinya.'),
    ('“Sorry ye.”', 'Frasa politik',
     'Diucapkan Prabowo di debat capres Desember 2023.',
     '“RoPA-nya belum ada, ya?” — “Sorry ye, sudah tercatat semua.”',
     'RoPA', 'Teks saja', 'Sedang',
     'Tanpa gestur/tiruan suara.'),
    ('“Saya prihatin.”', 'Frasa politik',
     'Lekat dengan mantan Presiden SBY.',
     '“Saya prihatin… RoPA-nya masih di spreadsheet.”',
     'RoPA', 'Teks saja', 'Sedang',
     'Frasa umum; asosiasi politiknya sudah lama.'),
    ('“Kabur aja dulu.”', 'Frasa politik',
     'Tagar warganet 2025 yang bernuansa kritik sosial-politik.',
     'Auditor datang? “Kabur aja dulu.” …atau buka dasbor.',
     'Dasbor kepatuhan', 'Teks saja', 'Sedang',
     'Bernuansa kritik; pakai untuk organik saja.'),
    ('“Ndasmu.”', 'Frasa politik',
     'Ucapan kasar yang viral pada 2023.',
     '—', '—', 'Jangan dipakai', 'Tinggi',
     'Kasar; tidak cocok untuk merek.'),
    ('“Antek asing”, “londo ireng”', 'Frasa politik',
     'Tuduhan politik yang sedang panas pada 2026.',
     '—', '—', 'Jangan dipakai', 'Tinggi',
     'Menyasar kelompok tertentu; berisiko tinggi untuk merek.'),

    # ---------------------------------------------------------------- frasa warganet
    ('“Astaga, bercanda.”', 'Frasa warganet',
     'Viral Agustus–September 2026.',
     'Pak Bos: “Kita sudah patuh UU PDP, kan?” — “Astaga, bercanda.”',
     'GAP Assessment', 'Teks + suara tim', 'Rendah', 'Sudah dipakai di N11.'),
    ('“Orang have / haven’t / not yet.”', 'Frasa warganet',
     'Istilah gaul September 2026.',
     '“Ada orang have: RoPA lengkap. Ada orang haven’t: masih di Excel. Aku? Orang not yet.”',
     'RoPA, DPIA', 'Teks + suara tim', 'Rendah', 'Sudah dipakai di N11.'),
    ('“Adalah pokoknya.”', 'Frasa warganet',
     'Jawaban mengambang yang viral 2026.',
     '“Dasar pemrosesannya apa?” — “Adalah pokoknya.”',
     'RoPA (wizard)', 'Teks + suara tim', 'Rendah', 'Sudah dipakai di N11; lihat A45.'),
    ('“Menyala!”', 'Frasa warganet',
     'Ungkapan pujian populer sejak 2024.',
     '“RoPA selesai sebelum tenggat. Menyala, DPO-ku!”',
     'RoPA', 'Teks + suara tim', 'Rendah', ''),
    ('“Yang penting yakin.”', 'Frasa warganet',
     'Ungkapan sehari-hari.',
     '“Bukti persetujuannya mana?” — “Yang penting yakin.”',
     'Consent (log & bukti)', 'Teks + suara tim', 'Rendah', ''),
    ('“Dahlah.”', 'Frasa warganet',
     'Ungkapan pasrah.',
     'Membuka file RoPA versi ke-14: “Dahlah.”',
     'RoPA', 'Teks saja', 'Rendah', ''),
    ('“Valid, no debat.”', 'Frasa warganet',
     'Ungkapan setuju mutlak.',
     '“Tercatat, ada bukti, ada tenggat. Valid, no debat.”',
     'Platform', 'Teks saja', 'Rendah', ''),
    ('“Bukan kaleng-kaleng.”', 'Frasa warganet',
     'Ungkapan “bukan sembarangan”.',
     '“Log audit berantai hash. Bukan kaleng-kaleng.”',
     'Log audit', 'Teks saja', 'Rendah', 'Rantai hash bersifat opsional di produk.'),
    ('“Tipis-tipis.”', 'Frasa warganet',
     'Ungkapan “sedikit demi sedikit”.',
     '“Patuhnya tipis-tipis dulu.” → mulai dari Start Pre Check.',
     'GAP Assessment', 'Teks saja', 'Rendah', ''),
    ('“Cooked” / “aura”', 'Frasa warganet',
     'Slang 2026.',
     '“−999 aura: kirim KTP pelanggan lewat grup.”',
     'Brand, Insiden', 'Teks saja', 'Rendah', 'Lihat A43, A44.'),
    ('“Kamu nanya?”', 'Frasa warganet',
     'Viral 2022; lekat dengan satu kreator.',
     '“RoPA itu apa?” — “Kamu nanya?” → kelas DPO Academy.',
     'DPO Academy', 'Teks saja', 'Sedang', 'Jangan meniru gaya bicara/penampilan kreatornya.'),
    ('“Emotional damage.”', 'Frasa warganet',
     'Frasa reaksi yang lekat dengan satu kreator.',
     'CFO membaca “hingga 2% dari pendapatan tahunan”: “Emotional damage.”',
     'Paparan Sanksi', 'Teks + suara tim tanpa meniru logat', 'Sedang', 'Lihat A08.'),

    # ---------------------------------------------------------------- frasa kantor
    ('“Nanti kita follow up.”', 'Frasa kantor',
     'Kalimat penutup rapat yang jarang ditindaklanjuti.',
     '“Insidennya kapan dilaporkan?” — “Nanti kita follow up.” (penghitung mundur tetap berjalan)',
     'Manajemen Insiden', 'Teks + suara tim', 'Rendah', ''),
    ('“Mohon izin bertanya.”', 'Frasa kantor',
     'Pembuka sopan khas kantor.',
     '“Mohon izin bertanya: data pribadi itu apa, ya?”',
     'DPO Academy', 'Teks + suara tim', 'Rendah', ''),
    ('“Sesuai arahan.”', 'Frasa kantor',
     'Jawaban aman khas kantor.',
     '“Datanya dikirim ke siapa?” — “Sesuai arahan.” (arahan siapa?) → alur persetujuan tercatat.',
     'RoPA (alur persetujuan)', 'Teks + suara tim', 'Rendah', ''),
    ('“Siap, salah.”', 'Frasa kantor',
     'Jawaban pasrah saat ditegur.',
     '“RoPA-nya mana?” — “Siap, salah.”',
     'RoPA', 'Teks + suara tim', 'Rendah', ''),
    ('“Final ya, ini final.”', 'Frasa kantor',
     'Kalimat sebelum revisi berikutnya.',
     '“Final ya, ini final.” → RoPA_final_revisi3_FIX.xlsx',
     'RoPA', 'Teks + suara tim', 'Rendah', ''),

    # ---------------------------------------------------------------- suara meme & pola hook
    ('“FAAAH!” (suara)', 'Suara meme',
     'Suara gagal total yang populer di video meme.',
     'File RoPA “dikunci pengguna lain” → FAAAH.',
     'RoPA', 'Rekam ulang oleh tim ke motion/sfx-kustom/ atau TTS berlisensi', 'Rendah',
     'Klip aslinya tidak dipakai (lihat sheet Bank Sound Meme).'),
    ('“HAH?” (suara)', 'Suara meme',
     'Suara reaksi kaget/bingung.',
     'Marketing: “blast ke semua nomor ya!” → HAH?',
     'Consent & Cookie', 'Rekam ulang oleh tim', 'Rendah', ''),
    ('Pola “Ini yang harus kamu lakukan ketika…”', 'Pola hook',
     'Pembuka video fakta unik (contoh acuan dari pengguna).',
     '“Ini yang harus kamu lakukan ketika dapat email ini!”',
     'DSR', 'Pola kalimat bebas dipakai', 'Rendah', 'Lihat gaya SE23.'),
    ('Pola “Jangan … kalau …”', 'Pola hook',
     'Reverse psychology.',
     '“Jangan cek skor kepatuhanmu kalau belum siap kaget.”',
     'GAP Assessment', 'Pola kalimat bebas dipakai', 'Rendah', 'Sudah dipakai di M02, T02.'),
    ('Pola “POV:” / “Nobody:”', 'Pola hook',
     'Format meme teks.',
     '“POV: auditor minta RoPA.”',
     'RoPA', 'Pola kalimat bebas dipakai', 'Rendah', 'Lihat A01, A09.'),
    ('Pola “Ketika … tanya …”', 'Pola hook',
     'Pertanyaan serius dijawab frasa viral.',
     '“Ketika direksi tanya: ‘kita sudah patuh?’”',
     'GAP Assessment', 'Pola kalimat bebas dipakai', 'Rendah', 'Lihat gaya SE24.'),
]
