# Data rancangan iklan meme (48 konsep), bank sound, efek VO, opsi TTS, kalender
A = [
 ('A01', 'FAAAH: RoPA-nya masih Excel', 'POV + suara "FAAAH" (gagal total)', 'Tools', 'Awareness → Konversi', 'DPO, tim legal', 'TikTok/Reels/Shorts 15–20 dtk',
  'Teks: "POV: auditor minta RoPA, kamu buka RoPA_final_revisi3_FIX.xlsx"',
  '0–3 dtk: laptop membuka file spreadsheet pelan-pelan\n3–5: "Tidak merespons…" → "FAAAH" + zoom ke wajah DPO 😩\n5–10: potong ke wizard RoPA Nexus (screenshot asli): satu register, kode ROPA otomatis, jejak audit\n10–15: DPO 😎 + CTA',
  '"FAAAH" (rekam ulang tim) di detik 4 · vine boom saat "tidak merespons" · musik drop saat Nexus muncul', '—', 'RoPA', 'Start Pre Check (gratis) di privasimu.com',
  'Register terpusat, kode ROPA-TAHUN-NOMOR, log audit (fakta_produk: ropa)', 9, 8, 7, 8, 'Rendah', 'Rendah. Jangan tampilkan logo/antarmuka spreadsheet bermerek', 'Bisa dibuat dari kit (varian N04)', 'Okt–Nov 2026'),
 ('A02', 'Astaga, bercanda (Pak Bos edition)', 'Chat + frasa viral "astaga, bercanda" (Agu–Sep 2026)', 'Tools', 'Awareness', 'DPO, legal, pekerja kantoran', 'TikTok/Reels 15 dtk',
  'Chat Pak Bos: "Kita sudah patuh UU PDP, kan?"',
  '0–3: chat masuk\n3–7: "Sudah dong, Pak. 100% ✅"\n7–9: "astaga, bercanda 😭" + vine boom + 💀 "kita cooked"\n9–15: skor GAP Assessment asli: "cek skor kepatuhan yang beneran" + CTA',
  'vine boom · ketikan · auraDown', 'Pak Bos: "berat" ringan', 'GAP Assessment', 'Cek skor kepatuhan: Start Pre Check',
  'GAP: kuesioner, skor, rencana remediasi (fakta_produk: gap-assessment)', 9, 8, 7, 9, 'Rendah', 'Rendah', 'Sudah jadi (potongan N11)', 'Kapan saja'),
 ('A03', 'Hal yang bisa kamu bilang ke auditor', '"Things to Say" (Agu–Sep 2026) + "adalah pokoknya"', 'Edukasi + Tools', 'Awareness + Share', 'DPO, auditor internal', 'TikTok/Reels 20 dtk',
  '"Hal yang bisa kamu bilang ke auditor:"',
  'Daftar 3 jawaban konyol: KTP di grup kantor · RoPA di kepala saya · "adalah pokoknya"\n→ tiap jawaban "+1 temuan" → stempel JANGAN DITIRU\n→ jawaban yang benar ada di Nexus: register, DPIA, log audit',
  'vine boom per jawaban · stamp · phonk cowbell (synth)', 'Narator "berat" (gaya sigma)', 'RoPA, DPIA, log audit', 'Simpan & tag rekan tim',
  'Log audit & register terpusat (fakta_produk)', 8, 8, 6, 9, 'Rendah', 'Rendah. Pastikan label "JANGAN DITIRU" jelas', 'Sudah jadi (potongan N11)', 'Kapan saja'),
 ('A04', 'Orang have vs haven\'t vs not yet', 'Istilah gaul "orang have/haven\'t/not yet" (Sep 2026)', 'Tools', 'Awareness + Share', 'DPO, pekerja kantoran', 'TikTok/Reels 12–15 dtk',
  '"Ada orang have…"', 'Template 3 panel: have (RoPA lengkap) / haven\'t (RoPA masih spreadsheet) / not yet (DPO 🫠)\n→ "jadi orang have: pakai Nexus"',
  'vine boom · buzzer · auraDown', '—', 'RoPA, DPIA', 'Jadi orang have: privasimu.com', '—', 9, 9, 6, 8, 'Rendah', 'Rendah', 'Sudah jadi (potongan N11)', 'Okt 2026 (selagi tren)'),
 ('A05', 'Borgol 3×24 jam yang kebesaran', 'Borgol kebesaran yang gampang lepas (Sep 2026), digambar ulang', 'Tools', 'Awareness → Konversi', 'DPO, IT security, CISO', 'Reels/Shorts 15–20 dtk',
  '"Jam 3 pagi: dugaan kebocoran data."', 'Layar kunci 03.00 → borgol raksasa "3 X 24 JAM" jatuh → "Tenang" borgol melorot\n→ modul insiden asli: 5 fase, hitung mundur, templat pemberitahuan',
  'notifikasi · clank · slide whistle · "FAAAH" opsional saat borgol jatuh', '—', 'Manajemen Insiden', 'Latih tim sebelum insiden: minta demo',
  'UU PDP Ps. 46 jo. PP 33/2026 Ps. 114; fakta_produk: breach', 8, 7, 8, 7, 'Rendah', 'Rendah', 'Sudah jadi (potongan N11)', 'Nov 2026'),
 ('A06', 'Polyester Edit: 1 DPO, semua modul', '"Polyester Edit" (Sep 2026)', 'Tools', 'Awareness', 'DPO, IT, legal', 'TikTok/Reels 10–12 dtk',
  '"Kalau DPO punya polyester edit:"', 'DPO diam di depan, layar asli Nexus berganti liar di belakang → kolase "SEMUA NYAMBUNG"',
  'funk Brasil (synth) · hit per potongan · aura', '—', 'Semua modul', 'Lihat demonya', 'Modul saling terhubung (fakta_produk: platform)', 6, 8, 7, 7, 'Rendah', 'Rendah', 'Sudah jadi (potongan N11)', 'Okt–Nov 2026'),
 ('A07', 'Kinda chic to… (DPO edition)', '"Kinda chic to…" (tren caption Sep 2026)', 'Tools / Brand', 'Awareness (LinkedIn)', 'DPO senior, compliance lead', 'LinkedIn/Instagram 10–15 dtk',
  '"Kinda chic to… lapor insiden tepat waktu."', '3–5 baris "kinda chic to…" + dasbor asli di laptop → CTA', 'lo-fi · ding lembut', '—', 'Dasbor, insiden, RoPA', 'Kinda chic to be ready: privasimu.com',
  'PP 33/2026 berlaku 16 Jan 2027', 7, 7, 7, 8, 'Rendah', 'Rendah', 'Sudah jadi (potongan N11)', 'Nov–Des 2026'),
 ('A08', 'EMOTIONAL DAMAGE: denda 2%', 'Frasa "emotional damage" (direkam ulang tim, tanpa meniru logat/persona)', 'Konsultasi + Tools', 'Konversi', 'Direksi, CFO', 'Reels/LinkedIn 15 dtk',
  '"CFO membaca: denda administratif hingga 2% dari pendapatan tahunan"', 'CFO 😳 → teriakan "EMOTIONAL DAMAGE!" + dun dun dun\n→ Paparan Sanksi Nexus memetakan pasal bersanksi ke modul → CTA konsultasi',
  'rekaman tim "emotional damage" · dun dun dun', 'Teks sanksi: "berat"', 'Paparan Sanksi Administratif', 'Jadwalkan konsultasi program siap PP 33',
  'UU PDP Ps. 57 (denda maks. 2% pendapatan tahunan); fakta_produk: paparan sanksi', 7, 8, 8, 7, 'Sedang', 'Sedang. Frasa populer milik kreator lain: rekam dengan suara sendiri, jangan tiru logat/etnis', 'Baru (kit)', 'Nov 2026 (musim anggaran)'),
 ('A09', 'Nobody: / Marketing jam 5 sore', '"Nobody:" + reaksi "HAH?"', 'Tools', 'Awareness + Share', 'Marketing, DPO', 'TikTok/Reels 15 dtk',
  '"Nobody: / Marketing jam 5 sore: \'blast promo ke semua nomor di database ya!\'"', 'DPO: "consent-nya ada?" → marketing: "consent itu apa?" → "HAH?"\n→ Consent Nexus: log persetujuan + bukti, penarikan tersebar ke semua sistem',
  '"HAH?" (rekam tim) · vine boom · jangkrik', '—', 'Consent & Cookie', 'Tag tim marketing kalian',
  'fakta_produk: consent (log + bukti, penarikan via API/webhook)', 9, 8, 7, 9, 'Rendah', 'Rendah. Jangan sebut merek aplikasi chat tertentu', 'Baru (kit, mirip N05)', 'Des 2026 (musim promo 12.12)'),
 ('A10', 'Tolong hapus data saya → LARIII', 'Panik "RUN" (rekam ulang: "LARIII!")', 'Tools', 'Awareness → Konversi', 'Customer service, DPO', 'Reels/Shorts 15 dtk',
  'Email masuk: "Tolong hapus data saya 🙏"', 'Seluruh kantor lari 🏃 "LARIII!" → DPO tenang buka DSR Nexus: tenggat 72 jam otomatis, verifikasi identitas, draf jawaban AI',
  '"LARIII!" (rekam tim) · whoosh · detak jam', '—', 'DSR', 'Coba alur DSR di demo', 'fakta_produk: dsr (tenggat 72 jam, verifikasi, draf AI)', 8, 7, 8, 7, 'Rendah', 'Rendah', 'Bisa dari N05', 'Okt 2026'),
 ('A11', 'HAH? Data pribadi spesifik itu apa?', 'Reaksi "huh?"', 'Edukasi + Tools', 'Awareness', 'Karyawan umum, HR', 'Reels/Shorts 15 dtk',
  '"Data pribadi spesifik itu apa?" "HAH?"', 'Daftar cepat: kesehatan, biometrik, genetika, catatan kejahatan, data anak, keuangan pribadi\n→ di Nexus: data spesifik otomatis risiko TINGGI + draf DPIA',
  '"HAH?" (rekam tim) · pop per item', '"HAH?" bisa pakai efek "tupai"', 'RoPA → DPIA otomatis', 'Simpan & bagikan ke tim',
  'UU PDP Ps. 4 ayat (2); fakta_produk: ropa (spesifik → TINGGI → draf DPIA)', 7, 7, 6, 7, 'Rendah', 'Rendah', 'Baru (kit)', 'Kapan saja'),
 ('A12', 'Tell me you\'re a DPO without telling me', 'Format "tell me … without telling me"', 'Brand / komunitas', 'Share', 'DPO, legal', 'TikTok/Reels 10–15 dtk',
  '"Tell me you\'re a DPO without telling me"', '4 kebiasaan: nyensor KTP di grup · nanya "dasar pemrosesannya apa?" · takut file FINAL_final · hafal "3×24 jam" → end card Nexus',
  'pop · vine boom di akhir', '—', 'Brand', 'Tag DPO kantormu 👇', '—', 9, 9, 4, 10, 'Rendah', 'Rendah', 'Baru (kit)', 'Okt 2026'),
 ('A13', 'DPO Starter Pack', 'Starter pack', 'Brand / komunitas', 'Share', 'DPO baru', 'Carousel IG/LinkedIn atau video 10 dtk',
  '"DPO starter pack (edisi 2026)"', 'Item: lanyard, kopi ke-4, 7 grup chat, spreadsheet RoPA, 225 pasal PP 33, mimpi buruk jam 3 pagi → "upgrade: Privasimu Nexus"',
  'pop per item · dun dun dun', '—', 'Brand', 'Tag DPO yang butuh upgrade', 'PP 33/2026 = 225 pasal (knowledge base)', 9, 8, 5, 9, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A14', 'Ekspektasi vs realita jadi DPO', 'Expectation vs reality', 'Tools', 'Awareness', 'DPO baru', 'TikTok/Reels 15 dtk',
  '"Ekspektasi jadi DPO:"', 'Ekspektasi: melindungi data dengan tenang 🧘 / realita: ngejar 12 divisi isi form + "FAAAH"\n→ realita dengan Nexus: alur Maker–Reviewer–Approver + pengingat',
  '"FAAAH" (rekam tim) · sad violin (synth)', '—', 'Alur RoPA', 'privasimu.com', 'fakta_produk: ropa (Maker, Reviewer, Approver)', 9, 8, 6, 8, 'Rendah', 'Rendah', 'Baru (kit meme "expect")', 'Kapan saja'),
 ('A15', 'Red flag vs green flag pihak ketiga', 'Red flag / green flag', 'Tools', 'Konversi', 'Procurement, DPO', 'Reels/LinkedIn 15–20 dtk',
  '"Red flag pihak ketiga 🚩"', '🚩 tidak mau isi asesmen · 🚩 kirim NDA bukan perjanjian pemrosesan data · ✅ isi kuesioner lewat tautan tanpa akun · ✅ skor risiko otomatis → modul Pihak Ketiga',
  'buzzer · ding', '—', 'Manajemen Risiko Pihak Ketiga, Telaah Kontrak', 'Minta demo', 'fakta_produk: pihak ketiga (tautan tanpa akun), telaah kontrak', 7, 7, 7, 7, 'Rendah', 'Rendah. Pakai istilah "pihak ketiga", bukan "vendor"', 'Baru', 'Nov 2026'),
 ('A16', 'Mannequin challenge: auditor datang', 'Kebangkitan meme 2016 (Mannequin Challenge)', 'Tools', 'Awareness + Share', 'Seluruh kantor', 'TikTok/Reels 20 dtk',
  'Auditor: "Boleh lihat bukti persetujuan?"', 'Semua karyawan membeku, kamera berputar; hanya DPO bergerak membuka Nexus: log persetujuan + bukti',
  'musik ala 2016 (synth orisinal) · record scratch', '—', 'Consent log, log audit', 'Kalau di kantormu, siapa yang bergerak?', 'fakta_produk: consent', 7, 8, 6, 8, 'Sedang (live-action tim/animasi)', 'Rendah. Karyawan yang tampil wajib memberi persetujuan tertulis', 'Baru', 'Okt–Nov 2026'),
 ('A17', '2016 vs 2026: DPO edition', '"2026 is the new 2016"', 'Brand', 'Awareness + Share', 'Pekerja 25–40 th', 'TikTok/Reels 15 dtk',
  '"2016: data pelanggan disimpan di flashdisk"', '2016 (filter jadul): flashdisk, spreadsheet, password di sticky note\n→ 2026: Nexus, log audit berantai hash, DSR 72 jam → "yang balik ke 2016 cukup memenya"',
  'rewind VHS · shutter', 'Narasi 2016: efek "telepon"', 'Platform', 'privasimu.com', 'fakta_produk: platform (log audit hash opsional)', 7, 8, 5, 8, 'Rendah', 'Rendah', 'Baru', 'Okt 2026'),
 ('A18', 'Anomali: "Bocorino Datalino"', 'Brainrot/anomali (canon 2026), karakter orisinal', 'Brand', 'Awareness (Gen Z)', 'Gen Z pekerja, mahasiswa hukum/IT', 'TikTok 15 dtk',
  '"Bocorino Datalino… anomali yang membocorkan data tiap Senin"', 'Karakter orisinal (keran bocor berkaki) dinarasikan ala brainrot → dikalahkan maskot Nexus → tagline',
  'narator dramatis · dun dun dun', 'Narator "berat" + "aula"', 'Brand', 'Sebutkan anomali versi kantormu', '—', 6, 9, 4, 8, 'Sedang (ilustrasi karakter)', 'Sedang. Bisa terasa cringe; uji kecil dulu', 'Baru', 'Okt 2026'),
 ('A19', 'Rating kebiasaan data kantor 1–10', 'Format rating', 'Edukasi', 'Awareness + Share', 'Karyawan umum', 'TikTok/Reels 20 dtk',
  '"Rating kebiasaan data di kantor, jujur:"', 'Password di sticky note 1/10 "FAAAH" · kirim KTP via grup 2/10 · RoPA terpusat 10/10 (Nexus)',
  '"FAAAH" (rekam tim) · ding', '—', 'RoPA, pelatihan', 'Kantormu dapat skor berapa?', '—', 8, 7, 6, 8, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A20', 'GRWM: DPO siap-siap audit', 'Get Ready With Me', 'Tools', 'Awareness', 'DPO muda', 'TikTok/Reels 20–30 dtk',
  '"Get ready with me: hari audit"', '"Skincare" = cek dasbor kepatuhan · "outfit" = laporan GAP · "aksesori" = log audit berantai hash · "parfum" = tenang',
  'ASMR klik · lo-fi', 'Efek "bisik" (ASMR)', 'Dasbor, GAP, log audit', 'privasimu.com', 'fakta_produk: platform', 7, 8, 7, 7, 'Sedang', 'Rendah', 'Baru', 'Nov 2026'),
 ('A21', 'Day in the life of a DPO (versi jujur)', 'Day in the life', 'Tools', 'Awareness → Konversi', 'DPO', 'TikTok/Reels/Shorts 30 dtk',
  '"Day in the life of a DPO (versi jujur)"', '07.00 12 notif DSR · 09.00 rapat "data pribadi itu apa" · 13.00 pihak ketiga kirim NDA · 03.00 dugaan insiden "FAAAH"\n→ versi Nexus: semua di satu antrean kerja',
  '"FAAAH" (rekam tim) · detak jam · notifikasi', '—', 'Antrean kerja PPDP, DSR, insiden', 'Minta demo', 'fakta_produk: dukungan PPDP (antrean pekerjaan)', 9, 8, 7, 8, 'Sedang', 'Rendah', 'Baru', 'Okt–Nov 2026'),
 ('A22', 'Rekap Tahunan DPO 2026', 'Year-in-review Desember (ala "Wrapped", tanpa meniru merek)', 'Brand', 'Share', 'DPO, legal', 'IG/TikTok slide 15–20 dtk',
  '"Rekap tahunan DPO 2026 kamu sudah siap"', 'Top "lagu": "Tolong isi form-nya" · menit di rapat: 12.480 · file favorit: FINAL_final_v3 · 2027: PP 33 berlaku → "bikin rekap 2027 lebih rapi"',
  'shimmer · pop', '—', 'Brand + PP 33', 'Bagikan rekapmu', 'PP 33/2026 berlaku 16 Jan 2027 (angka lain ilustrasi)', 9, 9, 6, 10, 'Rendah', 'Sedang. Jangan tiru warna/font/logo layanan musik tertentu', 'Baru', 'Des 2026 (minggu 1–3)'),
 ('A23', 'Hitung mundur PP 33 (serial)', 'Countdown serial', 'Tools / Konsultasi', 'Konversi', 'Direksi, DPO', 'Stories/Reels 10 dtk per episode',
  '"X hari lagi PP 33 berlaku"', 'Tiap episode: 1 meme + 1 kewajiban + CTA', 'flip clock', '—', 'Paparan Sanksi, GAP', 'Program siap PP 33',
  'PP 33/2026 berlaku 16 Jan 2027; 225 pasal', 7, 7, 8, 6, 'Rendah', 'Rendah', 'Bisa dari N01', 'Des 2026–Jan 2027'),
 ('A24', 'Resolusi 2027: patuh PP 33', 'New year resolution', 'Tools', 'Awareness + Konversi', 'Semua', 'TikTok/Reels 15 dtk',
  '"Resolusi 2027:"', '1. diet ❌ ("FAAAH") 2. nabung ❌ 3. patuh PP 33 ✅ (yang ini wajib, mulai 16 Januari)', '"FAAAH" ×2 (rekam tim) · ding benar', '—', 'GAP, program siap PP 33', 'Mulai dari Start Pre Check (gratis)',
  'PP 33/2026 berlaku 16 Jan 2027', 8, 8, 7, 8, 'Rendah', 'Rendah', 'Baru', '26 Des 2026–10 Jan 2027'),
 ('A25', '12.12: diskon 90%, data pelanggan ikut "diskon"?', 'Momen Harbolnas', 'Tools', 'Awareness', 'E-commerce, ritel', 'TikTok/Reels 15 dtk',
  '"Saat trafik 12.12 naik 10×…"', 'Dun dun dun: dugaan kebocoran → Nexus: latihan fire drill sebelum 12.12 + modul insiden', 'dun dun dun · alarm', '—', 'Simulasi & Fire Drill, Insiden', 'Latihan dulu sebelum 12.12',
  'fakta_produk: simulasi & fire drill', 7, 8, 7, 7, 'Rendah', 'Sedang. Jangan sebut marketplace tertentu', 'Baru', '25 Nov–12 Des 2026'),
 ('A26', 'Rapat direksi: "OH MY GOD, 2%?"', 'Reaksi kaget', 'Konsultasi', 'Konversi', 'Direksi, CFO', 'LinkedIn/Reels 15 dtk',
  '"Direksi saat tahu dendanya bisa sampai 2% pendapatan tahunan"', 'Reaksi "OH MY GOD" → konsultan Privasimu: pendampingan program siap PP 33', '"OH MY GOD" (rekam tim) · dun dun dun', '—', 'Konsultasi + Paparan Sanksi', 'Konsultasi (cek penawaran gratis masih berlaku)',
  'UU PDP Ps. 57', 7, 7, 9, 6, 'Rendah', 'Rendah', 'Bisa dari N08', 'Nov 2026'),
 ('A27', 'Anggaran 2027: pos PDP = Rp0?', 'POV rapat anggaran', 'Konsultasi + Tools', 'Konversi', 'CFO, DPO, direksi', 'LinkedIn/Reels 15 dtk',
  '"POV: rapat anggaran 2027, pos kepatuhan PDP: Rp0"', '"FAAAH" → "PP 33 berlaku 16 Jan 2027" → "masukkan ke anggaran: demo & penawaran"', '"FAAAH" (rekam tim) · coin', '—', 'Platform + konsultasi', 'Minta penawaran sebelum anggaran dikunci',
  'PP 33/2026 berlaku 16 Jan 2027', 7, 6, 9, 5, 'Rendah', 'Rendah', 'Baru', 'Okt–Nov 2026 (musim anggaran)'),
 ('A28', 'HR: pelamar minta CV-nya dihapus', 'Reaksi "HAH?"', 'Tools', 'Awareness', 'HR, recruiter', 'TikTok/Reels 15 dtk',
  '"Pelamar: \'Tolong hapus data saya.\' HR:"', '"HAH?" → retensi di RoPA + DSR 72 jam', '"HAH?" (rekam tim)', '—', 'RoPA (retensi), DSR', 'Tag tim HR',
  'fakta_produk: ropa (retensi), dsr', 8, 7, 6, 8, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A29', 'IT: "Aman kok, password-nya 123"', 'Error / gagal', 'Tools', 'Awareness', 'IT, karyawan', 'TikTok/Reels 10–15 dtk',
  '"IT: \'Aman kok.\' Password-nya:"', '"123456" → suara error → fire drill simulasi insiden di Nexus', 'error (synth) · "FAAAH"', '—', 'Simulasi & Fire Drill', 'Uji kesiapan timmu',
  'fakta_produk: simulasi', 8, 8, 6, 8, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A30', 'Latihan kebakaran ada, latihan kebocoran data?', 'Pertanyaan retoris + alarm', 'Tools', 'Konversi', 'CISO, DPO', 'LinkedIn/Reels 15 dtk',
  '"Kantor kita rutin latihan kebakaran. Latihan kebocoran data?"', 'Alarm → skenario kuis/tabletop di Nexus → skor rubrik', 'alarm · centang', '—', 'Simulasi & Fire Drill', 'Minta demo',
  'fakta_produk: simulasi (kuis, tabletop, walkthrough, rubrik)', 7, 7, 8, 6, 'Rendah', 'Rendah', 'Baru', 'Okt 2026'),
 ('A31', 'Sus: pengguna umur 12 daftar sendiri', 'Slang "sus"', 'Tools', 'Konversi', 'Edtech, game, sekolah', 'Reels/Shorts 15 dtk',
  '"Pengguna umur 12 tahun daftar sendiri tanpa wali? Sus."', 'Children Pro: persetujuan wali, peralihan saat 18 tahun', 'pop · ding', '—', 'Children Pro', 'Minta demo',
  'fakta_produk: consent (Children Pro); PP 33 Ps. 38 ayat (8)', 6, 7, 7, 6, 'Rendah', 'Rendah', 'Bisa dari N06', 'Nov 2026'),
 ('A32', 'Persetujuan yang bisa dipahami semua orang', 'Heartwarming (non-meme)', 'Brand', 'Awareness', 'Publik, layanan publik', 'Reels/YouTube 20 dtk',
  '"Tombol \'Setuju\' yang tidak bisa dibaca semua orang"', 'Pengguna tunanetra/lansia → Inclusive Privacy', 'musik lembut', '—', 'Inclusive Privacy', 'Pelajari lebih lanjut',
  'fakta_produk: consent (Inclusive Privacy)', 6, 6, 6, 7, 'Sedang', 'Rendah. Libatkan komunitas disabilitas, hindari stereotip', 'Baru', 'Awal Des 2026 (3 Des: Hari Disabilitas Internasional)'),
 ('A33', '12 anak usaha, 12 versi RoPA', '"Saling tunjuk" (digambar ulang, tanpa adegan kartun asli)', 'Konsultasi + Tools', 'Konversi', 'Holding, grup usaha', 'LinkedIn/Reels 15 dtk',
  'Holding: "Siapa yang pegang data pelanggan?"', '3 karakter DPO identik saling tunjuk → Holding Dashboard: satu grup, satu standar', 'vine boom', '—', 'Holding Dashboard', 'Konsultasi enterprise',
  'Tampilan asli Holding Group Dashboard (tanpa data grup)', 7, 7, 8, 6, 'Rendah', 'Rendah', 'Bisa dari N10', 'Nov 2026'),
 ('A34', 'Server-nya di mana? "Di cloud."', 'Reaksi bingung', 'Tools', 'Awareness', 'IT, legal', 'TikTok/Reels 15 dtk',
  '"Data pelanggan disimpan di mana?" "Di cloud." "Cloud-nya di negara mana?"', 'Jangkrik → register transfer lintas negara + TIA', 'jangkrik · "HAH?"', '—', 'Transfer Data Lintas Negara (TIA)', 'Minta demo',
  'fakta_produk: transfer lintas negara', 7, 6, 7, 7, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A35', 'AI yang ngarang pasal vs AI yang mengutip pasal', 'Drake-style ❌/✅ (digambar ulang)', 'Tools', 'Konversi', 'Legal, DPO', 'LinkedIn/Reels 15 dtk',
  '"Tanya AI soal bunyi pasal:"', '❌ AI yang mengarang bunyi pasal / ✅ Telaah Kebijakan Nexus: bunyi pasal diambil dari knowledge base regulasi', 'buzzer · ding benar', '—', 'Telaah Kebijakan, asisten AI', 'Minta demo',
  'fakta_produk: telaah kebijakan (bunyi pasal dari knowledge base, bukan ditulis AI)', 7, 7, 8, 7, 'Rendah', 'Sedang. Jangan sebut merek AI lain', 'Baru', 'Okt–Nov 2026'),
 ('A36', 'Selamat, kamu DPO sekarang 👏', 'Tepuk tangan sarkas', 'Konsultasi + Pelatihan', 'Konversi', 'DPO/PPDP baru', 'Reels/LinkedIn 15–20 dtk',
  'Bos: "Selamat, kamu DPO sekarang."', 'Tepuk tangan sarkas → DPO 🫠 → DPO Academy + pendampingan konsultan', 'tepuk tangan (synth) · sad violin (synth)', '—', 'DPO Academy, pendampingan', 'Kelas & pendampingan PPDP',
  'UU PDP Ps. 53–54 (penunjukan & tugas PPDP); DPO Academy', 8, 7, 8, 8, 'Rendah', 'Rendah', 'Bisa dari N09', 'Okt 2026'),
 ('A37', 'Konsultan yang kirim PDF lalu hilang', 'Drake-style ❌/✅', 'Konsultasi', 'Konversi', 'Direksi, DPO', 'LinkedIn/Reels 15 dtk',
  '"Konsultan PDP yang kamu butuhkan:"', '❌ kirim dokumen 200 halaman lalu hilang / ✅ mendampingi sampai audit + tools Nexus', 'buzzer · ding benar', '—', 'Konsultasi + Nexus', 'Konsultasi (cek penawaran gratis masih berlaku)',
  '—', 7, 6, 9, 6, 'Rendah', 'Sedang. Jangan menyindir pesaing tertentu', 'Bisa dari N07', 'Nov 2026'),
 ('A38', 'Hapus data saya… yang ada di 7 sistem', 'Ekspektasi vs realita', 'Tools', 'Konversi', 'DPO, IT', 'LinkedIn/Reels 15 dtk',
  '"Ekspektasi: hapus 1 data. Realita:"', 'Data orang yang sama muncul di 7 sistem → Data Discovery menemukan semuanya', 'dun dun dun', '—', 'Data Discovery, DSR', 'Minta demo',
  'fakta_produk: data discovery (cari data satu subjek)', 7, 6, 7, 6, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A39', 'Plot twist: yang bocorin… admin grup', 'Storytime + plot twist', 'Edukasi', 'Awareness + Share', 'Karyawan', 'TikTok/Reels 20–30 dtk',
  '"Storytime: data pelanggan kami bocor. Pelakunya?"', 'Investigasi dramatis → vine boom: "admin grup yang meneruskan file" → pelatihan + telaah kebijakan', 'vine boom · dun dun dun', 'Narator "berat"', 'Telaah Kebijakan, DPO Academy', 'Pernah kejadian di kantormu?',
  '— (cerita fiksi)', 8, 8, 6, 8, 'Sedang', 'Sedang. Cerita fiksi, beri label "ilustrasi"', 'Baru', 'Kapan saja'),
 ('A40', 'Balas komentar: "DPO itu kerjanya apa?"', 'Reply-to-comment TikTok', 'Edukasi', 'Awareness', 'Umum', 'TikTok 30–45 dtk',
  '"Balas @pengguna: \'DPO itu kerjanya apa sih?\'"', '3 poin (menasihati, memantau kepatuhan, jadi narahubung) + meme singkat tiap poin', 'pop', '—', 'Brand', 'Follow untuk tips PDP',
  'UU PDP Ps. 54 (tugas PPDP)', 7, 7, 6, 7, 'Rendah (talking head)', 'Rendah', 'Baru', 'Kapan saja'),
 ('A41', 'Sad violin: form RoPA yang tak pernah diisi', 'Sad violin (melodi synth orisinal)', 'Tools', 'Awareness + Share', 'DPO', 'TikTok/Reels 15 dtk',
  '"Kisah sedih form RoPA yang dikirim ke 12 divisi"', 'Hari 1: dibaca ✓✓ tak dibalas… hari 30 (sad violin) → Nexus: alur + pengingat + pengisian berbantuan AI', 'sad violin (synth) · jangkrik', 'Pesan suara: efek "telepon"', 'RoPA (isi otomatis berbantuan AI)', 'privasimu.com',
  'fakta_produk: ropa (pengisian otomatis berbantuan AI)', 9, 7, 6, 8, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A42', 'Siapa yang punya akses ke data ini? Dun dun dun', 'Dramatic reveal', 'Tools', 'Awareness', 'IT, DPO', 'Reels/LinkedIn 15 dtk',
  '"Siapa yang punya akses ke data pelanggan?"', 'Daftar akses membengkak ("akun magang 2019 masih aktif") dun dun dun → log audit Nexus untuk aktor manusia & AI', 'dun dun dun', '—', 'Log audit', 'Minta demo',
  'fakta_produk: platform (log audit), dukungan PPDP', 7, 6, 7, 6, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A43', '−999 aura: kebiasaan data di kantor', 'Poin aura (slang 2026)', 'Brand / edukasi', 'Share', 'Karyawan', 'TikTok/Reels 15 dtk',
  '"−999 aura: kirim KTP pelanggan lewat grup"', 'Rentetan −aura/+aura cepat → +1000 aura: pakai Nexus', 'auraDown/auraUp · vine boom', '—', 'Brand', 'Aura kantormu berapa?', '—', 9, 9, 5, 9, 'Rendah', 'Rendah', 'Baru (kit N11)', 'Okt 2026'),
 ('A44', 'Cooked vs chill: jam 3 pagi', 'Split-screen', 'Tools', 'Konversi', 'DPO, CISO', 'Reels/LinkedIn 15 dtk',
  '"Jam 3 pagi, insiden. DPO A vs DPO B:"', 'Kiri: cooked (tanpa alur) "FAAAH" / kanan: chill (checklist & templat siap di Nexus)', '"FAAAH" (rekam tim) · centang', '—', 'Manajemen Insiden', 'Minta demo',
  'fakta_produk: breach (checklist & linimasa otomatis)', 8, 8, 8, 7, 'Rendah', 'Rendah', 'Baru', 'Nov 2026'),
 ('A45', 'Dasar pemrosesannya apa? "Adalah pokoknya."', 'Frasa viral "adalah pokoknya" (2026)', 'Edukasi + Tools', 'Awareness + Share', 'Marketing, product, DPO', 'TikTok/Reels 15–20 dtk',
  '"Dasar pemrosesannya apa?" "Adalah pokoknya."', '"FAAAH" → 6 dasar pemrosesan UU PDP → wizard RoPA menanyakannya satu per satu', '"FAAAH" (rekam tim) · pop ×6', '—', 'Wizard RoPA', 'Simpan buat referensi',
  'UU PDP Ps. 20 ayat (2): 6 dasar pemrosesan', 8, 8, 6, 8, 'Rendah', 'Rendah', 'Baru', 'Kapan saja'),
 ('A46', '5 tanda perusahaanmu belum siap PP 33', 'Carousel LinkedIn', 'Konsultasi', 'Konversi', 'Direksi, DPO', 'Carousel 6 slide',
  '"5 tanda perusahaanmu belum siap PP 33"', '5 tanda + solusi → CTA', '—', '—', 'GAP, program siap PP 33', 'Start Pre Check (gratis)',
  'PP 33/2026 (225 pasal), berlaku 16 Jan 2027', 7, 6, 8, 7, 'Rendah', 'Rendah', 'Baru', 'Nov 2026'),
 ('A47', 'Roasting RoPA (live)', 'Roasting (live/webinar) + klip', 'Konsultasi', 'Konversi + Share', 'DPO, legal', 'Live 45–60 mnt + klip 30 dtk',
  '"Kirim RoPA versi dummy-mu, kami roasting live"', 'Konsultan Privasimu me-review contoh RoPA anonim dengan humor → tunjukkan versi Nexus', 'live', '—', 'Konsultasi + RoPA', 'Daftar sesi berikutnya',
  '—', 8, 7, 9, 8, 'Tinggi', 'Sedang. WAJIB data dummy/anonim; peserta setuju direkam', 'Baru', 'Nov–Des 2026'),
 ('A48', '#RoPA60Detik challenge', 'Speedrun challenge', 'Tools', 'Awareness + Konversi', 'DPO, legal', 'TikTok/Reels 30–60 dtk',
  '"Bisa isi 1 RoPA dalam 60 detik?"', 'Timer 60 dtk: wizard RoPA + isi otomatis AI → selesai → tantang rekan', 'detak jam · level up', '—', 'RoPA (isi otomatis AI)', 'Coba di demo, tag rekanmu',
  'fakta_produk: ropa (isi otomatis AI). Catatan waktu HARUS diukur nyata sebelum diklaim', 7, 8, 8, 8, 'Sedang (rekam layar demo)', 'Sedang. Klaim waktu harus terukur', 'Baru', 'Nov 2026'),
]

SOUND = [
 ('Meme', '/en/instant/meme/', 'Vokal ("are you out of your mind?")', 'Saat ada usul praktik data yang ngawur', 'Tinggi: rekaman orang lain', 'Rekam ulang tim: "Kamu gila, ya?"', 'sfx-kustom/gila.wav → \'file:gila\'', 'A09, A29'),
 ('FAAAH', '/en/instant/faaah-63455/', 'Vokal teriakan frustrasi ("Faaaah by Taileons")', 'Momen gagal total / ketahuan belum patuh', 'Tinggi: rekaman kreator (Taileons), tanpa lisensi komersial', 'Rekam ulang tim (teriak panjang "FAAAH") atau ElevenLabs v3 dengan tag [shouts]', 'sfx-kustom/faah.wav → \'file:faah\'', 'A01, A05, A14, A19, A21, A24, A27, A29, A44, A45'),
 ('Sad Violin (the meme one)', '/en/instant/sad-violin-the-meme-one/', 'Musik (cuplikan game/rekaman)', 'Momen sedih-lebay', 'Tinggi: rekaman berhak cipta', 'Synth orisinal "sadviolin" (melodi sendiri)', "'sadviolin'", 'A14, A36, A41'),
 ('Among Us role reveal sound', '/en/instant/among-us-role-reveal-sound-34956/', 'SFX game', 'Pengungkapan "pelaku"', 'Tinggi: aset game (IP)', 'Synth orisinal "reveal"', "'reveal'", 'A39'),
 ('Error SOUNDSS', '/en/instant/error-soundss-25534/', 'SFX error sistem', 'Salah input / password lemah', 'Sedang: suara sistem operasi bermerek', 'Synth orisinal "error"', "'error'", 'A29'),
 ('baby laughing meme', '/en/instant/baby-laughing-meme-56428/', 'Vokal bayi (orang nyata)', 'Tertawa', 'Tinggi: suara anak nyata (data pribadi + hak)', 'Hindari; pakai tawa tim dewasa bila perlu', '—', '—'),
 ('Punch Sound', '/en/instant/punch-sound-86161/', 'SFX pukulan', 'Pukulan telak (fakta keras)', 'Sedang: sumber tidak jelas', 'Synth "hit" / "impact" (sudah ada)', "'hit' · 'impact'", 'A08'),
 ('spiderman meme song', '/en/instant/spiderman-meme-song-37638/', 'Lagu', '—', 'Tinggi: lagu berhak cipta', 'Hindari', '—', '—'),
 ('instagram thud (vine boom)', '/en/instant/instagram-thud-55328/', 'SFX "bwoom"', 'Punchline / reveal', 'Sedang: rekaman asli tak berlisensi', 'Synth "vineboom" (sudah ada)', "'vineboom'", 'A02, A03, A09, A33, A39'),
 ('Shocked sound', '/en/instant/shocked-sound-37548/', 'SFX kaget', 'Kaget', 'Sedang', 'Synth orisinal "shock"', "'shock'", 'A08, A26'),
 ('dun dun dunnnnnnnn', '/en/instant/dun-dun-dunnnnnnnn-68584/', 'SFX dramatis', 'Fakta menakutkan (denda, akses)', 'Sedang', 'Synth "dundun" (sudah ada)', "'dundun'", 'A08, A13, A25, A38, A42'),
 ('Звук фотоаппарата (shutter)', '/en/instant/zvuk-fotoapparata-61186/', 'SFX kamera', 'Freeze frame / bukti', 'Rendah–sedang', 'Synth "shutter" (sudah ada)', "'shutter'", 'A17'),
 ('Death sound (Fortnite)', '/en/instant/death-sound-fortnite-13941/', 'SFX game', 'Gagal/"mati"', 'Tinggi: aset game (IP)', 'Synth orisinal "gameover" (8-bit)', "'gameover'", 'A19, A29'),
 ('Emotional Damage Meme', '/en/instant/emotional-damage-meme-74555/', 'Vokal (catchphrase kreator)', 'Fakta yang "menyakitkan"', 'Tinggi: suara & persona kreator', 'Rekam ulang tim dengan suara & logat sendiri (jangan meniru etnis/logat)', 'sfx-kustom/emotional-damage.wav', 'A08'),
 ('cat laugh meme 1', '/en/instant/cat-laugh-meme-1-15761/', 'Vokal hewan (klip orang lain)', 'Tertawa', 'Sedang', 'Hindari', '—', '—'),
 ('Galaxy meme', '/en/instant/galaxy-meme-18643/', 'Ambience "galaxy brain"', 'Ide "jenius"', 'Sedang', 'Synth "shimmer"/"riserLong" (sudah ada)', "'shimmer'", 'A35'),
 ('Fart Meme Sound', '/en/instant/fart-meme-sound-46799/', 'SFX kentut', '—', 'Brand safety', 'Hindari (tidak sesuai citra B2B)', '—', '—'),
 ('Meme final (créditos finales)', '/en/instant/meme-final-91448/', 'Lagu penutup ("directed by…")', 'Ending gagal', 'Tinggi: lagu berhak cipta', 'Synth orisinal "outro" (jingle kocak)', "'outro'", 'A19, A39'),
 ('RUN vine', '/en/instant/run-vine/', 'Vokal "RUN!"', 'Panik (DSR/insiden)', 'Tinggi: rekaman orang lain', 'Rekam ulang tim: "LARIII!"', 'sfx-kustom/lari.wav', 'A10'),
 ('HAha funny laugh', '/en/instant/haha-funny-laugh-93061/', 'Vokal tawa', 'Tawa', 'Tinggi', 'Rekam tawa tim', 'sfx-kustom/tawa.wav', '—'),
 ('Dexter meme', '/en/instant/dexter-meme-26140/', 'Cuplikan serial TV', '—', 'Tinggi: IP serial', 'Hindari', '—', '—'),
 ('-999 Social Credit Siren', '/en/instant/999-social-credit-siren-82729/', 'Meme politis', '—', 'Tinggi: bermuatan politik', 'Hindari; ganti penghitung "aura" (sudah ada)', "'auraDown'", 'A43'),
 ('asian meme huh?', '/en/instant/asian-meme-huh-49043/', 'Vokal "huh?"', 'Bingung', 'Tinggi: rekaman orang lain; judul bernuansa stereotip', 'Rekam ulang tim: "HAH?" (tanpa meniru logat/etnis)', 'sfx-kustom/hah.wav', 'A09, A11, A28, A34'),
 ('*Snore* mimimimimimi', '/en/instant/snore-mimimimimimi-76562/', 'Vokal kartun mendengkur', 'Rapat membosankan', 'Tinggi: cuplikan kartun', 'Rekam ulang tim (dengkur kocak)', 'sfx-kustom/dengkur.wav', 'A21'),
 ('outro song', '/en/instant/outro-song-77850/', 'Lagu', '—', 'Tinggi: lagu', 'Synth orisinal "outro"', "'outro'", '—'),
 ('Long brain fart', '/en/instant/long-brain-fart-60967/', 'SFX kentut', '—', 'Brand safety', 'Hindari', '—', '—'),
 ('Oh My God Meme', '/en/instant/oh-my-god-meme-88573/', 'Vokal "oh my god"', 'Kaget besar', 'Tinggi: rekaman orang lain', 'Rekam ulang tim: "OH MY GOD" / "YA AMPUN"', 'sfx-kustom/omg.wav', 'A26'),
 ('WIDE PUTIN MEME', '/en/instant/wide-putin-meme-6467/', 'Meme tokoh politik', '—', 'Tinggi: tokoh politik', 'Hindari', '—', '—'),
 ('Du bist gut genug', '/en/instant/du-bist-gut-genug-22336/', 'Vokal bahasa Jerman', '—', 'Sedang', 'Tidak relevan', '—', '—'),
 ('what da dog doin', '/en/instant/what-da-dog-doin-35890/', 'Vokal', 'Bingung melihat alur data', 'Tinggi', 'Rekam ulang tim: "lagi ngapain tuh?"', 'sfx-kustom/ngapain.wav', 'A34'),
 ('Meme mp3 (créditos finales)', '/en/instant/meme-mp3-37545/', 'Lagu penutup', '—', 'Tinggi', 'Synth orisinal "outro"', "'outro'", '—'),
 ('Wow Anime meme', '/en/instant/wow-anime-meme-55752/', 'Vokal anime "wow"', 'Kagum (fitur keren)', 'Tinggi: cuplikan anime', 'Rekam ulang tim "WAAAW" atau synth "tada"', "sfx-kustom/wow.wav · 'tada'", 'A06, A48'),
 ('French meme song', '/en/instant/french-meme-song-55813/', 'Lagu', '—', 'Tinggi: lagu', 'Hindari', '—', '—'),
 ('Fart Meme Sound (Better and louder)', '/en/instant/fart-meme-sound-better-and-louder-32265/', 'SFX kentut', '—', 'Brand safety', 'Hindari', '—', '—'),
 ("'What' Bottom Text Meme", '/en/instant/what-bottom-text-meme-sanctuary-guardian-s-24591/', 'Vokal "what?"', 'Bingung', 'Tinggi', 'Rekam ulang tim "HAH?"', 'sfx-kustom/hah.wav', 'A11'),
 ('DEJA VU MEME', '/en/instant/deja-vu-meme-13405/', 'Lagu (eurobeat)', 'Revisi yang terulang', 'Tinggi: lagu berhak cipta', 'Synth orisinal "eurobeat" (sting cepat)', "'eurobeat'", 'A14, A41'),
]
FX = [
 ('berat', 'Suara berat & gelap (narator "sigma", trailer)', 'Narator Things to Say, fakta menakutkan, suara Pak Bos', 'A03, A08, A18, A39', 'rubberband=pitch=0.78, bass +5 dB, kompresor', 'Ya'),
 ('tupai', 'Suara tinggi lucu (chipmunk)', 'Reaksi "HAH?", suara batin panik, versi "anak magang"', 'A11, A28', 'rubberband=pitch=1.55', 'Ya'),
 ('telepon', 'Seperti telepon / voice note', 'Pesan dari bos, pelanggan, pesan suara di grup', 'A17, A41', 'highpass 450 Hz + lowpass 3.000 Hz + kompresi', 'Ya'),
 ('toa', 'Pengumuman lewat toa/megafon', 'Pengumuman kantor, "PERHATIAN SEMUA DIVISI…"', 'A09, A21', 'band 700–3.500 Hz + distorsi ringan + gema pendek', 'Ya'),
 ('robot', 'Suara mesin/robot', 'Suara "sistem", notifikasi otomatis, bot', 'A29, A35', 'afftfilt robotize (fase dinolkan) + gema', 'Ya'),
 ('gema', 'Gema dramatis', 'Kalimat kunci, penutup, momen "plot twist"', 'A39, A42', 'aecho 180/360 ms', 'Ya'),
 ('aula', 'Ruangan besar/aula', 'Pidato direksi, momen megah', 'A18, A26', 'aecho multi-tap 60/120/240 ms', 'Ya'),
 ('bisik', 'Bisikan (ASMR)', 'GRWM, rahasia, "psst…"', 'A20', 'afftfilt whisperize (fase acak) + highpass', 'Ya'),
 ('lebay', 'Bass boosted/pecah ala meme (versi aman telinga)', 'Punchline super lebay (jarang-jarang!)', 'A19, A43', 'bass +12 dB + acrusher + limiter', 'Ya'),
 ('nangis', 'Suara bergetar mau nangis', 'Momen sedih-lebay (form tak diisi)', 'A14, A41', 'vibrato 7 Hz', 'Ya'),
 ('slowed', 'Slowed + reverb (tren editan)', 'Transisi dramatis, pembuka', '—', 'asetrate 0,85 + gema', 'Tidak (mengubah tempo; khusus potongan tanpa sinkron kata)'),
]
TTS = [
 ('edge-tts (dipakai sekarang)', 'Ardi & Gadis: baku, agak kaku', 'Terbatas', 'Ya (timing per kata)', 'TIDAK untuk iklan komersial (layanan Read Aloud Edge)', 'Gratis', 'Tidak ada', 'Hanya placeholder untuk draf & timing.', ''),
 ('Azure AI Speech', 'Suara sama (Ardi/Gadis), resmi', 'Terbatas untuk id-ID', 'Ya', 'Ya', 'Bayar per karakter', 'Akun Azure + kunci API (diisi sendiri)', 'Pengganti resmi tercepat bila suka suara sekarang.', ''),
 ('ElevenLabs (Eleven v3 / Multilingual v2)', 'Sangat natural; ada suara lokal (Andi, Bian, Dakocan, Putri Maharani, Ahmad, dll.)', 'Sangat ekspresif; tag [whispers] [laughs] [sarcastically] [shouts]', 'Ya: endpoint with-timestamps (per karakter) → langsung sinkron', 'Ya, mulai paket Starter', 'Starter ± US$6/bln (30 rb kredit); Creator US$22/bln (121 rb) (cek harga terbaru)', 'Akun + API key (disetel sendiri sebagai env var, bukan dikirim ke saya)',
  'REKOMENDASI UTAMA untuk video meme (bisa teriak "FAAAH", bisik, sarkas). 11 video ± 10 rb karakter/bulan.', 'https://elevenlabs.io/pricing'),
 ('Google Cloud TTS: Chirp 3 HD (id-ID)', 'Natural, gaya percakapan', 'Sedang', 'Perlu dicek; kalau tidak ada, audio diselaraskan otomatis seperti VN', 'Ya', 'Bayar per karakter', 'Akun GCP + kunci', 'Alternatif kuat, stabil untuk volume besar.', 'https://docs.cloud.google.com/text-to-speech/docs/chirp3-hd'),
 ('Prosa.ai (lokal Indonesia)', 'Sangat Indonesia (Dimas formal/ekspresif, Ocha ramah)', 'Sedang', 'Perlu dicek; bisa diselaraskan otomatis seperti VN', 'Cek ketentuan paket', 'Lite Rp50 rb/35 rb karakter; Rp150 rb/100 rb; Pro Rp450 rb/500 rb per bulan (per berita; cek terbaru)', 'Akun Prosa', 'Pilihan lokal, logat paling "Indonesia".', 'https://gizmologi.id/aplikasi/prosa-ai-hadirkan-pembaruan-text-to-speech/'),
 ('Rekaman tim (VN)', 'Paling otentik', 'Sesuai pengisi suara', 'Ya: diselaraskan otomatis (vn/)', 'Ya (milik sendiri)', 'Gratis', 'HP + ruangan senyap', 'Terbaik untuk suara meme (FAAAH, HAH?) & karakter.', ''),
]
PLAN = [
 ('Awareness', 'Musim anggaran 2027 dimulai', 'A04, A12, A43', 'A27'),
 ('Awareness', '—', 'A02, A17, A18', 'A30'),
 ('Awareness', '—', 'A01, A21, A45', 'A36'),
 ('Awareness → Pertimbangan', '—', 'A03, A06, A16', 'A35'),
 ('Pertimbangan', 'Anggaran difinalkan', 'A14, A19, A41', 'A08, A27'),
 ('Pertimbangan', '11.11', 'A09, A44', 'A15'),
 ('Pertimbangan', '—', 'A05, A11, A28', 'A26, A46'),
 ('Pertimbangan → Konversi', 'Menjelang 12.12', 'A25, A07', 'A31, A33'),
 ('Konversi', '3 Des: Hari Disabilitas Internasional', 'A32, A22', 'A37'),
 ('Konversi', '12.12', 'A22, A25', 'A47 (live)'),
 ('Konversi', '—', 'A13, A39', 'A23 (mulai hitung mundur)'),
 ('Konversi', 'Natal', 'A10, A34', 'A23'),
 ('Konversi', 'Tahun Baru', 'A24', 'A23, A46'),
 ('Peluncuran PP 33', '—', 'A24, A40', 'A23, A48'),
 ('Peluncuran PP 33', '16 Jan 2027: PP 33 berlaku', 'A05, A42', 'A23 (hari H), A26'),
 ('Pasca peluncuran', '—', 'A20, A38', 'A37'),
]
