# Keluarga 2 · GRAFIS & BENTUK: bentuk, garis, dan diagram yang bercerita. Satu baris = satu gaya + satu usulan video.
from gaya_base import R

ROWS = [
    # ------------------------------------------------------------------ sudah dipakai
    R('GB01', 'Swiss poster / grid',
      'Grid tegas, huruf besar, blok warna datar seperti poster Swiss.',
      'Tata letak grid 12 kolom; blok warna geser; tipografi tebal.',
      'Sudah (N08)', 3, 7, 9,
      'Program Siap PP 33', 'Anomali',
      'Poster kinetik “siap PP 33”.',
      'Masalah → program → langkah → CTA konsultasi',
      'Program siap PP 33', '—', '49,4 dtk', 'N08 (sudah dirender)'),
    R('GB02', 'Blueprint (gambar teknik)',
      'Garis putih di atas biru tua seperti denah arsitek.',
      'Garis digambar (stroke), kisi halus, anotasi ukuran.',
      'Sudah (N10)', 3, 7, 9,
      'Holding & Anak Usaha', 'Anomali',
      'Denah grup usaha tergambar.',
      'Struktur grup → standar bersama → dasbor grup → CTA',
      'Holding', 'holding-header', '36 dtk', 'N10 (sudah dirender)'),

    # ------------------------------------------------------------------ garis
    R('GB05', 'One-line art (satu garis tanpa putus)',
      'Satu garis tinta yang tidak pernah putus menggambar semua adegan, dengan bercak warna pastel di belakangnya.',
      'Satu path SVG panjang; stroke-dashoffset membuka garis; kamera mengikuti ujung pena; seluruh rute membentuk gambar besar saat kamera mundur.',
      'Sudah (GB05)', 4, 10, 9,
      'Satu Garis', 'Reverse psychology',
      '“Jangan ikuti garis ini… kalau kamu sudah tahu ke mana saja data pelangganmu pergi.”',
      'Garis menggambar Rina & formulir → mengalir ke marketing, CS, pihak ketiga, cloud → kusut → di Nexus terurai: bukti persetujuan, RoPA, DPIA, DSR → seluruh garis membentuk gembok → CTA',
      'Platform (Consent, RoPA, DPIA, DSR)', '—', '64 dtk', 'Flow unggulan “Perjalanan Satu Data” (versi 60 dtk)',
      'Dikerjakan pertama (permintaan). Sudah dirakit di gb05-satu-garis; tinggal render. Rina = tokoh ilustrasi.'),
    R('GB06', 'Ikon garis menggambar sendiri',
      'Ikon garis tipis tergambar dari nol, banyak goresan.',
      'stroke-dashoffset per goresan dengan jeda bertingkat.',
      'Bisa', 2, 6, 9,
      'Lima Fase', 'Relate',
      '“Jam 3 pagi. Alurnya sudah siap.”',
      'Ikon 5 fase insiden tergambar berurutan → templat pemberitahuan & RACI → CTA',
      'Manajemen Insiden', 'breach-detail, breach-aksi', '15 dtk', 'P30'),
    R('GB35', 'Benang kusut → rapi',
      'Gulungan benang kusut ditarik perlahan menjadi garis rapi.',
      'Path kusut ↔ path lurus dengan jumlah titik sama; interpolasi.',
      'Bisa', 3, 8, 8,
      'RoPA_final_revisi3_FIX', 'Relate',
      '“Angkat tangan kalau kamu punya file bernama RoPA_final_revisi3_FIX.xlsx.”',
      'Benang kusut = versi file → ditarik jadi satu garis = satu register → CTA',
      'RoPA', 'ropa-list-baru', '15 dtk', 'M04 / P02'),
    R('GB37', 'Garis detak (EKG)',
      'Garis monitor detak jantung berjalan; ritmenya berubah sesuai cerita.',
      'Path gelombang dari rumus; kepala garis bercahaya; grid monitor.',
      'Bisa', 2, 7, 8,
      'Detak Jam 3 Pagi', 'Relate',
      '“Detak jantung DPO saat notifikasi jam 3 pagi.”',
      'Detak tenang → melonjak saat notifikasi → stabil lagi saat alur 5 fase tampil → CTA',
      'Manajemen Insiden', 'breach-detail', '10 dtk', 'M11 / A44'),
    R('GB17', 'Garis kontur (topografi)',
      'Garis kontur peta membentuk bukit dan lembah.',
      'Path kontur bertingkat dari fungsi noise deterministik; warna per ketinggian.',
      'Bisa', 3, 7, 8,
      'Peta Risiko', 'Anomali',
      '“Proyek paling berisiko di kantormu biasanya proyek yang paling ditunggu-tunggu.”',
      'Kontur datar → satu puncak merah naik → matriks 5×5 DPIA → rencana mitigasi → CTA',
      'DPIA', 'dashboard-risiko, dpia-risiko', '15 dtk', 'M05'),
    R('GB18', 'Guilloché (pola sertifikat)',
      'Pola garis halus berpilin seperti di sertifikat dan uang kertas.',
      'Kurva rosette (rumus epitrochoid) digambar stroke; bingkai sertifikat.',
      'Bisa', 3, 8, 9,
      'Bukti', 'Logika dipatahkan',
      '“Klik ‘Setuju’ tanpa bukti sama dengan tidak pernah setuju.”',
      'Pola guilloché tergambar → jadi lembar bukti persetujuan: siapa, kapan, kanal → CTA',
      'Consent (log & bukti)', 'consent-detail', '15 dtk', 'M08'),
    R('GB53', 'Peta jalur (transit map)',
      'Peta jalur kereta: garis warna-warni, stasiun bulat, titik transit.',
      'Path ortogonal/45°; stasiun lingkaran; kereta titik berjalan di jalur.',
      'Bisa', 3, 9, 9,
      'Peta Jalur Kepatuhan', 'Anomali',
      '“Naik dari stasiun mana pun. Tujuannya sama: siap diperiksa.”',
      'Jalur GAP → RoPA → DPIA → Consent/DSR/Insiden → Fire Drill; titik transit = modul terhubung → CTA',
      'Platform (siklus modul)', '—', '20 dtk', 'Baru', 'Desain peta sendiri; tanpa lambang operator kereta.'),
    R('GB54', 'Papan sirkuit',
      'Jalur tembaga papan sirkuit; sinyal cahaya mengalir.',
      'Path ortogonal + titik solder; kepala cahaya berjalan (dash).',
      'Bisa', 2, 7, 8,
      'Tersambung', 'Anomali',
      '“Persetujuan ditarik di aplikasi. Sistem lain tahu?”',
      'Sinyal “tarik persetujuan” mengalir lewat API & webhook ke sistem internal → semua kanal menghormati → CTA',
      'Consent (API & webhook)', 'consent-detail', '15 dtk', 'Flow unggulan (Bab 1)'),
    R('GB27', 'Labirin',
      'Labirin dari atas; garis mencari jalan, buntu, lalu menemukan rute.',
      'Labirin grid tetap; jalur solusi digambar stroke; jalan buntu berkedip.',
      'Sudah (GB27)', 3, 8, 8,
      'Mencari Satu Dokumen', 'Relate',
      '“Beginilah rasanya mencari satu dokumen bukti saat audit.”',
      'Garis tersesat di labirin folder → tampilan atas: jalur lurus → analisis bukti per pertanyaan → CTA',
      'GAP Assessment (analisis bukti)', 'gap-rekomendasi', '15 dtk', 'Baru'),
    R('GB48', 'Denah kantor',
      'Denah kantor garis putih; titik penyimpanan data menyala.',
      'Path denah digambar; pin muncul berurutan; penghitung.',
      'Bisa', 2, 7, 8,
      'Denah Kantor', 'Anomali',
      '“Di denah kantor ini ada 9 tempat penyimpanan data. Kamu tahu berapa?”',
      'Pin menyala: lemari, laptop, server, email, pihak ketiga → katalog sistem & sumber data → CTA',
      'Data Discovery (katalog sistem)', '—', '15 dtk', 'Baru', 'Angka 9 = ilustrasi.'),

    # ------------------------------------------------------------------ bentuk dasar
    R('GB03', 'Flat geometric (Bauhaus)',
      'Lingkaran, kotak, segitiga warna primer menyusun ikon dan adegan.',
      'Div/SVG bentuk dasar; pindah-putar-skala; palet 4 warna.',
      'Sudah (GB03)', 2, 7, 8,
      'Tiga Bentuk', 'Anomali',
      '“Semua urusan data pribadi bisa digambar dengan tiga bentuk.”',
      'Lingkaran = orang, kotak = sistem, segitiga = risiko → tersusun jadi alur RoPA–DPIA–DSR → CTA',
      'Platform', '—', '15 dtk', 'Baru'),
    R('GB04', 'Gooey blob (gumpalan cair)',
      'Gumpalan cair yang saling menempel, menyatu, dan memisah.',
      'Filter SVG goo (blur + color matrix) pada lingkaran bergerak.',
      'Bisa', 2, 8, 7,
      'Lima Versi Data yang Sama', 'Anomali',
      '“Lima divisi. Lima versi data pelanggan yang sama.”',
      'Lima gumpalan terpisah → menyatu jadi satu → modul saling terhubung → CTA',
      'Platform', '—', '15 dtk', 'Baru'),
    R('GB14', 'Tangram',
      'Tujuh keping geometris disusun ulang menjadi berbagai gambar.',
      'Tujuh poligon; tiap susunan = daftar posisi & rotasi; interpolasi antarsusunan.',
      'Bisa', 3, 9, 8,
      'Tujuh Keping', 'Anomali',
      '“Tujuh keping yang sama. Susunannya yang menentukan.”',
      'Keping berserakan → tanda tanya → rumah → perisai → logo → CTA',
      'Platform', '—', '15 dtk', 'Baru'),
    R('GB38', 'Morph ikon',
      'Satu bentuk berubah mulus menjadi bentuk lain.',
      'Interpolasi titik path dengan jumlah titik sama.',
      'Bisa', 3, 7, 9,
      'Dokumen Jadi Perisai', 'Anomali',
      '“Dokumen yang tercatat berubah jadi ini.”',
      'Dokumen → perisai → gembok → logo',
      'Platform', '—', '5 dtk', 'Baru (bumper logo)'),
    R('GB20', 'Diagram Venn',
      'Lingkaran tembus pandang saling bertumpuk; irisan diberi label.',
      'Lingkaran mix-blend; label muncul di irisan.',
      'Sudah (GB20)', 1, 7, 8,
      'Irisan', 'Relate',
      '“Legal. IT. Bisnis. Yang di tengah itu kamu, DPO.”',
      'Tiga lingkaran mendekat → irisan tengah menyala → antrean kerja & Priva → CTA',
      'Dukungan PPDP', 'ai-agent-home', '10 dtk', 'A12 / A13'),
    R('GB39', 'Kaleidoskop',
      'Pola simetris berputar seperti teropong kaleidoskop.',
      'Satu irisan konten dicerminkan 6–8 kali (transform + clip-path).',
      'Sudah (GB39)', 3, 8, 6,
      'Dari Dekat, Kacau', 'Logika dipatahkan',
      '“Dari dekat terlihat kacau. Dari jauh, ini pola.”',
      'Potongan layar modul berputar → mundur: pola simetris → logo → CTA',
      'Platform', 'dashboard', '10 dtk', 'Baru (bumper)'),
    R('GB19', 'Batik geometris (kawung)',
      'Motif kawung/ceplok tersusun berulang dan berputar pelan.',
      'Elips SVG berulang dalam grid; muncul bergelombang dari tengah.',
      'Bisa', 3, 8, 8,
      'Pola', 'Anomali',
      '“Pola yang rapi selalu lahir dari aturan yang jelas.”',
      'Satu elips → kawung → kain penuh → aturannya: UU PDP & PP 33 → Nexus → CTA',
      'Brand, Platform', '—', '15 dtk', 'Baru (lokal)', 'Pakai motif umum (kawung/ceplok); hormati makna budaya.'),
    R('GB50', 'Cut-out organik',
      'Potongan kertas berbentuk bebas berwarna cerah, bertumpuk.',
      'Path organik; bayangan tipis; gerak melayang.',
      'Bisa', 2, 7, 8,
      'Kinda Chic', 'Logika dipatahkan',
      '“Kinda chic to… lapor insiden tepat waktu.”',
      'Tiga kartu “kinda chic” dengan bentuk potongan kertas → layar asli → CTA',
      'Insiden, RoPA', 'dashboard', '15 dtk', 'A07'),
    R('GB49', 'Stiker die-cut',
      'Stiker bergaris tepi putih ditempel satu-satu, saling tumpuk.',
      'Elemen dengan outline putih tebal + bayangan; masuk dengan efek tempel.',
      'Sudah (GB49)', 2, 7, 6,
      'DPO Starter Pack', 'Relate',
      '“DPO starter pack.”',
      'Stiker: kopi, 47 tab, file final_final, grup chat → stiker terakhir: Nexus → CTA',
      'Brand', '—', '10 dtk', 'A13'),

    # ------------------------------------------------------------------ tekstur & material
    R('GB08', 'Halftone / risograph',
      'Cetak sablon dua warna dengan titik raster dan registrasi sedikit meleset.',
      'Pola radial-gradient titik + mix-blend multiply dua lapis warna bergeser.',
      'Bisa', 2, 8, 7,
      '5 Tanda Belum Siap', 'Anomali',
      '“5 tanda perusahaanmu belum siap PP 33. Nomor 3 paling sering.”',
      'Poster bernomor 1–5 dicetak lapis demi lapis → GAP Assessment → CTA',
      'GAP, program siap PP 33', 'gap-rekomendasi', '20 dtk', 'A46'),
    R('GB09', 'Glassmorphism / aurora',
      'Kartu kaca buram melayang di atas gradasi bergerak.',
      'backdrop-filter blur + gradasi kanvas; kartu paralaks.',
      'Bisa', 2, 7, 9,
      'Satu Layar', 'Logika dipatahkan',
      '“Laporan terbaik bukan yang paling tebal.”',
      'Kartu kaca KPI muncul satu-satu (skor, DSR, insiden) dari dasbor asli → CTA',
      'Dasbor kepatuhan', 'dashboard, dashboard-postur', '15 dtk', 'P32'),
    R('GB10', 'Claymorphism (3D lembut)',
      'Ikon gembung lembut seperti mainan, bayangan halus.',
      'Bentuk membulat + bayangan dalam/luar ganda; pantulan kecil.',
      'Bisa', 3, 8, 8,
      'Pengguna Kelas 5 SD', 'Anomali',
      '“Pengguna paling setia aplikasimu mungkin masih kelas 5 SD.”',
      'Avatar anak gembung → formulir → “butuh izin wali” → Children Pro → CTA',
      'Children Pro', 'children-pro', '15 dtk', 'M09 / P08', 'Tanpa foto anak; ilustrasi saja.'),
    R('GB12', 'Low-poly',
      'Bentang alam dari segitiga-segitiga datar berwarna.',
      'Poligon SVG dengan warna per sisi; cahaya bergeser.',
      'Bisa', 3, 7, 7,
      'Mendaki Tingkat', 'Anomali',
      '“Tidak ada lift menuju puncak kepatuhan. Tapi ada peta.”',
      'Gunung low-poly → bendera tiap tingkat kematangan → jalur rekomendasi → CTA',
      'Maturity Assessment', '—', '15 dtk', 'M03 (varian)', 'Perlu screenshot baru Maturity.'),
    R('GB13', 'Origami (lipat kertas)',
      'Kertas dilipat berkali-kali menjadi bentuk baru.',
      'Panel CSS 3D berputar di engsel lipatan; bayangan lipatan.',
      'Sudah (GB13)', 4, 9, 8,
      'Selembar Kontrak', 'Logika dipatahkan',
      '“Kontrak sudah ditandatangani. Bukan berarti datanya aman.”',
      'Kontrak dilipat jadi pesawat (dilupakan) → dibuka lagi → telaah per bab + rekomendasi klausul → dilipat jadi perisai → CTA',
      'Telaah Kontrak', '—', '20 dtk', 'M17 / P09'),
    R('GB15', 'Piksel / mosaik',
      'Kotak-kotak kecil acak yang tersortir menjadi gambar rapi.',
      'Grid sel; posisi awal acak (hash) → posisi akhir; warna per kategori.',
      'Bisa', 2, 8, 7,
      'Sortir', 'Relate',
      '“Tonton sampai rapi.”',
      'Piksel acak = data tercampur → tersortir: umum / spesifik / bukan data pribadi → CTA',
      'Data Discovery', '—', '10 dtk', 'Baru', 'Efek memuaskan; cocok untuk loop.'),
    R('GB16', 'Titik berpindah (partikel membentuk ikon)',
      'Ribuan titik berkumpul membentuk ikon, lalu bubar membentuk ikon lain.',
      'Canvas: titik target dari sampling bentuk; interpolasi posisi dengan jeda hash.',
      'Bisa', 3, 8, 8,
      'Gambar Besar', 'Anomali',
      '“Satu titik tidak berarti apa-apa. Sampai semuanya terkumpul.”',
      'Titik = catatan kecil → membentuk dokumen → perisai → logo → CTA',
      'Platform', '—', '10 dtk', 'Baru (bumper)'),

    # ------------------------------------------------------------------ diagram & data
    R('GB11', 'Infografik animasi',
      'Batang, donat, dan garis tumbuh dengan angka yang menghitung.',
      'SVG/div tinggi-lebar dari data; angka odometer.',
      'Sudah (GB11)', 2, 6, 9,
      'Patuh Itu Bukan Ya/Tidak', 'Logika dipatahkan',
      '“‘Sudah patuh atau belum?’ itu pertanyaan yang salah.”',
      'Sakelar ya/tidak → berubah jadi tingkat kematangan per domain → rekomendasi peningkatan → CTA',
      'Maturity Assessment', '—', '20 dtk', 'M03', 'Perlu screenshot baru Maturity.'),
    R('GB21', 'Flowchart / pohon keputusan',
      'Kotak dan belah ketupat terhubung panah; jalur aktif menyala.',
      'Node div + panah SVG digambar; jalur disorot mengikuti VO.',
      'Bisa', 2, 6, 9,
      'Apakah Ini Data Pribadi?', 'Relate',
      '“Flowchart paling jujur di kantor: ‘Apakah ini data pribadi?’”',
      'Pertanyaan → Ya → spesifik? → Ya → risiko TINGGI → draf DPIA otomatis → CTA',
      'RoPA → DPIA otomatis', 'ropa-data-spesifik', '15 dtk', 'A11'),
    R('GB22', 'Mind map / graf simpul',
      'Simpul-simpul terhubung garis; satu ditarik, yang lain ikut bergerak.',
      'Posisi simpul dari rumus pegas sederhana (deterministik); garis mengikuti.',
      'Bisa', 3, 7, 9,
      'Tarik Satu', 'Anomali',
      '“Tarik satu data. Lihat apa saja yang ikut bergerak.”',
      'Simpul “data pelanggan” ditarik → RoPA, DPIA, pihak ketiga, kontrak ikut → semua saling terkait di Nexus → CTA',
      'Platform, Pihak Ketiga', '—', '15 dtk', 'Baru'),
    R('GB23', 'Linimasa / Gantt',
      'Garis waktu horizontal dengan batang tahapan yang terisi.',
      'Batang scaleX berurutan; penanda hari ini bergerak.',
      'Sudah (GB23)', 1, 5, 9,
      'Hitung Mundur Sudah Jalan', 'Anomali',
      '“Hitung mundur sudah jalan. Rencanamu?”',
      'Garis waktu ke 16 Jan 2027 → tahapan program siap PP 33 terisi → CTA konsultasi',
      'Program siap PP 33', '—', '15 dtk', 'P28 / N08'),
    R('GB24', 'Peta titik & busur',
      'Peta dunia dari titik-titik; busur cahaya menghubungkan negara.',
      'Titik peta dari data grid kasar; busur path digambar + kepala bercahaya.',
      'Berat', 4, 8, 9,
      'Cloud-nya di Negara Mana?', 'Logika dipatahkan',
      '“‘Datanya di mana?’ ‘Di cloud.’ ‘Cloud-nya di negara mana?’”',
      'Busur dari Indonesia ke luar → tanda tanya → register transfer + TIA → CTA',
      'Transfer Data Lintas Negara', '—', '20 dtk', 'M14 / P10', 'Perlu data titik peta; tanpa nama penyedia cloud.'),
    R('GB25', 'Radar / sonar',
      'Layar radar hijau; jarum menyapu dan titik temuan menyala.',
      'Conic-gradient berputar + titik muncul saat tersapu; pendar memudar.',
      'Bisa', 2, 8, 8,
      'Yang Tidak Kamu Tahu Ada', 'Logika dipatahkan',
      '“Data paling berisiko bukan yang paling sensitif. Tapi yang tidak kamu tahu ada.”',
      'Radar menyapu → titik temuan: NIK di kolom lama → dikaitkan ke RoPA → CTA',
      'Data Discovery', '—', '15 dtk', 'M15 / P15'),
    R('GB26', 'Barcode / QR',
      'Garis barcode dan kotak QR tersusun, dipindai garis merah.',
      'Batang lebar dari hash; garis pindai; kode teks di bawah.',
      'Bisa', 1, 6, 8,
      'Semua Punya Nomor', 'Anomali',
      '“Semua yang tercatat punya nomor. Yang tidak tercatat?”',
      'Barcode ROPA-, DPIA-, DSR-, BRC- dipindai → satu benda tanpa kode → CTA',
      'RoPA, DPIA, DSR, Insiden (kode otomatis)', 'ropa-tersimpan', '10 dtk', 'Baru'),
    R('GB40', 'Speedometer / meter jarum',
      'Jarum meter bergerak dari merah ke hijau.',
      'Busur conic-gradient + jarum rotasi dari nilai; angka menghitung.',
      'Bisa', 1, 6, 9,
      'Berani Lihat Jarumnya?', 'Reverse psychology',
      '“Jangan lihat jarum ini kalau belum siap.”',
      'Jarum bergetar → berhenti di 56 “Cukup” → tiga lapis penyusun skor → CTA',
      'Postur Privasi', 'postur-privasi', '10 dtk', 'M02 (varian)', 'Angka dari data demo di screenshot.'),
    R('GB45', 'Lapisan terurai (exploded view)',
      'Satu benda terangkat menjadi lapisan-lapisan yang melayang.',
      'Panel CSS 3D bertumpuk; jarak antarlapis dianimasikan; label tiap lapis.',
      'Sudah (GB45)', 3, 8, 9,
      'Tiga Lapis', 'Anomali',
      '“Skor ini ternyata punya tiga lapis.”',
      'Skor postur 56 → terurai: lapis data, proses, respons → lapis terlemah disorot → CTA',
      'Postur Privasi', 'postur-privasi', '15 dtk', 'M01 (varian)', 'Angka dari data demo di screenshot.'),
    R('GB44', 'Gunung es (irisan)',
      'Gunung es: puncak kecil di atas air, badan raksasa di bawah.',
      'Poligon es + garis air bergelombang; kamera turun ke bawah permukaan.',
      'Bisa', 2, 8, 9,
      'Yang di Bawah Permukaan', 'Logika dipatahkan',
      '“Yang terlihat: satu formulir pendaftaran.”',
      'Puncak = formulir → turun: sistem, salinan, pihak ketiga, arsip lama → Data Discovery memetakan → CTA',
      'Data Discovery', '—', '20 dtk', 'M15'),
    R('GB46', 'Orbit',
      'Ikon modul mengorbit satu pusat.',
      'Rotasi orbit elips dengan kecepatan berbeda; garis orbit tipis.',
      'Bisa', 2, 6, 8,
      'Satu Pusat', 'Anomali',
      '“Semua modul berputar di satu pusat.”',
      'Modul melayang acak → tertarik ke orbit → pusat: Nexus → CTA',
      'Platform', '—', '10 dtk', 'Baru (bumper)'),
    R('GB36', 'Rasi bintang',
      'Titik bintang dihubungkan garis membentuk rasi.',
      'Titik berkelip (hash) + garis digambar antarbintang.',
      'Bisa', 2, 7, 8,
      '12 Bintang', 'Anomali',
      '“12 anak usaha. Tanpa garis penghubung, itu cuma titik-titik.”',
      '12 bintang terpisah → garis menghubungkan → rasi = standar grup → dasbor holding → CTA',
      'Holding', 'holding-header', '15 dtk', 'M21 / A33', 'Tanpa nama grup/perusahaan nyata.'),

    # ------------------------------------------------------------------ benda & mekanisme
    R('GB07', 'Isometrik miniatur',
      'Kantor mungil dilihat dari sudut atas; jam berputar, tugas menumpuk.',
      'CSS 3D (rotateX 60° rotateZ 45°) balok tiga sisi; cahaya berubah pagi–malam.',
      'Berat', 5, 9, 8,
      'Sehari Jadi DPO (Versi Jujur)', 'Relate',
      '“Day in the life of a DPO. Versi jujur.”',
      '08.00 kopi → 10.00 DSR masuk → 13.00 rapat → 03.00 insiden → antrean kerja Nexus merapikan → CTA',
      'Dukungan PPDP, DSR, Insiden', 'dashboard', '30 dtk', 'A21'),
    R('GB29', 'Efek domino',
      'Deretan domino jatuh berantai, bercabang, memicu hal berikutnya.',
      'Rotasi tiap keping berurutan dari rumus; cabang dengan jeda.',
      'Bisa', 3, 9, 9,
      'Satu Centang', 'Anomali',
      '“Satu centang di formulir ini menjatuhkan semua yang ada di belakangnya.”',
      'Centang “data spesifik” → domino jatuh: risiko TINGGI → draf DPIA dibuat otomatis → rencana penanganan risiko → CTA',
      'RoPA → DPIA (otomatis)', 'ropa-data-spesifik, dpia-list', '15 dtk', 'A11 / M05'),
    R('GB30', 'Roda gigi',
      'Roda gigi berputar saling menggerakkan.',
      'SVG roda gigi; rasio putar dari jumlah gigi.',
      'Bisa', 2, 6, 8,
      'Tiga Roda', 'Relate',
      '“Kalau satu orang jadi pembuat, penelaah, dan penyetuju sekaligus, itu bukan alur. Itu lingkaran.”',
      'Satu roda berputar sendiri → tiga roda: Maker, Reviewer, Approver → riwayat perubahan → CTA',
      'RoPA (alur Maker–Reviewer–Approver)', '—', '15 dtk', 'Baru'),
    R('GB31', 'Timbangan (neraca)',
      'Neraca dua lengan; beban ditambah, lengan miring.',
      'Rotasi lengan dari selisih beban; piring menggantung tegak.',
      'Bisa', 2, 7, 9,
      'Bukan Tiket Bebas', 'Logika dipatahkan',
      '“‘Kan kita punya kepentingan yang sah.’ Kalimat ini bukan tiket bebas.”',
      'Kepentingan organisasi di kiri, hak subjek data di kanan → ditimbang → hasil didokumentasikan (LIA) → CTA',
      'LIA', '—', '15 dtk', 'M06 / P24', 'Perlu screenshot baru LIA.'),
    R('GB32', 'Menara balok',
      'Menara balok kayu; satu balok ditarik, menara goyah.',
      'Balok tersusun; goyangan dari rumus sinus teredam; runtuh terhitung.',
      'Bisa', 3, 8, 8,
      'Balok yang Bukan Milikmu', 'Anomali',
      '“Kebocoran bisa lewat pintu yang bukan milikmu.”',
      'Menara = sistemmu; balok bawah berlabel “pihak ketiga” ditarik → goyah → asesmen & skor pihak ketiga → CTA',
      'Manajemen Risiko Pihak Ketiga', '—', '15 dtk', 'M13 / P14', 'Balok polos, tanpa merek mainan.'),
    R('GB52', 'Rantai',
      'Mata rantai tersambung; satu mata retak.',
      'Mata rantai SVG berulang; retakan digambar; sorot.',
      'Sudah (GB52)', 2, 6, 8,
      'Mata Rantai Terlemah', 'Anomali',
      '“Keamanan datamu sekuat pihak ketigamu yang paling lemah.”',
      'Rantai ditarik → satu mata retak berlabel pihak ketiga → kuesioner asesmen lewat tautan → skor → CTA',
      'Manajemen Risiko Pihak Ketiga', '—', '15 dtk', 'M13 / A15'),
    R('GB28', 'Puzzle',
      'Keping puzzle saling mengunci membentuk gambar.',
      'Path keping dengan tonjolan; keping masuk dari luar layar.',
      'Bisa', 2, 6, 8,
      'Satu Keping Hilang', 'Anomali',
      '“Satu keping hilang, gambarnya tidak pernah selesai.”',
      'Puzzle modul hampir lengkap → satu lubang: pihak ketiga → keping masuk → CTA',
      'Pihak Ketiga, Platform', '—', '10 dtk', 'M13 (varian)'),
    R('GB33', 'Ban berjalan (pabrik)',
      'Ban berjalan pabrik; benda masuk mesin, keluar dalam bentuk baru.',
      'Sabuk pola bergerak; mesin kotak dengan lampu; benda translateX.',
      'Bisa', 3, 8, 8,
      'Atau Jangan', 'Reverse psychology',
      '“Silakan ketik ulang 200 dokumen RoPA-mu satu per satu… atau jangan.”',
      'Dokumen Word/Excel masuk mesin → keluar sebagai rekaman RoPA rapi → CTA',
      'Document Import (AI)', '—', '15 dtk', 'M18 / P19', '“200” = ilustrasi.'),
    R('GB34', 'Pipa & tetesan',
      'Jaringan pipa; satu sambungan menetes, tetesan makin cepat.',
      'Pipa path tebal; tetesan jatuh (rumus gravitasi); genangan membesar.',
      'Bisa', 2, 7, 8,
      'Tetes Pertama', 'Anomali',
      '“Tetes pertama jarang terdengar.”',
      'Tetes kecil diabaikan → genangan → insiden dicatat: daftar periksa penahanan + hitung mundur → CTA',
      'Manajemen Insiden', 'breach-fase', '15 dtk', 'M11 (varian)'),
    R('GB51', 'Jam pasir',
      'Jam pasir; butir jatuh, tumpukan bawah membesar.',
      'Butir canvas dengan lintasan rumus; tinggi tumpukan dari waktu.',
      'Bisa', 3, 7, 8,
      '72 Jam', 'Relate',
      '“Email paling ditakuti customer service: ‘Tolong hapus semua data saya.’”',
      'Jam pasir dibalik saat email masuk → alur handler–reviewer–approver → selesai sebelum habis → CTA',
      'DSR', 'dsr-form, dsr-detail', '15 dtk', 'M07 / P23'),
    R('GB47', 'Tumbuh (tanaman)',
      'Tunas tumbuh menjadi pohon; tiap cabang satu capaian.',
      'Path cabang digambar bertahap; daun muncul (skala).',
      'Bisa', 3, 7, 8,
      'Tidak Tumbuh Semalam', 'Logika dipatahkan',
      '“Kepatuhan tidak tumbuh dalam semalam. Tapi bisa diukur tiap musim.”',
      'Tunas → cabang per domain → tingkat kematangan naik → CTA',
      'Maturity Assessment', '—', '15 dtk', 'M03 (varian)'),

    # ------------------------------------------------------------------ ilusi
    R('GB41', 'Scanimation (ilusi garis geser)',
      'Kisi garis hitam digeser; gambar diam di bawahnya tampak bergerak.',
      'Gambar gabungan 6 frame bergaris + masker kisi translateX.',
      'Bisa', 4, 10, 7,
      'Geser Garisnya', 'Anomali',
      '“Gambar ini diam. Geser garisnya.”',
      'Kisi bergeser → ikon data tampak berjalan → “data tidak pernah diam” → RoPA mencatat alirannya → CTA',
      'RoPA, Data Discovery', '—', '15 dtk', 'Baru'),
    R('GB42', 'Bentuk mustahil (ilusi optik)',
      'Bentuk yang tampak masuk akal dari satu sudut, janggal saat diputar.',
      'Susunan balok CSS 3D yang hanya sejajar dari satu sudut kamera.',
      'Bisa', 4, 9, 8,
      'Dari Sudut Ini', 'Logika dipatahkan',
      '“Dari sudut ini, semuanya terlihat patuh.”',
      'Tangga tampak tersambung → kamera berputar: ada celah → GAP Assessment menunjukkan celahnya → CTA',
      'GAP Assessment', 'gap-hasil', '15 dtk', 'Baru'),
    R('GB43', 'Bayangan berbeda',
      'Benda kecil dengan bayangan besar yang bentuknya lain.',
      'Objek + bayangan path terpisah; bayangan membesar dan berubah.',
      'Bisa', 2, 8, 8,
      'Bayangannya', 'Anomali',
      '“Fiturnya kecil. Bayangannya tidak.”',
      'Tombol “rekomendasi untukmu” → bayangan besar bertuliskan risiko → dinilai lewat DPIA → CTA',
      'DPIA', 'dpia-risiko', '15 dtk', 'M05'),
]
