# Keluarga 3–7: CRAFT, LAYAR & UI, SINEMATIK & RETRO, PARODI FORMAT, STRUKTUR EDIT.
from gaya_base import R

ROWS = [
    # ====================================================================== 3 · CRAFT (buatan tangan)
    R('CR01', 'Stop motion papan gabus',
      'Kertas, sticky note, dan stempel di papan gabus; gerak patah-patah.',
      'Waktu dikuantisasi 12 fps; getar kecil per langkah; tekstur dari hash.',
      'Sudah (T03)', 4, 9, 7,
      'Rating Kebiasaan Data di Kantor', 'Relate', '“Rating kebiasaan data di kantor. Jujur, ya.”',
      'Nilai 1/10 … 0/10 → papan disapu → kartu Nexus 10/10 → CTA',
      'RoPA, DSR, Insiden', '—', '51,4 dtk', 'T03 (sudah dirender)'),
    R('CR02', 'Paper-craft (guntingan kertas berlapis)',
      'Bentuk dari kertas warna berlapis dengan bayangan lembut, coretan krayon.',
      'Lapisan div dengan bayangan; goyang kecil; tekstur kertas.',
      'Sudah (N06)', 3, 8, 8,
      'Data Anak & Inklusif', 'Anomali', 'Pengguna termuda juga butuh izin walinya.',
      'Anak daftar sendiri → izin wali → Children Pro & Inclusive Privacy → CTA',
      'Children Pro, Inclusive Privacy', 'children-pro, inclusive-privacy', '45,6 dtk', 'N06 (sudah dirender)'),
    R('CR03', 'Kolase / mixed media',
      'Potongan layar, kertas sobek, selotip, dan coretan spidol ditumpuk.',
      'Elemen dengan tepi sobek (clip-path), selotip transparan, rotasi acak dari hash.',
      'Bisa', 3, 8, 7,
      '2016 vs 2026', 'Relate', '“2016: data pelanggan disimpan di flashdisk.”',
      'Kolase 2016 (flashdisk, kertas tempel) → disobek → kolase 2026: register, log audit, tenggat otomatis → CTA',
      'Platform', 'dashboard, ropa-list-baru', '20 dtk', 'A17'),
    R('CR04', 'Whiteboard (spidol papan putih)',
      'Tangan tak terlihat menggambar diagram dengan spidol sambil menjelaskan.',
      'Goresan digambar (stroke) dengan ujung spidol; penghapus menyapu.',
      'Bisa', 2, 6, 8,
      'Jelaskan dalam 20 Detik', 'Relate', '“Jelaskan UU PDP ke direksi dalam 20 detik. Mulai.”',
      'Timer → tiga kotak: catat, nilai, tanggapi → panah ke modul → CTA',
      'Platform', '—', '20 dtk', 'Baru'),
    R('CR05', 'Papan tulis kapur',
      'Tulisan dan gambar kapur di papan hijau tua, ada debu kapur.',
      'Font kapur + tekstur bintik; hapusan meninggalkan bekas.',
      'Bisa', 2, 7, 8,
      'Kelas Pertama', 'Reverse psychology', '“Jangan ambil kelas ini… kalau kamu sudah hafal 76 pasal UU PDP.”',
      'Judul kelas ditulis kapur → daftar materi → kartu kursus DPO Academy asli → CTA',
      'DPO Academy', 'dpo-academy', '15 dtk', 'M22'),
    R('CR06', 'Bullet journal / planner',
      'Halaman agenda bertitik dengan tulisan tangan, stiker, dan kotak centang.',
      'Kisi titik; tulisan tangan write-on; centang digambar; selotip hias.',
      'Bisa', 2, 7, 7,
      'Agenda DPO Minggu Ini', 'Relate', '“Agenda DPO minggu ini. Ditulis Senin, berantakan Selasa.”',
      'Agenda rapi → tugas mendadak menimpa → antrean kerja Nexus mengurutkan → CTA',
      'Dukungan PPDP (antrean kerja)', 'dashboard', '15 dtk', 'A21 (varian)'),
    R('CR07', 'Sketsa pensil',
      'Garis pensil tipis, arsiran, dan garis bantu yang belum dihapus.',
      'Stroke abu-abu dengan filter kasar; arsir dari garis sejajar.',
      'Bisa', 3, 7, 8,
      'Sketsa Pertama', 'Anomali', '“Semua yang rapi dimulai dari sketsa kasar.”',
      'Sketsa alur data digambar → ditebalkan jadi langkah wizard RoPA → CTA',
      'RoPA (wizard)', 'ropa-baru', '15 dtk', 'Baru'),
    R('CR08', 'Cat air / tinta menyebar',
      'Warna merembes di kertas basah, tepi tidak rata.',
      'Bercak radial + feTurbulence displacement; melebar per waktu.',
      'Berat', 4, 8, 7,
      'Merembes', 'Anomali', '“Data merembes seperti tinta di kertas basah.”',
      'Satu tetes tinta = satu salinan data → merembes ke mana-mana → Data Discovery memetakan → CTA',
      'Data Discovery', '—', '15 dtk', 'Baru'),
    R('CR09', 'Diorama kertas berlapis',
      'Lapisan kertas bertingkat dengan cahaya dari belakang (kotak lampu).',
      'Lapisan paralaks dengan bayangan dalam; cahaya hangat berdenyut pelan.',
      'Bisa', 3, 8, 8,
      'Di Balik Formulir', 'Anomali', '“Di balik satu formulir, ada enam lapis.”',
      'Lapisan terbuka satu-satu: formulir → sistem → pihak ketiga → arsip → RoPA mencatat semuanya → CTA',
      'RoPA', '—', '15 dtk', 'Baru', 'Jumlah lapis = ilustrasi.'),
    R('CR10', 'Dinding sticky note',
      'Dinding penuh kertas tempel warna-warni, membentuk gambar dari jauh.',
      'Grid kertas tempel; tiap kertas jatuh menempel; dari jauh membentuk ikon.',
      'Bisa', 3, 8, 7,
      'Dinding Ini Dulu Putih', 'Relate', '“Dinding ini dulu putih.”',
      'Kertas tempel tugas memenuhi dinding → kamera mundur: membentuk tanda tanya → antrean kerja → CTA',
      'Dukungan PPDP', '—', '15 dtk', 'Baru'),
    R('CR11', 'Papan detektif (benang merah)',
      'Foto, catatan, dan pin dihubungkan benang merah di papan.',
      'Pin + benang path digambar antarpin; kartu catatan miring.',
      'Bisa', 3, 9, 8,
      'Tarik Benangnya', 'Anomali', '“Siapa membuka data apa, dan kapan? Tarik benangnya.”',
      'Kartu peristiwa dipasang → benang merah menghubungkan → log audit & linimasa insiden → CTA',
      'Log audit, Insiden (linimasa)', 'breach-aksi', '20 dtk', 'A42'),
    R('CR12', 'Scrapbook / album',
      'Halaman album dengan kartu bergambar, selotip sudut, dan keterangan tulisan tangan.',
      'Kartu berbingkai putih; selotip sudut; keterangan write-on.',
      'Bisa', 2, 6, 7,
      'Album Perjalanan Data', 'Relate', '“Album perjalanan satu data pelanggan.”',
      'Halaman 1: mendaftar → 2: dicatat → 3: dinilai → 4: dihapus atas permintaan → CTA',
      'Platform', 'consent-detail, ropa-tersimpan, dsr-detail', '20 dtk', 'Flow unggulan (versi 30 dtk)'),
    R('CR13', 'Sulam / kristik',
      'Gambar dan huruf dari tusuk silang benang di kain.',
      'Grid tusuk X muncul berurutan; tekstur kain.',
      'Bisa', 3, 8, 7,
      'Satu Tusuk Salah', 'Anomali', '“Satu tusuk salah, polanya ikut salah.”',
      'Pola disulam → satu tusuk keliru merusak gambar → dibongkar → alur Maker–Reviewer–Approver → CTA',
      'RoPA (alur persetujuan)', '—', '15 dtk', 'Baru'),
    R('CR14', 'Wayang / bayangan di kelir',
      'Siluet hitam di layar kain bercahaya lampu yang bergoyang.',
      'Siluet path; cahaya radial berkedip halus; gerak sendi sederhana.',
      'Bisa', 4, 9, 7,
      'Dalang Data', 'Anomali', '“Di balik layar selalu ada dalang. Di balik data, harus ada penanggung jawabnya.”',
      'Bayangan tanpa dalang kacau → dalang muncul: pembagian peran (RACI) → CTA',
      'Insiden (matriks RACI), Dukungan PPDP', '—', '20 dtk', 'Baru (lokal)', 'Hormati budaya; jangan pakai tokoh wayang tertentu sebagai olok-olok.'),
    R('CR15', 'Batik canting (malam)',
      'Garis malam digores canting, lalu warna mengisi.',
      'Garis cokelat digambar; warna mengisi area (clip) setelah garis selesai.',
      'Bisa', 3, 8, 8,
      'Digambar Dulu, Baru Diwarnai', 'Logika dipatahkan', '“Batik digambar dulu, baru diwarnai. Proyek data juga: dinilai dulu, baru meluncur.”',
      'Pola digambar → warna masuk → DPIA sebelum peluncuran → CTA',
      'DPIA', 'dpia-risiko', '15 dtk', 'M05 (lokal)'),
    R('CR16', 'Pasir (sand art)',
      'Gambar dari pasir di meja cahaya; sekali sapu, hilang.',
      'Butir canvas; sapuan menghapus area; cahaya dari bawah.',
      'Berat', 4, 8, 7,
      'Sekali Sapu', 'Anomali', '“Catatan di atas pasir hilang sekali sapu.”',
      'Catatan pasir tersapu → catatan yang tidak bisa diam-diam diubah: log audit berantai hash → CTA',
      'Log audit (rantai hash opsional)', '—', '15 dtk', 'Baru'),
    R('CR17', 'Zine fotokopi',
      'Halaman hitam-putih kontras tinggi, tempelan miring, bintik mesin fotokopi.',
      'Filter kontras + bintik; potongan teks ditempel; garis potong.',
      'Bisa', 2, 7, 5,
      'Zine: Cara Bertahan Saat Audit', 'Reverse psychology', '“Jangan fotokopi halaman ini.”',
      'Sampul zine → 3 halaman tips → halaman terakhir: Start Pre Check → CTA',
      'GAP Assessment', '—', '15 dtk', 'Baru', 'Untuk organik/komunitas.'),
    R('CR18', 'Krayon anak',
      'Gambar krayon polos ala anak-anak di kertas gambar.',
      'Goresan tebal bertekstur; warna keluar garis; write-on.',
      'Bisa', 2, 7, 8,
      'Gambar Anak', 'Anomali', '“Yang mendaftar di aplikasimu mungkin masih menggambar seperti ini.”',
      'Gambar krayon “aku & HP” → formulir daftar → izin wali → Children Pro → CTA',
      'Children Pro', 'children-pro', '15 dtk', 'A31', 'Tanpa foto/gambar anak sungguhan.'),
    R('CR19', 'Flipbook',
      'Buku kecil yang halamannya dibalik cepat sehingga gambar bergerak.',
      'Halaman rotateY cepat; gambar tiap halaman bergeser sedikit.',
      'Bisa', 3, 8, 7,
      'Balik Halamannya', 'Anomali', '“Balik halamannya cepat-cepat.”',
      'Flipbook: permohonan masuk → diproses → disetujui → selesai → DSR terlacak → CTA',
      'DSR', 'dsr-detail', '15 dtk', 'Baru'),
    R('CR20', 'Buku pop-up',
      'Buku dibuka, bangunan kertas berdiri dari lipatan.',
      'Halaman CSS 3D; elemen berdiri lewat rotateX dari engsel.',
      'Berat', 5, 10, 8,
      'Buku Pop-up Kepatuhan', 'Anomali', '“Buka halamannya. Kantormu berdiri.”',
      'Halaman 1: kantor & data → 2: risiko berdiri → 3: modul Nexus berdiri rapi → CTA',
      'Platform', '—', '25 dtk', 'Baru'),
    R('CR21', 'Amplop & segel',
      'Surat dilipat, masuk amplop, disegel, dan dikirim.',
      'Lipatan panel 3D; segel cap; amplop bergeser keluar.',
      'Bisa', 3, 7, 8,
      'Surat yang Harus Sampai', 'Relate', '“Surat ini harus sampai paling lambat 3×24 jam.”',
      'Templat pemberitahuan terisi → dilipat → disegel → penghitung mundur berhenti tepat waktu → CTA',
      'Insiden (templat pemberitahuan tertulis)', 'breach-aksi', '15 dtk', 'Baru'),
    R('CR22', 'Stempel persetujuan',
      'Cap karet dijatuhkan berulang di dokumen: DISETUJUI.',
      'Cap masuk dengan skala + guncangan; tinta tidak rata (mask bintik).',
      'Bisa', 2, 7, 8,
      'Disetujui oleh Siapa?', 'Anomali', '“Disetujui. Disetujui. Disetujui. Oleh siapa?”',
      'Cap tanpa nama → riwayat perubahan & persetujuan tampil: siapa, kapan → CTA',
      'RoPA (riwayat & alur persetujuan)', '—', '10 dtk', 'Baru'),
    R('CR23', 'Lemari arsip / kartu indeks',
      'Laci arsip ditarik; kartu indeks dibolak-balik.',
      'Laci translateZ; kartu flip; label laci.',
      'Bisa', 3, 7, 8,
      'Laci Nomor Berapa?', 'Relate', '“Lemari ini punya seratus laci. RoPA-nya di laci mana?”',
      'Laci dibuka-tutup panik → kotak cari → register RoPA dengan kode otomatis → CTA',
      'RoPA', 'ropa-list-baru', '15 dtk', 'Baru', 'Jumlah laci = ilustrasi.'),
    R('CR24', 'Balok susun (mainan bangun)',
      'Balok warna-warni disusun dari bawah membentuk bangunan.',
      'Balok kotak polos jatuh & mengunci; susunan dari data.',
      'Bisa', 2, 7, 7,
      'Bangun dari Bawah', 'Logika dipatahkan', '“Kepatuhan tidak dibangun dari atap.”',
      'Atap melayang jatuh → mulai dari fondasi: GAP → RoPA → DPIA → atap terpasang → CTA',
      'Program siap PP 33', '—', '15 dtk', 'Baru', 'Balok polos; tanpa bentuk/merek mainan tertentu.'),
    R('CR25', 'Claymation (tanah liat)',
      'Tokoh dan benda dari tanah liat bergerak frame demi frame.',
      'Butuh model 3D/foto tanah liat sungguhan.',
      'Tidak cocok', 5, 9, 7,
      '—', '—', '—', '—', '—', '—', '—', '—', 'Butuh pemodelan atau pemotretan nyata.'),
    R('CR26', 'Animasi karakter frame-by-frame',
      'Tokoh kartun digambar tangan tiap frame.',
      'Butuh ilustrator/animator; di luar kemampuan mesin berbasis kode.',
      'Tidak cocok', 5, 9, 8,
      '—', '—', '—', '—', '—', '—', '—', '—', 'Alternatif: tokoh bentuk sederhana (GB03) atau emoji.'),

    # ====================================================================== 4 · LAYAR & UI
    R('UI01', 'UI walkthrough berkamera',
      'Screenshot asli dalam bingkai browser melayang; kamera menyorot bagian penting.',
      'Tipe nx_shot (lib/seri-modul.js): bingkai 3D, kamera keyframe, sorotan berlabel.',
      'Sudah (M01, M02)', 3, 7, 10,
      'Seri Nexus Explained', 'Logika dipatahkan', '“Laporan kepatuhan terbaik, bukan yang paling tebal.”',
      'Hook → 3–4 layar asli disorot → CTA',
      'Semua modul', 'semua aset', '45–48 dtk', 'M01, M02 (sudah dirender) · M03–M22 menyusul'),
    R('UI02', 'Chat story',
      'Cerita lewat gelembung percakapan yang muncul satu per satu.',
      'Gelembung masuk dengan indikator mengetik; waktu dari VO.',
      'Sudah (N05)', 2, 7, 8,
      'Tolong Hapus Data Saya', 'Relate', '“Tolong hapus semua data saya.”',
      'Chat pelanggan → panik → alur DSR → CTA',
      'DSR', 'dsr-form, dsr-detail', '43 dtk', 'N05 (sudah dirender)'),
    R('UI03', 'Story slides / rekap tahunan',
      'Slide bergradasi cerah dengan angka raksasa dan bilah progres di atas.',
      'Latar gradasi kanvas; transisi geser; konfeti deterministik.',
      'Sudah (A22)', 3, 8, 7,
      'Rekap Tahunan DPO 2026', 'Relate', '“Rekap tahunan DPO 2026 kamu sudah siap.”',
      'Kalimat favorit → menit rapat → file favorit → kepribadian → 2027 → ajakan tag',
      'Brand + PP 33', 'dashboard', '46 dtk', 'A22 (sudah dirender)', 'Angka = ilustrasi.'),
    R('UI04', 'Screenlife (cerita di layar komputer)',
      'Seluruh cerita terjadi di desktop: jendela, kursor, notifikasi.',
      'Desktop tiruan buatan sendiri; jendela div; kursor bergerak dengan lintasan halus.',
      'Sudah (UI04)', 3, 8, 8,
      'Pukul 16.58', 'Relate', '“Nobody: … Marketing jam 5 sore: ‘blast promo ke semua nomor di database ya!’”',
      'Jam 16.58 → chat masuk → kursor ragu di tombol Kirim → cek persetujuan per kanal → CTA',
      'Consent & Cookie', 'consent-detail', '20 dtk', 'A09', 'Desktop & aplikasi fiktif; tanpa merek nyata.'),
    R('UI05', 'Retro OS (dialog error beruntun)',
      'Jendela abu-abu jadul; dialog error bermunculan berjejer.',
      'Jendela bergaya lama buatan sendiri; dialog beranak-pinak dengan offset.',
      'Sudah (UI05)', 3, 9, 7,
      'FAAAH', 'Relate', '“POV: auditor minta RoPA. Kamu buka RoPA_final_revisi3_FIX.xlsx.”',
      'File dibuka → “dikunci oleh pengguna lain” → not responding → dialog beruntun → register RoPA rapi → CTA',
      'RoPA', 'ropa-list-baru', '20 dtk', 'A01', 'Tampilan OS buatan sendiri; suara “FAAAH” direkam tim/TTS.'),
    R('UI06', 'Lock screen (notifikasi)',
      'Layar kunci ponsel; notifikasi menumpuk sepanjang hari.',
      'Jam besar berganti; kartu notifikasi masuk dari atas.',
      'Sudah (UI06)', 2, 7, 8,
      'Sehari dalam Notifikasi', 'Relate', '“07.00: ‘Pagi, bisa minta RoPA terbaru?’”',
      'Notifikasi 07.00–23.00 menumpuk → 03.00: dugaan insiden → satu notifikasi rapi: antrean kerja → CTA',
      'Dukungan PPDP, Insiden', '—', '20 dtk', 'A21 (varian ringan)'),
    R('UI07', 'Kotak pencarian (saran otomatis)',
      'Kotak pencarian; ketikan dilengkapi saran yang makin jujur.',
      'Ketik per karakter; daftar saran berganti tiap huruf.',
      'Bisa', 1, 8, 8,
      'Saran Pencarian', 'Relate', '“cara menjawab auditor kalau… ”',
      'Saran: “…RoPA belum ada”, “…buktinya di laptop orang resign” → tanya Priva → CTA',
      'Priva (asisten AI), GAP', 'ai-agent-home', '15 dtk', 'Baru', 'Mesin pencari fiktif; tanpa logo.'),
    R('UI08', 'Spreadsheet hidup',
      'Sel tabel menjadi panggung: sel menyala, bergeser, dan berbaris.',
      'Grid sel; sel berwarna berpindah; rumus muncul di bilah atas.',
      'Bisa', 2, 8, 8,
      'Tab ke-14', 'Relate', '“Spreadsheet ini punya 14 tab. Yang benar tab mana?”',
      'Tab berganti cepat → #REF! menyebar → sel-sel berbaris jadi register → CTA',
      'RoPA', 'ropa-list-baru', '15 dtk', 'M04', 'Tanpa antarmuka/logo aplikasi spreadsheet bermerek.'),
    R('UI09', 'Mockup perangkat 3D',
      'Laptop atau ponsel melayang berputar menampilkan layar asli.',
      'Bingkai perangkat CSS 3D; screenshot di layar; pantulan halus.',
      'Bisa', 3, 7, 9,
      'Di Laptop Direksi', 'Logika dipatahkan', '“Yang dibuka direksi bukan laporan 482 halaman. Ini.”',
      'Laptop berputar terbuka → dasbor asli → ponsel: postur privasi → CTA',
      'Dasbor kepatuhan', 'dashboard, postur-privasi', '15 dtk', 'P32'),
    R('UI10', 'Kotak masuk email',
      'Daftar email; satu subjek membuat semua berhenti.',
      'Baris email masuk dari atas; satu baris disorot & membesar.',
      'Bisa', 2, 7, 8,
      'Senin, 08.02', 'Relate', '“Email paling ditakuti customer service: ‘Tolong hapus semua data saya.’”',
      'Email masuk → diteruskan ke 4 orang → tenggat 72 jam berjalan → formulir & alur DSR → CTA',
      'DSR', 'dsr-form, dsr-detail', '15 dtk', 'M07 / P23', 'Aplikasi email fiktif.'),
    R('UI11', '47 tab browser',
      'Deretan tab browser yang terus bertambah sampai judulnya tak terbaca.',
      'Tab div mengecil saat bertambah; satu tab berkedip.',
      'Bisa', 2, 7, 7,
      '47 Tab', 'Relate', '“DPO dan 47 tab yang tidak boleh ditutup.”',
      'Tab bertambah → semua ditutup jadi satu tab: Nexus → CTA',
      'Platform', 'dashboard', '10 dtk', 'A13 (potongan)'),
    R('UI12', 'Pohon folder',
      'Folder di dalam folder di dalam folder; nama makin putus asa.',
      'Pohon folder membuka bertingkat; kursor mengejar.',
      'Sudah (UI12)', 2, 7, 8,
      'Baru (2)', 'Relate', '“Folder ‘Baru’ di dalam ‘Baru (2)’ di dalam ‘FIX banget’.”',
      'Folder dibuka bertingkat → dokumen lama ditemukan → diimpor dengan AI → CTA',
      'Document Import (AI), RoPA', '—', '15 dtk', 'M18'),
    R('UI13', 'Papan kanban',
      'Kartu tugas berpindah kolom: Menunggu, Dikerjakan, Selesai.',
      'Kartu drag dengan lintasan; penghitung per kolom.',
      'Bisa', 2, 6, 9,
      'Tiga Minggu di Kolom Menunggu', 'Relate', '“Kartu ini sudah tiga minggu di kolom ‘Menunggu’.”',
      'Kartu berdebu → antrean pekerjaan yang menunggu tindakan → bergerak ke Selesai → CTA',
      'Dukungan PPDP (antrean kerja)', 'dashboard', '15 dtk', 'Baru'),
    R('UI14', 'Wizard formulir',
      'Formulir bertahap; bilah langkah terisi, pilihan menyala.',
      'Langkah aktif berpindah; centang digambar; label risiko berubah.',
      'Bisa', 2, 6, 9,
      'Langkah 4 dari 7', 'Anomali', '“Satu centang di langkah ini mengubah segalanya.”',
      'Wizard RoPA → centang data spesifik → risiko TINGGI otomatis → draf DPIA → CTA',
      'RoPA → DPIA', 'ropa-data-spesifik', '15 dtk', 'A11 / A45'),
    R('UI15', 'Parade banner cookie',
      'Banner cookie bertumpuk menutupi layar; tombol “Terima semua” di mana-mana.',
      'Banner masuk dari bawah berlapis; tombol berkedip.',
      'Bisa', 2, 8, 8,
      'Terima Semua?', 'Relate', '“Kamu menutup enam banner cookie hari ini. Ingat isinya?”',
      'Banner menumpuk → satu banner jelas + pusat preferensi → log persetujuan → CTA',
      'Consent & Cookie', 'consent-detail', '15 dtk', 'Baru', 'Banner fiktif; tanpa situs nyata.'),
    R('UI16', 'Kuis pilih kotak',
      'Kisi 3×3 gambar; penonton diminta memilih kotak tertentu.',
      'Grid kartu; kotak terpilih diberi centang; penghitung.',
      'Bisa', 2, 9, 8,
      'Pilih Semua Kotak Berisi Data Pribadi', 'Relate', '“Pilih semua kotak yang berisi data pribadi.”',
      'Kotak: nama, plat nomor, NIK, foto wajah, menu makan siang… → jawaban mengejutkan → pemindaian otomatis → CTA',
      'Data Discovery, RoPA', '—', '15 dtk', 'Baru', 'Desain sendiri; jangan meniru tampilan layanan captcha.'),
    R('UI17', 'Asisten AI (orb / gelombang)',
      'Orb bercahaya berdenyut saat menjawab; kutipan sumber muncul.',
      'Gradasi radial berdenyut; teks jawaban diketik; kartu sumber.',
      'Bisa', 2, 7, 9,
      'Tanya Priva', 'Logika dipatahkan', '“AI paling berguna untuk DPO bukan yang paling kreatif.”',
      'Pertanyaan diketik → jawaban dengan rujukan knowledge base → CTA',
      'Priva (asisten AI)', 'ai-agent-home, ai-agent-chat', '15 dtk', 'M19'),
    R('UI18', 'Lacak paket (resi)',
      'Linimasa pelacakan seperti resi kurir: titik status turun satu per satu.',
      'Linimasa vertikal; titik aktif berdenyut; cap waktu.',
      'Sudah (UI18)', 2, 9, 9,
      'Lacak Permohonan', 'Relate', '“Paket bisa dilacak sampai depan pintu. Permohonan hapus data?”',
      'Status: diterima → diverifikasi → ditelaah → disetujui → selesai (tenggat 72 jam terlihat) → CTA',
      'DSR', 'dsr-detail', '15 dtk', 'Baru', 'Tampilan pelacakan fiktif; tanpa merek kurir.'),
    R('UI19', 'Keranjang belanja',
      'Halaman keranjang; barang aneh ikut masuk.',
      'Daftar keranjang; baris baru menyelip; total berubah.',
      'Sudah (UI19)', 2, 7, 7,
      'Keranjang 12.12', 'Anomali', '“Diskon 90%. Data pelanggan ikut ‘diskon’?”',
      'Keranjang promo → baris “data pelanggan” menyelip → latihan insiden sebelum musim promo → CTA',
      'Simulasi & Fire Drill', 'fire-drill-header', '15 dtk', 'A25', 'Toko fiktif.'),
    R('UI20', 'Layar memuat',
      'Bilah progres yang macet di angka tertentu.',
      'Bilah scaleX dengan jeda; teks status berganti.',
      'Bisa', 1, 6, 8,
      'Memuat Kepatuhan…', 'Relate', '“Memuat kepatuhan… 38%.”',
      'Progres macet → daftar yang belum selesai → GAP Assessment memberi skor & rekomendasi → CTA',
      'GAP Assessment', 'gap-rekomendasi', '10 dtk', 'Baru', 'Angka = ilustrasi.'),
    R('UI21', 'Sakelar preferensi',
      'Deretan sakelar hidup/mati; satu dimatikan, yang lain ikut.',
      'Sakelar bergeser; garis penghubung menyala.',
      'Bisa', 2, 7, 9,
      'Matikan Satu', 'Anomali', '“Pelanggan mematikan satu sakelar. Berapa sistem yang ikut berubah?”',
      'Sakelar “promosi” dimatikan → sinyal ke semua kanal → penarikan dihormati di seluruh kanal → CTA',
      'Consent (pusat preferensi)', 'consent-detail', '15 dtk', 'Flow unggulan (Bab 1)'),
    R('UI22', 'Rapat video',
      'Kisi peserta rapat online; satu kotak masih mute.',
      'Grid kotak peserta (avatar bentuk); ikon mute; gelembung chat.',
      'Bisa', 2, 7, 7,
      'Kamu Masih Mute', 'Relate', '“Latihan kebocoran data pertama kantor ini. Moderatornya masih mute.”',
      'Rapat kacau → skenario tabletop siap pakai → penilaian rubrik → CTA',
      'Simulasi & Fire Drill', 'fire-drill-header', '15 dtk', 'M12', 'Aplikasi rapat fiktif; avatar tanpa wajah nyata.'),
    R('UI23', 'Pencapaian terbuka (game)',
      'Notifikasi pencapaian muncul di pojok layar dengan bunyi.',
      'Kartu toast masuk; ikon piala; bilah XP.',
      'Bisa', 1, 7, 7,
      'Pencapaian Terbuka', 'Relate', '“Pencapaian terbuka: membaca UU PDP sampai Pasal 5.”',
      'Pencapaian konyol → pencapaian sungguhan: modul DPO Academy selesai → CTA',
      'DPO Academy', 'dpo-academy', '10 dtk', 'A36'),
    R('UI24', 'Urutan boot',
      'Teks putih di layar hitam memeriksa komponen satu per satu.',
      'Baris muncul berurutan; status OK/GAGAL berwarna.',
      'Sudah (UI24)', 1, 8, 8,
      'Memeriksa…', 'Anomali', '“Memeriksa RoPA… OK. Memeriksa bukti persetujuan… TIDAK DITEMUKAN.”',
      'Pemeriksaan berjalan → berhenti di yang gagal → rekomendasi perbaikan → CTA',
      'GAP Assessment', 'gap-rekomendasi', '15 dtk', 'Baru'),
    R('UI25', 'Halaman galat 404',
      'Halaman “tidak ditemukan” dengan angka besar.',
      'Angka raksasa; teks kecil; tombol kembali.',
      'Bisa', 1, 7, 8,
      '404', 'Anomali', '“404: bukti tidak ditemukan.”',
      '404 → “auditor sedang menunggu” → analisis dokumen bukti per pertanyaan → CTA',
      'GAP Assessment (analisis bukti)', 'gap-rekomendasi', '10 dtk', 'Baru'),
    R('UI26', 'Pemindai (viewfinder)',
      'Bingkai bidik kamera memindai ruangan dan memberi label.',
      'Sudut bidik; kotak deteksi muncul; label mengetik.',
      'Bisa', 3, 8, 8,
      'Pindai Ruangan Ini', 'Anomali', '“Pindai meja kerjamu. Berapa data pribadi yang terlihat?”',
      'Kotak deteksi: kartu nama, layar, kertas tempel → pemindaian sumber data → CTA',
      'Data Discovery', '—', '15 dtk', 'Baru', 'Ruangan ilustrasi (gambar), bukan foto.'),
    R('UI27', 'Bento grid',
      'Kotak-kotak informasi berbagai ukuran tersusun rapat.',
      'Grid CSS; kotak masuk bertingkat; isi dari screenshot.',
      'Bisa', 2, 7, 9,
      'Bento Kepatuhan', 'Logika dipatahkan', '“Satu layar. Semua yang ditanya direksi.”',
      'Kotak skor, tenggat, insiden, risiko masuk satu-satu → CTA',
      'Dasbor kepatuhan', 'dashboard, dashboard-postur, dashboard-risiko, dashboard-sla', '15 dtk', 'P32'),
    R('UI28', 'Nomor antrean loket',
      'Layar antrean: nomor dipanggil, loket berkedip.',
      'Angka besar berganti; suara panggilan (TTS); papan loket.',
      'Bisa', 2, 8, 8,
      'Nomor Antrean A-072', 'Relate', '“Nomor antrean A-072, silakan ke loket persetujuan.”',
      'Loket kertas → persetujuan di loket tercatat sama seperti web & aplikasi → CTA',
      'Consent (titik pengumpulan: web, aplikasi, loket)', 'consent-detail', '15 dtk', 'Baru (lokal)'),

    # ====================================================================== 5 · SINEMATIK & RETRO
    R('SN01', 'Cyber-noir CCTV',
      'Tampilan kamera pengawas gelap dengan garis scan dan cap waktu.',
      'Overlay scanline, vignette, teks cap waktu.',
      'Sudah (N03)', 3, 8, 8,
      'Insiden 3×24 Jam', 'Anomali', 'Jam 03.00: dugaan kebocoran data.',
      'Notifikasi → 5 fase → templat → CTA',
      'Manajemen Insiden', 'breach-detail, breach-fase, breach-aksi', '38,5 dtk', 'N03 (sudah dirender)'),
    R('SN02', 'Neon sign',
      'Tulisan tabung neon menyala di dinding malam; ada yang berkedip.',
      'text-shadow berlapis; kedip dari hash; pantulan di lantai.',
      'Sudah (SN02)', 2, 9, 7,
      'Cooked vs Chill', 'Relate', '“Jam 3 pagi, insiden. DPO A vs DPO B.”',
      'Layar terbagi: neon merah COOKED berkedip panik · neon biru CHILL tenang → bedanya: alur siap → CTA',
      'Manajemen Insiden', 'breach-detail', '20 dtk', 'A44'),
    R('SN03', 'VHS / camcorder',
      'Rekaman kaset: garis tracking, warna bergeser, tulisan REC.',
      'Offset kanal warna; pita noise bergerak; cap tanggal.',
      'Bisa', 2, 8, 7,
      'Rekaman 2016', 'Relate', '“Rekaman kantor, 2016: ‘datanya simpan di flashdisk saja’.”',
      'Rekaman VHS 2016 → rewind → 2026: register & log audit → CTA',
      'Platform', 'dashboard', '15 dtk', 'A17 / P13'),
    R('SN04', 'Synthwave (grid 80-an)',
      'Grid ungu menuju cakrawala, matahari bergaris, pegunungan garis.',
      'Grid perspektif bergerak; gradasi matahari; garis neon.',
      'Bisa', 2, 8, 6,
      'Menuju 2027', 'Anomali', '“Jalan ini lurus menuju 16 Januari 2027.”',
      'Melaju di grid → gerbang PP 33 mendekat → daftar siap → CTA',
      'Program siap PP 33', '—', '15 dtk', 'A23'),
    R('SN05', 'TV tabung ganti saluran',
      'Layar TV lama; saluran berganti dengan semut dan bunyi klik.',
      'Noise kanvas; garis lipat; isi tiap saluran kartu teks.',
      'Bisa', 2, 8, 7,
      'Ganti Saluran', 'Anomali', '“Ganti saluran pun percuma. Beritanya sama.”',
      'Saluran 1–3: judul kebocoran data (fiktif) → saluran 4: latihan insiden → CTA',
      'Simulasi & Fire Drill, Insiden', 'fire-drill-header', '15 dtk', 'Baru', 'Judul berita fiktif; tanpa logo stasiun TV.'),
    R('SN06', 'Film noir detektif',
      'Hitam-putih, bayangan kerai jendela, narasi detektif.',
      'Garis bayangan bergerak; grain; teks narasi serif.',
      'Bisa', 3, 8, 7,
      'Kasus Kolom ke-17', 'Anomali', '“Malam itu hujan. Dan ada NIK di kolom yang tidak seharusnya.”',
      'Narasi detektif → petunjuk → pemindaian kolom menemukan → dikaitkan ke RoPA → CTA',
      'Data Discovery', '—', '20 dtk', 'M15 (varian)'),
    R('SN07', 'Title sequence potongan kertas',
      'Bentuk geometris tajam dan huruf miring ala pembuka film lama.',
      'Bentuk datar bergerak kaku; palet 3 warna; tipografi tebal.',
      'Sudah (SN07)', 3, 8, 8,
      'Pembuka', 'Anomali', '“Dipersembahkan oleh: tenggat yang tidak menunggu.”',
      'Kredit pembuka: “menampilkan RoPA… DPIA… DSR…” → judul: Privasimu Nexus → CTA',
      'Platform', '—', '15 dtk', 'Baru (pembuka kampanye)', 'Gaya umum era itu; jangan meniru judul film tertentu.'),
    R('SN08', 'Film bisu (kartu teks)',
      'Hitam-putih berkedip; dialog tampil di kartu teks berornamen; iringan piano.',
      'Bingkai ornamen; flicker dari hash; goresan film; musik piano synth.',
      'Sudah (SN08)', 2, 9, 7,
      'Auditor Datang', 'Relate', '“Pada suatu pagi yang tenang… auditor datang.”',
      'Kartu: “RoPA-nya mana?” → panik gaya film bisu → kartu: “Untung sudah tercatat.” → CTA',
      'GAP, RoPA', 'ropa-list-baru', '20 dtk', 'A16 (varian)'),
    R('SN09', 'Warta berita arsip',
      'Siaran berita lama hitam-putih dengan narator tegas.',
      'Bingkai 4:3; grain; judul huruf besar; garis waktu.',
      'Bisa', 2, 7, 7,
      'Warta Kepatuhan', 'Anomali', '“Warta hari ini: aturan pelaksana telah terbit.”',
      'Narator: PP 33 berlaku 16 Januari 2027 → apa yang harus disiapkan → CTA',
      'Program siap PP 33', '—', '15 dtk', 'N01 (varian)', 'Tanpa logo/lembaga siaran nyata.'),
    R('SN10', 'Panggung & lampu sorot',
      'Panggung gelap; satu lampu sorot menyapu lalu berhenti.',
      'Kerucut cahaya (gradient) bergerak; debu melayang.',
      'Bisa', 2, 7, 8,
      'Di Bawah Lampu Sorot', 'Anomali', '“Lampu sorot ini akan berhenti di satu divisi.”',
      'Lampu menyapu Legal, IT, Marketing → berhenti: “yang belum tercatat” → GAP → CTA',
      'GAP Assessment', '—', '15 dtk', 'Baru'),
    R('SN11', 'Partikel / jaringan titik-garis',
      'Titik melayang terhubung garis tipis saat berdekatan.',
      'Canvas: posisi titik dari rumus; garis bila jarak < ambang.',
      'Bisa', 2, 6, 8,
      'Terhubung', 'Anomali', '“Tiap titik ini satu catatan.”',
      'Titik tersebar → terhubung → membentuk logo → CTA',
      'Platform', '—', '10 dtk', 'Baru (bumper)'),
    R('SN12', 'Bokeh malam',
      'Lampu kota buram di latar; teks tajam di depan.',
      'Lingkaran blur bergerak pelan; fokus bergeser.',
      'Bisa', 2, 6, 8,
      'Malam Sebelum Audit', 'Relate', '“Malam sebelum audit. Kantor sudah gelap, satu layar masih menyala.”',
      'Suasana malam → layar menyala: dasbor → “besok cukup buka ini” → CTA',
      'Dasbor kepatuhan', 'dashboard', '15 dtk', 'Baru'),
    R('SN13', 'Peluncuran roket',
      'Hitung mundur peluncuran; roket garis sederhana lepas landas.',
      'Hitung mundur besar; asap partikel; guncangan kamera.',
      'Sudah (SN13)', 3, 8, 8,
      'Nilai Dulu, Baru Meluncur', 'Anomali', '“Proyek paling berisiko di kantormu biasanya yang paling ditunggu-tunggu.”',
      'Hitung mundur 3-2-… berhenti: “DPIA?” → penilaian selesai → meluncur → CTA',
      'DPIA', 'dpia-risiko', '15 dtk', 'M05'),
    R('SN14', 'Hujan karakter',
      'Kolom karakter jatuh seperti hujan di layar gelap.',
      'Kolom teks translateY berkecepatan beda; karakter dari hash.',
      'Bisa', 2, 7, 7,
      'Hujan Data', 'Anomali', '“Di antara hujan ini ada 1 NIK. Temukan.”',
      'Hujan karakter → satu rangkaian menyala merah: NIK → pemindaian menemukan → CTA',
      'Data Discovery', '—', '15 dtk', 'Baru', 'Warna & susunan sendiri; jangan meniru film tertentu.'),
    R('SN15', 'Ruang kendali (HUD)',
      'Panel-panel tembus pandang bergaya ruang kendali.',
      'Panel garis tipis; angka bergerak; lingkaran target.',
      'Bisa', 3, 8, 8,
      'War Room', 'Relate', '“Jam 03.07. War room dibuka.”',
      'Panel peran (RACI) → linimasa → templat pemberitahuan → hitung mundur → CTA',
      'Manajemen Insiden', 'breach-aksi', '20 dtk', 'M11'),
    R('SN16', 'Kamera termal',
      'Citra termal: biru dingin sampai merah panas.',
      'Peta warna dari gradasi; bercak panas berdenyut.',
      'Sudah (SN16)', 2, 8, 8,
      'Yang Panas', 'Anomali', '“Dilihat dengan kamera termal, titik paling panas ada di sini.”',
      'Citra termal kantor (gambar) → titik panas → matriks risiko 5×5 asli → CTA',
      'DPIA', 'dashboard-risiko', '15 dtk', 'Baru'),
    R('SN17', 'Strip film / lembar kontak',
      'Deretan bingkai film berlubang; beberapa dilingkari spidol merah.',
      'Strip dengan lubang; bingkai berisi kartu; lingkaran digambar.',
      'Sudah (SN17)', 2, 7, 7,
      '36 Bingkai', 'Anomali', '“36 bingkai. Hanya 3 yang penting saat insiden.”',
      'Strip berjalan → 3 bingkai dilingkari: catat, tahan, beri tahu → CTA',
      'Manajemen Insiden', 'breach-fase', '15 dtk', 'Baru', 'Angka = ilustrasi.'),
    R('SN18', 'Jejak cahaya (light painting)',
      'Garis cahaya meninggalkan jejak yang memudar pelan.',
      'Path dengan ekor memudar; pendar aditif.',
      'Bisa', 3, 8, 8,
      'Jejak', 'Anomali', '“Setiap gerakan meninggalkan jejak.”',
      'Jejak cahaya mengikuti kursor → jejak = log audit manusia & AI → CTA',
      'Log audit', '—', '10 dtk', 'Baru'),
    R('SN19', 'Hitam-putih + satu warna',
      'Seluruh layar abu-abu; hanya satu hal berwarna.',
      'Filter grayscale; elemen aksen tanpa filter.',
      'Sudah (SN19)', 1, 7, 9,
      'Satu Warna', 'Anomali', '“Di formulir ini, hanya satu kolom yang berwarna merah.”',
      'Formulir abu-abu → kolom data spesifik merah → risiko TINGGI otomatis → CTA',
      'RoPA', 'ropa-data-spesifik', '15 dtk', 'A11'),
    R('SN20', 'Hitung mundur film (3-2-1)',
      'Lingkaran hitung mundur film lama dengan jarum berputar.',
      'Jarum conic berputar; angka besar; goresan film.',
      'Bisa', 1, 6, 7,
      '3, 2, 1', 'Anomali', '“3… 2… 1…”',
      'Hitung mundur → “PP 33 berlaku.” → logo → CTA',
      'Program siap PP 33', '—', '5 dtk', 'P04 (bumper)'),
    R('SN21', 'Parallax foto 2.5D',
      'Foto diam diberi kedalaman; latar dan objek bergerak beda.',
      'Butuh foto berlisensi + pemotongan lapisan.',
      'Berat', 4, 7, 8,
      '—', '—', '—', '—', '—', '—', '—', '—', 'Perlu foto berlisensi (unduhan seizin pengguna).'),
    R('SN22', 'Footage stok + caption',
      'Potongan video nyata dengan caption tebal di atasnya.',
      'Butuh video stok berlisensi bebas; pipeline sekarang berbasis halaman HTML.',
      'Berat', 4, 7, 8,
      '—', '—', '—', '—', '—', '—', '—', '—', 'Bisa ditambahkan: video stok sebagai latar (unduhan seizin pengguna, cek lisensi).'),
    R('SN23', '3D fotoreal',
      'Render produk atau ruang tiga dimensi realistis.',
      'Di luar kemampuan mesin berbasis HTML.',
      'Tidak cocok', 5, 9, 8,
      '—', '—', '—', '—', '—', '—', '—', '—', 'Butuh perangkat 3D & artis.'),

    # ====================================================================== 6 · PARODI FORMAT
    R('PF01', 'Iklan TV jadul',
      'Parodi iklan obat 90-an: warna norak, bintang berputar, jingle.',
      'Bingkai 4:3; efek bintang; teks melengkung.',
      'Sudah (N04)', 3, 9, 7,
      'RoPA (Parodi Iklan Obat)', 'Relate', 'Pusing karena RoPA di spreadsheet?',
      'Keluhan → “obatnya” → cara pakai → CTA',
      'RoPA', 'ropa-baru, ropa-tersimpan', '50,7 dtk', 'N04 (sudah dirender)'),
    R('PF02', 'Arcade RPG 8-bit',
      'Game piksel: tokoh, kotak dialog, bilah nyawa.',
      'Font piksel; kotak dialog; musik chip.',
      'Sudah (N09)', 3, 9, 7,
      'PPDP Baru', 'Relate', 'Kamu naik level jadi PPDP.',
      'Misi → pelatihan → pendampingan → CTA',
      'DPO Academy, konsultasi', 'dpo-academy', '52 dtk', 'N09 (sudah dirender)'),
    R('PF03', 'Kompilasi meme',
      'Potongan cepat berbagai format meme dalam satu video.',
      'Tipe scene meme di n11-meme-dpo/style.js.',
      'Sudah (N11)', 4, 9, 6,
      'Hidup DPO (2026)', 'Relate', '“Yep, itu aku. Pasti bingung kok bisa begini.”',
      'Freeze frame → orang have → astaga bercanda → things to say → polyester edit → kinda chic → CTA',
      'Semua modul', 'dashboard', '66,6 dtk', 'N11 (sudah dirender)'),
    R('PF04', 'Majalah editorial',
      'Tata letak majalah mewah: serif besar, ruang kosong lapang.',
      'Grid editorial; serif kontras tinggi; garis tipis.',
      'Sudah (N07)', 3, 8, 9,
      'Konsultan PDP', 'Logika dipatahkan', 'Konsultan terbaik bukan yang laporannya paling tebal.',
      'Masalah → pendampingan → CTA konsultasi',
      'Konsultasi', '—', '45 dtk', 'N07 (sudah dirender)'),
    R('PF05', 'Komik / pop-art',
      'Panel komik, titik halftone, balon kata, huruf efek suara.',
      'Panel dengan garis tebal; balon SVG; tokoh emoji/bentuk.',
      'Bisa', 3, 9, 7,
      'Nobody: / Marketing Jam 5 Sore', 'Relate', '“Nobody: … Marketing jam 5 sore: ‘blast promo ke semua nomor di database ya!’”',
      'Panel 1 kosong (jangkrik) → panel 2 balon marketing → panel 3 “HAH?!” → panel 4 cek persetujuan → CTA',
      'Consent & Cookie', 'consent-detail', '20 dtk', 'A09', 'Tokoh = emoji/bentuk, bukan karakter komik yang sudah ada.'),
    R('PF06', 'Breaking news TV',
      'Layar berita: judul merah, teks berjalan, jam pojok.',
      'Lower-third; teks berjalan; kilat “sekilas info”.',
      'Bisa', 2, 8, 8,
      'Sekilas Info', 'Anomali', '“Sekilas info: sebuah perusahaan menemukan 14 salinan data yang sama.”',
      'Judul berita → teks berjalan berisi fakta UU PDP → Data Discovery → CTA',
      'Data Discovery', '—', '15 dtk', 'Baru', 'Stasiun TV fiktif; angka = ilustrasi.'),
    R('PF07', 'Kuis / game show',
      'Pertanyaan di layar, empat pilihan, timer, lampu berkedip.',
      'Kartu pilihan menyala; timer melingkar; bunyi benar/salah.',
      'Bisa', 2, 8, 8,
      'Kuis 3×24', 'Relate', '“Berapa lama batas pemberitahuan insiden? A. Nanti saja. B. 3×24 jam.”',
      'Timer → jawaban B menyala → penghitung mundur otomatis di Nexus → CTA',
      'Manajemen Insiden', 'breach-detail', '15 dtk', 'Baru', 'Tata letak sendiri; jangan meniru acara kuis tertentu.'),
    R('PF08', 'Struk belanja',
      'Kertas printer termal memanjang; daftar barang dan TOTAL.',
      'Kertas tumbuh ke bawah; baris dicetak per karakter; tepi sobek zigzag.',
      'Sudah (PF08)', 2, 9, 8,
      'Emotional Damage: Denda 2%', 'Anomali', '“CFO membaca: denda administratif hingga 2% dari pendapatan tahunan.”',
      'Struk mencetak daftar kelalaian → TOTAL: hingga 2% pendapatan tahunan → cap → pemetaan paparan sanksi → CTA',
      'Paparan Sanksi Administratif', '—', '20 dtk', 'A08', 'Contoh rupiah = ilustrasi; frasa direkam tim/TTS tanpa meniru persona.'),
    R('PF09', 'Tier list',
      'Papan peringkat S sampai F; kartu dilempar ke barisnya.',
      'Baris berwarna; kartu masuk dengan lintasan.',
      'Bisa', 2, 8, 7,
      'Tier List Kebiasaan Data', 'Relate', '“Tier list kebiasaan data di kantor.”',
      'F: password di kertas tempel · D: kirim KTP lewat grup · S: register terpusat → CTA',
      'RoPA, DPO Academy', '—', '15 dtk', 'A19 / A43'),
    R('PF10', 'Bingo',
      'Kartu bingo 5×5; kotak dicoret satu-satu sampai BINGO.',
      'Grid; coretan digambar; garis bingo menyala.',
      'Bisa', 2, 8, 7,
      'Bingo Rapat Kepatuhan', 'Relate', '“Bingo rapat kepatuhan. Kotak tengah: ‘nanti kita follow up’.”',
      'Kotak dicoret → BINGO → rapat berikutnya cukup buka dasbor → CTA',
      'Dasbor kepatuhan', 'dashboard', '15 dtk', 'Baru', 'Kartu bisa dibagikan sebagai gambar.'),
    R('PF11', 'Prakiraan cuaca',
      'Peta cuaca dengan ikon matahari, awan, dan petir per wilayah.',
      'Peta bentuk sederhana; ikon cuaca; pembawa acara = suara saja.',
      'Sudah (PF11)', 3, 8, 8,
      'Prakiraan Kepatuhan', 'Anomali', '“Prakiraan kepatuhan hari ini: cerah di Legal, badai lokal di Marketing.”',
      'Peta divisi (bukan peta negara) → badai di satu divisi → dasbor & skor per area → CTA',
      'Dasbor, GAP', 'gap-hasil', '15 dtk', 'Baru'),
    R('PF12', 'Acara masak / resep',
      'Kartu resep: bahan, takaran, langkah bernomor.',
      'Kartu resep; bahan masuk mangkuk (ikon); langkah dicentang.',
      'Bisa', 2, 8, 7,
      'Resep RoPA Anti Gagal', 'Relate', '“Resep RoPA anti gagal. Bahan: tujuan, dasar pemrosesan, kategori data.”',
      'Bahan masuk → aduk (wizard) → matang: rekaman berkode → CTA',
      'RoPA (wizard)', 'ropa-baru, ropa-tersimpan', '15 dtk', 'Baru'),
    R('PF13', 'Zodiak / ramalan',
      'Kartu ramalan mingguan per “zodiak” profesi.',
      'Kartu berputar; ikon bintang; teks ramalan.',
      'Bisa', 1, 7, 6,
      'Ramalan DPO Minggu Ini', 'Relate', '“Ramalan DPO minggu ini: akan ada yang bertanya ‘data pribadi itu apa, sih?’.”',
      'Ramalan lucu → “keberuntungan: dasbor” → CTA',
      'Brand', '—', '10 dtk', 'Baru', 'Untuk organik.'),
    R('PF14', 'Visual novel',
      'Kotak dialog di bawah, pilihan jawaban, latar ruangan.',
      'Kotak dialog mengetik; pilihan menyala; latar bentuk sederhana.',
      'Bisa', 2, 8, 7,
      'Pilih Jawabanmu', 'Relate', '“Auditor: ‘RoPA-nya mana?’ ▶ A. ‘Sebentar…’ ▶ B. ‘Ini.’”',
      'Pilihan A → akhir buruk → ulang → pilihan B → akhir baik → CTA',
      'RoPA', 'ropa-list-baru', '20 dtk', 'Baru', 'Tokoh = siluet; tanpa gaya karakter gim tertentu.'),
    R('PF15', 'Boarding pass',
      'Tiket pesawat dengan kolom asal, tujuan, dan gerbang.',
      'Kartu tiket; teks mengetik; sobekan kupon.',
      'Bisa', 2, 8, 8,
      'Penerbangan Data', 'Logika dipatahkan', '“Penumpang: data pelanggan. Tujuan: ‘cloud’. Negara: ???”',
      'Tiket dicetak → kolom negara kosong → register transfer + TIA → CTA',
      'Transfer Data Lintas Negara', '—', '15 dtk', 'M14', 'Maskapai fiktif.'),
    R('PF16', 'Rapor sekolah',
      'Buku rapor: mata pelajaran, nilai, catatan wali kelas.',
      'Tabel nilai; angka ditulis tangan; cap.',
      'Bisa', 2, 9, 8,
      'Rapor Kepatuhan', 'Relate', '“Rapor semester ini. Catatan wali kelas: ‘sebenarnya mampu, tapi kurang mencatat’.”',
      'Nilai per mata pelajaran (per area) → catatan → skor GAP asli → CTA',
      'GAP Assessment', 'gap-hasil', '15 dtk', 'Baru (lokal)'),
    R('PF17', 'Undangan',
      'Kartu undangan berornamen: nama acara, waktu, tempat.',
      'Kartu dengan ornamen; teks muncul berurutan; pita.',
      'Bisa', 2, 9, 7,
      'Turut Mengundang: Auditor', 'Relate', '“Dengan hormat, kami mengundang Bapak/Ibu pada acara: AUDIT.”',
      'Undangan dibuka → “tanpa perlu membawa kado, cukup bukti” → dasbor & bukti siap → CTA',
      'GAP, Dasbor', 'dashboard', '15 dtk', 'Baru (lokal)'),
    R('PF18', 'Poster film',
      'Poster bioskop: judul besar, slogan, “segera tayang”.',
      'Tata letak poster; huruf kredit kecil; cahaya menyapu.',
      'Bisa', 2, 7, 7,
      'Segera Tayang', 'Anomali', '“Segera tayang di seluruh kantor Indonesia: 16 Januari 2027.”',
      'Poster terbuka → slogan → daftar persiapan → CTA',
      'Program siap PP 33', '—', '10 dtk', 'A23', 'Judul & poster fiktif.'),
    R('PF19', 'Trailer film',
      'Kartu teks dramatis, dentuman, potongan cepat.',
      'Kartu hitam; huruf logam; dentum + riser.',
      'Bisa', 2, 8, 7,
      'Musim Ini', 'Anomali', '“Musim ini… satu peraturan… mengubah cara kantormu menyimpan data.”',
      'Kartu dramatis → potongan layar asli → judul: PP 33 → CTA',
      'Program siap PP 33', 'dashboard, breach-detail', '15 dtk', 'Baru'),
    R('PF20', 'Koran / berita utama',
      'Halaman depan koran dengan judul besar.',
      'Tata letak kolom; judul masuk berputar; tekstur kertas.',
      'Bisa', 2, 8, 8,
      'Berita Utama Besok', 'Anomali', '“Berita utama yang tidak ingin kamu baca tentang perusahaanmu.”',
      'Koran berputar → judul (fiktif) → “masih bisa dicegah” → latihan insiden → CTA',
      'Simulasi & Fire Drill', 'fire-drill-header', '15 dtk', 'Baru', 'Koran & berita fiktif.'),
    R('PF21', 'Label nilai gizi',
      'Label hitam-putih seperti di kemasan makanan.',
      'Tabel garis tebal; baris muncul; angka persen.',
      'Sudah (PF21)', 1, 9, 8,
      'Informasi Nilai Data', 'Anomali', '“Informasi nilai data. Takaran saji: 1 formulir.”',
      'Label: nama, NIK, email, lokasi → “mengandung data spesifik” → tercatat di RoPA → CTA',
      'RoPA, Consent', 'ropa-data-spesifik', '15 dtk', 'Baru'),
    R('PF22', 'Petunjuk perakitan',
      'Gambar garis langkah demi langkah dengan nomor dan panah.',
      'Ilustrasi garis; nomor langkah; panah; sisa baut.',
      'Sudah (PF22)', 3, 8, 8,
      'Cara Merakit Kepatuhan', 'Relate', '“Langkah 1 dari 48. Sisa baut: 3.”',
      'Perakitan membingungkan → versi Nexus: wizard bertahap → CTA',
      'RoPA (wizard)', 'ropa-baru', '15 dtk', 'Baru', 'Gaya gambar sendiri; tanpa merek furnitur.'),
    R('PF23', 'Kartu keselamatan',
      'Kartu petunjuk keselamatan dengan gambar langkah darurat.',
      'Panel ilustrasi garis; nomor; panah.',
      'Bisa', 3, 9, 9,
      'Dalam Keadaan Darurat', 'Anomali', '“Dalam keadaan darurat insiden data, tetap tenang dan ikuti lima fase berikut.”',
      'Panel 1–5: fase insiden → “pintu darurat”: templat pemberitahuan → CTA',
      'Manajemen Insiden', 'breach-detail', '20 dtk', 'Baru', 'Tanpa logo maskapai.'),
    R('PF24', 'Slip gaji',
      'Slip gaji dengan baris tunjangan dan potongan.',
      'Tabel slip; baris mengetik; total.',
      'Sudah (PF24)', 1, 8, 6,
      'Slip Gaji DPO', 'Relate', '“Tunjangan sabar: Rp0. Lembur audit: tidak tercatat.”',
      'Baris slip lucu → “bantuan: antrean kerja & asisten AI” → CTA',
      'Dukungan PPDP', '—', '10 dtk', 'Baru', 'Nominal = lelucon.'),
    R('PF25', 'Judul FTV',
      'Judul sinetron panjang dengan huruf dramatis dan latar norak.',
      'Huruf bergradasi; kilau; latar gradasi jingga.',
      'Bisa', 2, 9, 6,
      'Judul FTV', 'Relate', '“Aku Ditunjuk Jadi DPO Padahal Cuma Tanya Password WiFi.”',
      'Judul 1–3 makin absurd → “episode berikutnya: ikut kelas DPO Academy” → CTA',
      'DPO Academy', 'dpo-academy', '15 dtk', 'A36', 'Tanpa logo stasiun TV.'),
    R('PF26', 'Dokumenter alam',
      'Narasi dokumenter satwa dengan teks keterangan spesies.',
      'Teks keterangan serif; bingkai sinematik; ilustrasi bentuk.',
      'Bisa', 2, 8, 7,
      'Di Habitat Aslinya', 'Relate', '“Di habitat aslinya, DPO jarang terlihat makan siang.”',
      'Narasi pengamatan → “spesies ini kini dibantu antrean kerja” → CTA',
      'Dukungan PPDP', 'dashboard', '15 dtk', 'A21 (varian)'),
    R('PF27', 'Ulasan bintang',
      'Kartu ulasan pelanggan dengan bintang.',
      'Kartu ulasan; bintang terisi; teks mengetik.',
      'Bisa', 1, 8, 8,
      'Ulasan Bintang 1', 'Anomali', '“★☆☆☆☆ ‘Sudah minta hapus data tiga kali.’”',
      'Ulasan (ilustrasi) → tenggat & pelacakan DSR → CTA',
      'DSR', 'dsr-detail', '10 dtk', 'Baru', 'Ulasan fiktif; beri label ilustrasi.'),
    R('PF28', 'Trailer horor',
      'Layar gelap, teks berkedip, suara napas.',
      'Flicker; vignette pekat; teks bergetar.',
      'Sudah (PF28)', 2, 8, 6,
      'Jangan Buka File Itu', 'Reverse psychology', '“Jangan buka file itu.”',
      'File RoPA lama terbuka sendiri → 14 tab → lampu menyala: diimpor dengan AI → CTA',
      'Document Import, RoPA', 'ropa-list-baru', '15 dtk', 'Baru'),
    R('PF29', 'Pengumuman stasiun',
      'Papan informasi dan suara pengumuman.',
      'Papan jadwal; teks bergulir; suara TTS dengan efek aula.',
      'Bisa', 2, 7, 7,
      'Perhatian, Perhatian', 'Relate', '“Perhatian: data tujuan luar negeri dipersilakan melapor ke meja transfer.”',
      'Pengumuman → papan: tujuan & dasar pelindungan → register transfer → CTA',
      'Transfer Data Lintas Negara', '—', '15 dtk', 'Baru', 'Tanpa nama/lambang operator.'),
    R('PF30', 'Siaran olahraga (tayangan ulang)',
      'Papan skor, garis analisis, dan tayangan ulang lambat.',
      'Papan skor; garis digambar di atas layar; label “tayangan ulang”.',
      'Bisa', 3, 9, 8,
      'Tayangan Ulang', 'Anomali', '“Kita lihat tayangan ulangnya: siapa yang terakhir menyentuh data ini?”',
      'Tayangan ulang log → garis analisis → keputusan: tercatat → CTA',
      'Log audit', '—', '15 dtk', 'A42', 'Tanpa logo liga/stasiun.'),
    R('PF31', 'Bursa / ticker',
      'Angka indeks dan grafik garis naik-turun dengan teks berjalan.',
      'Grafik garis digambar; ticker; panah hijau/merah.',
      'Bisa', 2, 7, 8,
      'Indeks Kepatuhan', 'Anomali', '“Indeks kepatuhan ditutup menguat di 81.”',
      'Grafik tren per modul → skor → CTA',
      'Dasbor (tren)', 'dashboard-postur', '10 dtk', 'Baru', 'Angka dari data demo di screenshot.'),
    R('PF32', 'Label museum',
      'Benda di etalase dengan kartu keterangan museum.',
      'Etalase; lampu sorot; kartu keterangan serif.',
      'Bisa', 2, 9, 8,
      'Artefak', 'Relate', '“Artefak: spreadsheet RoPA, sekitar 2019. Bahan: 14 tab, 1 orang yang paham.”',
      'Artefak 1–2 → “koleksi terbaru: register terpusat” → CTA',
      'RoPA', 'ropa-list-baru', '15 dtk', 'M04 (varian)'),
    R('PF33', 'Peta harta karun',
      'Peta kertas tua dengan garis putus-putus dan tanda X.',
      'Garis putus digambar; tekstur kertas; X dicap.',
      'Bisa', 2, 7, 7,
      'X Menandai Lokasinya', 'Anomali', '“Di peta ini ada 5 tanda X. Semuanya data pribadi.”',
      'Garis menuju X → tiap X = sumber data → katalog sistem → CTA',
      'Data Discovery', '—', '15 dtk', 'Baru', 'Angka = ilustrasi.'),
    R('PF34', 'Ular tangga',
      'Papan permainan; bidak naik tangga atau turun ular.',
      'Grid bernomor; bidak melompat; ular & tangga path.',
      'Sudah (PF34)', 3, 9, 8,
      'Ular Tangga Kepatuhan', 'Relate', '“Kotak 47: lupa mencatat pihak ketiga. Turun ke kotak 12.”',
      'Bidak naik tangga (RoPA, DPIA) → kena ular (kelalaian) → tangga panjang: Nexus → CTA',
      'Platform', '—', '20 dtk', 'Baru (lokal)'),
    R('PF35', 'Kartu koleksi',
      'Kartu bergambar dengan nama, kemampuan, dan angka kekuatan.',
      'Kartu flip; kilau; angka menghitung.',
      'Sudah (PF35)', 2, 8, 7,
      'Kartu Modul', 'Anomali', '“Kartu langka: DPIA. Kemampuan: menilai sebelum terlambat.”',
      'Kartu RoPA, DPIA, DSR dibuka → satu set lengkap → CTA',
      'Platform', '—', '15 dtk', 'Baru', 'Desain kartu sendiri.'),
    R('PF36', 'Peliharaan digital',
      'Layar kecil piksel dengan peliharaan yang harus dirawat.',
      'Layar LCD semu; sprite piksel buatan sendiri; bilah lapar.',
      'Bisa', 3, 9, 7,
      'Rawat RoPA-mu', 'Relate', '“RoPA-mu lapar. Terakhir diperbarui 214 hari lalu.”',
      'Peliharaan lesu → diberi makan (diperbarui) → riwayat perubahan → CTA',
      'RoPA', '—', '15 dtk', 'Baru', 'Desain sendiri; tanpa merek mainan. Angka = ilustrasi.'),
    R('PF37', 'Ponsel jadul (SMS)',
      'Layar ponsel monokrom dengan pesan singkat.',
      'Layar piksel hijau; teks mengetik; bunyi bip.',
      'Bisa', 2, 7, 6,
      '1 Pesan Diterima', 'Relate', '“1 pesan diterima: ‘Hapus data saya.’”',
      'SMS 2006 → email 2016 → formulir DSR 2026 → CTA',
      'DSR', 'dsr-form', '15 dtk', 'Baru', 'Ponsel fiktif.'),
    R('PF38', 'Iklan baris',
      'Kolom iklan baris koran dengan teks rapat.',
      'Kolom teks; satu iklan disorot & membesar.',
      'Bisa', 1, 7, 6,
      'Dicari', 'Relate', '“DICARI: orang yang paham isi spreadsheet ini.”',
      'Iklan baris lucu → “atau pindahkan ke register” → CTA',
      'RoPA', '—', '10 dtk', 'M04 (varian)'),
    R('PF39', 'Petunjuk alat pemadam',
      'Stiker petunjuk pemakaian di dinding: tarik, arahkan, tekan.',
      'Panel ikon garis; nomor; panah.',
      'Bisa', 2, 8, 9,
      'Latihan yang Terlupa', 'Logika dipatahkan', '“Kantor rutin latihan kebakaran. Latihan kebocoran data? …hening.”',
      'Petunjuk pemadam → petunjuk insiden data dengan gaya sama → Fire Drill → CTA',
      'Simulasi & Fire Drill', 'fire-drill-header', '15 dtk', 'M12 / A30'),

    # ====================================================================== 7 · STRUKTUR EDIT
    R('SE01', 'Split-screen',
      'Layar dibagi dua; dua cerita berjalan bersamaan.',
      'Dua wadah; waktu sama; garis pemisah bisa bergeser.',
      'Bisa', 2, 7, 8,
      'DPO A vs DPO B', 'Relate', '“Jam 3 pagi, insiden. DPO A vs DPO B.”',
      'Kiri panik, kanan tenang → bedanya alur siap → CTA',
      'Manajemen Insiden', 'breach-detail', '20 dtk', 'A44', 'Digabung dengan SN02 (neon).'),
    R('SE02', 'POV',
      'Sudut pandang orang pertama; teks “POV:” di atas.',
      'Bingkai tangan/kursor; teks POV; guncangan kecil.',
      'Bisa', 1, 7, 7,
      'POV: Auditor Minta RoPA', 'Relate', '“POV: auditor minta RoPA.”',
      'POV membuka file → gagal → register → CTA',
      'RoPA', 'ropa-list-baru', '20 dtk', 'A01', 'Digabung dengan UI05 (retro OS).'),
    R('SE03', 'Countdown / daftar bernomor',
      'Daftar 5 sampai 1 dengan angka besar.',
      'Angka besar berganti; kartu isi; bilah progres.',
      'Bisa', 1, 6, 8,
      '5 Tanda Belum Siap PP 33', 'Anomali', '“5 tanda perusahaanmu belum siap PP 33.”',
      '5 → 1 → GAP Assessment → CTA',
      'GAP, program siap PP 33', 'gap-rekomendasi', '20 dtk', 'A46', 'Digabung dengan GB08 (halftone).'),
    R('SE04', 'Day in the life',
      'Sehari penuh dengan cap jam di tiap potongan.',
      'Cap jam besar; potongan pendek per jam.',
      'Bisa', 2, 7, 7,
      'Sehari Jadi DPO', 'Relate', '“Day in the life of a DPO. Versi jujur.”',
      '08.00 → 13.00 → 17.00 → 03.00 → antrean kerja → CTA',
      'Dukungan PPDP', 'dashboard', '30 dtk', 'A21', 'Digabung dengan GB07 atau UI06.'),
    R('SE05', 'Ekspektasi vs realita',
      'Dua kartu berdampingan: bayangan vs kenyataan.',
      'Kartu kiri rapi, kanan kacau; label.',
      'Bisa', 1, 7, 7,
      'Ekspektasi vs Realita Jadi DPO', 'Relate', '“Ekspektasi: membaca regulasi. Realita: mengejar orang isi form.”',
      '3 pasang ekspektasi–realita → alur RoPA dengan tautan isi untuk pihak ketiga → CTA',
      'RoPA', 'ropa-baru', '15 dtk', 'A14'),
    R('SE06', 'Loop sempurna',
      'Akhir video tersambung mulus ke awal.',
      'Bingkai terakhir = bingkai pertama; teks menyambung.',
      'Bisa', 2, 8, 7,
      'Revisi Tanpa Akhir', 'Relate', '“Video ini tidak punya akhir. Seperti revisi RoPA-mu.”',
      'final → final_v2 → final_FIX → (kembali ke awal) · keluar dari loop: register → CTA di caption',
      'RoPA', '—', '10 dtk', 'Baru', 'CTA ditaruh di tengah/caption karena video berulang.'),
    R('SE07', 'Infinite zoom',
      'Kamera terus masuk ke detail, membuka adegan baru di dalamnya.',
      'Skala eksponensial bertingkat antar adegan.',
      'Bisa', 3, 9, 8,
      'Dari Formulir ke Dasbor', 'Anomali', '“Masuk ke kotak centang ini.”',
      'Kotak centang → log persetujuan → RoPA → DPIA → dasbor → CTA',
      'Platform', 'consent-detail, ropa-tersimpan, dashboard', '20 dtk', 'Flow unggulan (versi 30 dtk)'),
    R('SE08', 'Sebelum/sesudah (geser)',
      'Garis pemisah digeser memperlihatkan sebelum dan sesudah.',
      'Dua lapis dengan clip-path; pegangan geser.',
      'Bisa', 1, 7, 9,
      'Geser', 'Anomali', '“Geser ke kanan.”',
      'Kiri: spreadsheet 14 tab · kanan: register RoPA → CTA',
      'RoPA', 'ropa-list-baru', '10 dtk', 'M04'),
    R('SE09', 'Satu tarikan kamera (one-take)',
      'Kamera bergerak menerus tanpa potongan melewati semua adegan.',
      'Satu kanvas panjang; kamera translate/rotate halus.',
      'Bisa', 3, 8, 9,
      'Satu Tarikan Napas', 'Anomali', '“Satu tarikan napas, semua modul.”',
      'Kamera melewati GAP → RoPA → DPIA → DSR → Insiden → CTA',
      'Platform', 'gap-hasil, ropa-list-baru, dpia-risiko, dsr-detail, breach-detail', '25 dtk', 'Flow unggulan (versi 30 dtk)'),
    R('SE10', 'Putar balik (rewind)',
      'Cerita dimulai dari akhir lalu diputar mundur.',
      'Waktu cerita dibalik; efek pita mundur; SFX rewind.',
      'Bisa', 2, 8, 8,
      'Putar Balik', 'Anomali', '“Kita putar balik: 3×24 jam sebelum berita ini terbit.”',
      'Akhir: berita → mundur → titik keputusan: latihan & alur siap → CTA',
      'Insiden, Fire Drill', 'breach-detail', '20 dtk', 'Baru'),
    R('SE11', 'Match cut (bentuk sama)',
      'Potongan antar adegan lewat bentuk yang sama.',
      'Bentuk kunci (lingkaran/kotak) dipertahankan posisi & ukurannya.',
      'Bisa', 3, 8, 8,
      'Bentuk yang Sama', 'Anomali', '“Lingkaran ini: tombol Setuju.”',
      'Lingkaran = tombol → jam tenggat → skor → logo → CTA',
      'Platform', '—', '15 dtk', 'Baru'),
    R('SE12', 'Freeze frame + narator',
      'Adegan membeku; narator menjelaskan “itu aku”.',
      'Bingkai beku hitam-putih; lingkaran spidol; SFX scratch.',
      'Sudah (N11)', 2, 8, 7,
      'Hidup DPO (pembuka)', 'Relate', '“Yep, itu aku.”',
      'Freeze → putar balik → cerita',
      'Brand', '—', '5 dtk', 'N11 (sudah dirender)'),
    R('SE13', 'Callback (akhir kembali ke hook)',
      'Kalimat penutup mengulang hook dengan makna baru.',
      'Teks hook muncul lagi sebelum CTA.',
      'Sudah (T01)', 1, 7, 8,
      'Satu Platform (penutup)', 'Anomali', '“…atau masih 12 spreadsheet?”',
      'Hook → isi → hook diulang → CTA',
      'Platform', '—', '—', 'T01 (sudah dirender)'),
    R('SE14', 'Mitos vs fakta',
      'Kartu MITOS dicap FAKTA bergantian.',
      'Kartu flip; cap; warna merah/hijau.',
      'Bisa', 1, 6, 9,
      'Mitos: Ini Urusan IT', 'Logika dipatahkan', '“Mitos: pelindungan data pribadi itu urusan tim IT saja.”',
      '3 mitos → fakta singkat → modul terkait → CTA',
      'Platform', '—', '20 dtk', 'Baru', 'Tiap fakta wajib punya dasar pasal.'),
    R('SE15', 'Ini atau itu',
      'Dua pilihan; penonton diminta memilih di komentar.',
      'Dua kartu; bilah suara; hitung mundur.',
      'Bisa', 1, 7, 7,
      'Pilih Satu', 'Relate', '“Pilih satu: audit mendadak atau 200 permohonan hapus data?”',
      'Pilihan → “atau siap untuk keduanya” → CTA',
      'Platform', '—', '10 dtk', 'Baru', 'Untuk interaksi organik.'),
    R('SE16', 'Kuis jeda',
      'Pertanyaan muncul; penonton diminta menjeda video.',
      'Timer; tombol jeda besar; jawaban terbuka.',
      'Bisa', 1, 7, 7,
      'Jeda Video Ini', 'Reverse psychology', '“Jangan jeda video ini… kecuali kamu tahu jawabannya.”',
      'Pertanyaan: “berapa jam tenggat DSR di Nexus?” → jawaban 72 jam → CTA',
      'DSR', 'dsr-detail', '10 dtk', 'Baru'),
    R('SE17', 'Time-lapse',
      'Waktu dipercepat; hari berganti dalam hitungan detik.',
      'Penanda tanggal berjalan; grafik tumbuh.',
      'Bisa', 2, 7, 8,
      'Setahun dalam 15 Detik', 'Anomali', '“Setahun kepatuhan dalam 15 detik.”',
      'Tren bulanan tumbuh → skor naik → CTA',
      'Dasbor (tren)', 'dashboard-postur', '15 dtk', 'Baru', 'Angka dari data demo di screenshot.'),
    R('SE18', 'Zoom-out reveal',
      'Mulai dari detail kecil, mundur memperlihatkan gambar besar.',
      'Skala mengecil bertahap; elemen baru masuk bingkai.',
      'Bisa', 2, 8, 9,
      'Mundur Selangkah', 'Anomali', '“Ini satu baris data. Mundur selangkah.”',
      'Satu baris → satu sistem → semua sistem → katalog → CTA',
      'Data Discovery', '—', '15 dtk', 'Baru'),
    R('SE19', 'Speedrun (pakai timer)',
      'Stopwatch berjalan sementara tugas diselesaikan.',
      'Butuh rekaman layar asli + bukti klaim waktu.',
      'Berat', 3, 8, 8,
      '#RoPA60Detik', 'Reverse psychology', '“Bisa isi 1 RoPA dalam 60 detik?”',
      'Timer → pengisian berbantuan AI → selesai → CTA',
      'RoPA (isi otomatis berbantuan AI)', 'ropa-baru', '60 dtk', 'A48', 'Klaim waktu harus dibuktikan dengan rekaman layar nyata.'),
    R('SE20', 'Tutorial 3 langkah',
      'Tiga langkah bernomor, masing-masing satu layar.',
      'Angka besar; screenshot; centang.',
      'Bisa', 1, 5, 10,
      'Tiga Langkah Pre Check', 'Relate', '“Tiga langkah untuk tahu posisi kepatuhanmu.”',
      '1 mulai asesmen → 2 jawab → 3 lihat skor & rekomendasi → CTA',
      'GAP Assessment', 'gap-mulai, gap-hasil, gap-rekomendasi', '20 dtk', 'Baru'),
    R('SE21', 'Dialog dua suara',
      'Dua suara bergantian; teks tiap suara di sisi berbeda.',
      'Dua suara TTS/VN; teks kiri-kanan; jeda komedi.',
      'Bisa', 1, 7, 8,
      'Di Cloud', 'Logika dipatahkan', '“‘Datanya di mana?’ ‘Di cloud.’ ‘Cloud-nya di negara mana?’”',
      'Tanya-jawab → hening → register transfer → CTA',
      'Transfer Data Lintas Negara', '—', '15 dtk', 'M14 / A34'),
    R('SE22', 'Tenggat nyata dipadatkan',
      'Waktu 72 jam dipadatkan; jam berputar cepat.',
      'Jam berputar; penanda hari; tugas selesai bertahap.',
      'Bisa', 2, 8, 8,
      '72 Jam dalam 30 Detik', 'Anomali', '“72 jam, dipadatkan jadi 30 detik.”',
      'Jam 0: insiden dicatat → jam 24: penahanan → jam 60: pemberitahuan dikirim → CTA',
      'Manajemen Insiden', 'breach-fase, breach-aksi', '30 dtk', 'Baru'),
    R('SE23', 'Fun fact storytelling + sisipan meme',
      'Narasi cepat ala video fakta unik: caption tebal 2–3 kata, panah merah, potongan reaksi meme.',
      'Caption besar per frasa dari timing VO; panah/lingkaran merah digambar; sisipan kartu meme buatan sendiri.',
      'Bisa', 2, 8, 7,
      'Ini yang Harus Kamu Lakukan Ketika Dapat Email Ini!', 'Relate', '“Ini yang harus kamu lakukan ketika dapat email ini!”',
      'Email “hapus data saya” disorot panah merah → jangan panik (sisipan meme) → 3 langkah DSR → tenggat 72 jam → CTA',
      'DSR', 'dsr-form, dsr-detail', '30 dtk', 'Baru (contoh gaya dari pengguna)',
      'Contoh acuan memakai footage asli; versi kita memakai layar asli + grafis. Footage stok perlu lisensi & izin unduh.'),
    R('SE24', 'Reaksi frasa viral',
      'Pertanyaan serius dijawab frasa viral, lalu bunyi meme.',
      'Kartu pertanyaan → kartu jawaban frasa (teks) → SFX → solusi.',
      'Bisa', 1, 9, 6,
      'Ketika Auditor Tanya', 'Relate', '“Ketika auditor tanya: ‘data pelanggan disimpan di mana?’”',
      'Jawaban frasa viral (teks + suara tim) → bunyi “FAAAH” → jawaban yang benar: katalog sistem & RoPA → CTA',
      'Data Discovery, RoPA', 'ropa-list-baru', '15 dtk', 'Baru (lihat sheet Hook Frasa Viral)',
      'FRASA SAJA: tanpa wajah, suara asli, nama, atau klip tokoh. Lihat catatan hukum di sheet Hook Frasa Viral.'),
    R('SE25', 'Balas komentar',
      'Kartu komentar di atas, jawaban video di bawahnya.',
      'Kartu komentar tiruan; jawaban bertahap.',
      'Bisa', 1, 7, 7,
      'DPO Itu Kerjanya Apa?', 'Relate', '“Membalas komentar: ‘DPO itu kerjanya apa sih?’”',
      'Komentar → 3 tugas nyata → alat bantunya → CTA',
      'Brand', 'dashboard', '15 dtk', 'A40', 'Komentar ilustrasi; tanpa nama akun nyata.'),
    R('SE26', 'Komentar layar hijau',
      'Orang berbicara di depan tangkapan layar.',
      'Butuh talenta & rekaman video.',
      'Berat', 3, 7, 8,
      '—', '—', '—', '—', '—', '—', '—', '—', 'Butuh orang di depan kamera (dan persetujuannya).'),
    R('SE27', 'Testimoni pelanggan',
      'Kutipan pelanggan dengan nama dan jabatan.',
      'Butuh testimoni asli dan izin tertulis.',
      'Tidak cocok', 2, 6, 10,
      '—', '—', '—', '—', '—', '—', '—', '—', 'Jangan mengarang testimoni. Bisa dibuat begitu ada izin tertulis.'),
]
