# Keluarga 1 · TIPOGRAFI: huruf jadi bintang utama. Satu baris = satu gaya + satu usulan video.
from gaya_base import R

ROWS = [
    # ------------------------------------------------------------------ sudah dipakai
    R('TY01', 'Kinetic typography (kamera menjelajah kanvas)',
      'Kata muncul tepat saat diucapkan; kamera geser-putar di satu kanvas besar, lalu mundur memperlihatkan semuanya.',
      'Blok teks di kanvas dunia; kamera per baris dari waktu VO; font variabel Archivo + Instrument Serif.',
      'Sudah (T02)', 4, 8, 9,
      'Jangan Tonton Video Ini', 'Reverse psychology',
      '“Jangan tonton video ini… kalau perusahaanmu tidak menyimpan satu pun data pelanggan.”',
      'Hook → PP 33 & sanksi 2% → “merasa aman” dicoret → RoPA, DPIA, DSR, insiden → kanvas utuh → CTA',
      'Platform', '—', '53,6 dtk', 'T02 (sudah dirender)'),
    R('TY02', 'Stomp / beat-cut',
      'Kata raksasa menghentak di tiap ketukan stomp-stomp-clap; warna blok berganti keras.',
      'Kartu per ketukan (durasi scene kelipatan birama), kilat di tiap clap, musik stomp disintesis.',
      'Sudah (T01)', 4, 9, 8,
      'Satu Platform', 'Anomali',
      '“12 spreadsheet. 7 folder. 3 grup chat. 1 DPO.”',
      'Hook → “Cukup. Saatnya rapi.” → 8 modul menghentak + screenshot asli → PP 33 → “Siap?” → CTA',
      'Platform', 'ropa-list-baru, dpia-risiko, dsr-detail, consent-detail, breach-detail, gap-hasil, ai-agent-chat, dpo-academy',
      '38,2 dtk', 'T01 (sudah dirender)', 'Angka hook = hiperbola.'),
    R('TY03', 'Split-flap (papan jadwal bandara)',
      'Huruf dan angka berputar seperti papan keberangkatan lama.',
      'Kartu huruf rotateX dua belahan; bunyi flip per huruf.',
      'Sudah (N01)', 3, 8, 9,
      'Hitung mundur PP 33/2026', 'Anomali',
      'Papan berputar menuju “16.01.2027”.',
      'Hitung mundur → kewajiban → program siap PP 33 → CTA',
      'Program siap PP 33', '—', '45 dtk', 'N01 (sudah dirender)'),
    R('TY04', 'Huruf guntingan + stempel (stop motion)',
      'Huruf potongan majalah ditempel satu-satu di papan gabus, stempel nilai dijatuhkan; gerak patah-patah 12 fps.',
      'Waktu dikuantisasi 12 fps, getar kecil per langkah, tekstur gabus dari hash.',
      'Sudah (T03)', 4, 9, 7,
      'Rating Kebiasaan Data di Kantor', 'Relate',
      '“Rating kebiasaan data di kantor. Jujur, ya.”',
      '1/10, 2/10, 3/10, 0/10 → papan disapu bersih → kartu Nexus 10/10 → CTA',
      'RoPA, DSR, Insiden', '—', '51,4 dtk', 'T03 / A19 (sudah dirender)', 'Nilai = lelucon rating.'),

    # ------------------------------------------------------------------ mesin tik, terminal, kode
    R('TY05', 'Mesin tik (typewriter)',
      'Kertas krem; huruf diketik satu-satu, bunyi “ting” di ujung baris, salah ketik ditimpa XXX.',
      'Huruf muncul per karakter (12–14 huruf/dtk), font Special Elite, kertas naik per baris; SFX key + ding.',
      'Sudah (TY05)', 2, 7, 8,
      'Surat yang Hampir Dikirim DPO', 'Relate',
      '“Dengan hormat, saya mengundurkan diri sebagai satu-satunya orang yang mengurus data pribadi di kantor ini.”',
      'Surat diketik → kalimat ditimpa XXX → diganti “…atau beri saya alat yang layak.” → antrean kerja & dasbor → CTA',
      'Dukungan PPDP (antrean kerja, dasbor)', 'dashboard', '20 dtk', 'Baru (turunan M20)', 'Humor empati; jangan mengejek atasan.'),
    R('TY06', 'Terminal / command line',
      'Layar hitam, huruf monospace; perintah diketik, hasil muncul baris demi baris.',
      'Ketik per karakter + kursor blok berkedip; keluaran per baris; scanline tipis; SFX key/tick.',
      'Sudah (TY06)', 2, 7, 7,
      'cari --nama "rina"', 'Anomali',
      '“Ketik nama satu pelanggan. Di berapa sistem datanya tersimpan?”',
      'Perintah cari diketik → hasil terus bertambah (CRM, email, CS, arsip) → “yang kamu tahu: 2” → Data Discovery menemukan & mengaitkan ke RoPA → CTA',
      'Data Discovery (pencarian data satu subjek untuk DSR)', '—', '20 dtk', 'A38 / P15', 'Jumlah sistem = ilustrasi.'),
    R('TY07', 'Editor kode (syntax highlight)',
      'Editor gelap dengan warna sintaks; baris kode ditulis, satu baris disorot.',
      'Span berwarna per token, ketik per karakter, nomor baris, sorot baris + komentar muncul.',
      'Sudah (TY07)', 2, 6, 7,
      'Satu Baris yang Sering Dilupakan', 'Logika dipatahkan',
      '“Tombol ‘Setuju’ itu satu baris kode. Buktinya ada di baris mana?”',
      'onClick=setuju() diketik → komentar “// lalu buktinya?” → baris API persetujuan + webhook → log persetujuan tampil → CTA',
      'Consent (API, webhook, log bukti)', 'consent-detail', '15 dtk', 'M08 (sudut developer)', 'Kode = ilustrasi, bukan dokumentasi API.'),
    R('TY35', 'ASCII art',
      'Gambar dari karakter ketik (#, /, |) di layar terminal.',
      'Blok <pre> monospace; baris muncul dari atas; karakter berganti membentuk gambar.',
      'Sudah (TY35)', 2, 7, 6,
      'README.md', 'Reverse psychology',
      '“Jangan baca README ini kalau integrasimu sudah mencatat bukti persetujuan.”',
      'README ASCII → 3 langkah integrasi (sematkan, API, webhook) → gembok ASCII → CTA',
      'Consent, DSR (API & webhook)', 'consent-detail', '15 dtk', 'Baru (audiens developer)'),

    # ------------------------------------------------------------------ huruf yang berubah bentuk
    R('TY08', 'Text mask (layar di dalam huruf)',
      'Huruf raksasa memenuhi layar; layar aplikasi asli terlihat di dalam badan huruf.',
      'background-clip: text dengan screenshot sebagai latar; kamera mendekat sampai huruf jadi jendela.',
      'Sudah (TY08)', 2, 8, 9,
      'Ada Apa di Dalam Empat Huruf Ini?', 'Anomali',
      '“RoPA. Empat huruf. Isinya: semua yang kantormu lakukan terhadap data pribadi.”',
      'RoPA raksasa → masuk ke huruf O → register RoPA asli → DPIA & DSR dengan cara sama → CTA',
      'RoPA, DPIA, DSR', 'ropa-list-baru, dpia-risiko, dsr-detail', '20 dtk', 'Baru (turunan M04)'),
    R('TY09', 'Liquid / huruf meleleh',
      'Huruf tebal meleleh, menetes, dan bergelombang seperti lilin.',
      'Filter SVG feTurbulence + feDisplacementMap dengan skala naik; tetesan dari elemen goo.',
      'Sudah (TY09)', 3, 8, 7,
      '72 Jam yang Meleleh', 'Relate',
      '“72 jam itu cepat. Apalagi kalau dihitung manual.”',
      'Angka 72 JAM utuh → meleleh saat email bolak-balik → membeku jadi pil tenggat otomatis → CTA',
      'DSR (tenggat otomatis 72 jam)', 'dsr-detail', '15 dtk', 'M07 / P06'),
    R('TY10', 'Glitch / RGB split',
      'Huruf pecah jadi kanal merah-hijau-biru, bergeser, berkedip seperti sinyal rusak.',
      'Tiga salinan teks berwarna dengan offset dari hash per frame; potongan clip-path deterministik.',
      'Sudah (TY10)', 2, 7, 7,
      '03.00', 'Anomali',
      '“Jam 03.00. Tulisan ini muncul di layar: dugaan kebocoran data.”',
      'Teks glitch → penghitung 3×24 jam mulai → daftar periksa penahanan muncul rapi (glitch hilang) → CTA',
      'Manajemen Insiden', 'breach-detail', '15 dtk', 'M11 / P03'),
    R('TY11', 'Font variabel “bernapas”',
      'Satu kata menebal, melebar, lalu menipis mengikuti emosi kalimat.',
      'Font variabel (Archivo wght 100–900, wdth 62–125) dianimasikan per frame dari waktu.',
      'Sudah (TY11)', 2, 7, 8,
      'Minggu Depan Ya', 'Relate',
      '“Begini rasanya saat auditor bilang: ‘minggu depan ya’.”',
      'Kata AUDIT tipis → makin tebal & sesak tiap hari → satu klik ekspor laporan kepatuhan → kata kembali lega → CTA',
      'Dasbor kepatuhan, GAP Assessment', 'dashboard, gap-hasil', '15 dtk', 'Baru (turunan M01)'),
    R('TY12', 'Elastis (huruf karet)',
      'Huruf ditarik memanjang seperti karet lalu memantul kembali.',
      'scaleX/scaleY dengan easing elastis, titik tumpu di sisi huruf.',
      'Bisa', 2, 6, 7,
      'Yang Tidak Bisa Ditarik', 'Logika dipatahkan',
      '“Tenggat proyek bisa ditarik-tarik. 3×24 jam tidak.”',
      'Kata TENGGAT ditarik berkali-kali → kata 3×24 JAM tidak bergerak → penghitung mundur insiden → CTA',
      'Manajemen Insiden (penghitung mundur 3×24 jam)', 'breach-detail', '10 dtk', 'P30 (varian)'),
    R('TY33', 'Anagram (huruf bertukar tempat)',
      'Huruf-huruf sebuah kata bertukar tempat membentuk kata lain.',
      'Tiap huruf pindah posisi lewat lengkungan; jeda bertingkat.',
      'Sudah (TY33)', 1, 9, 9,
      'NAMA ↔ AMAN', 'Anomali',
      '“NAMA dan AMAN tersusun dari empat huruf yang sama.”',
      'NAMA → huruf bertukar → AMAN → “bedanya cuma di cara mengaturnya” → RoPA & log bukti → CTA',
      'Platform, RoPA', 'ropa-list-baru', '10 dtk', 'Baru', 'Hook paling hemat: 4 huruf.'),
    R('TY18', 'Text scramble / decode',
      'Huruf berputar acak lalu “terkunci” satu per satu menjadi kata yang benar.',
      'Tiap posisi huruf mengacak dari hash sampai waktu kuncinya; warna berubah saat terkunci.',
      'Sudah (TY18)', 2, 8, 8,
      'kol_17', 'Anomali',
      '“Kolom bernama ‘kol_17’ ini ternyata berisi NIK.”',
      'Nama kolom acak → terurai jadi NIK, no. HP, email → ditandai data pribadi umum/spesifik → dikaitkan ke RoPA → CTA',
      'Data Discovery (pemindaian kolom)', '—', '15 dtk', 'M15 / P15', 'Nama kolom = ilustrasi.'),
    R('TY50', 'Teks teriris (sliced)',
      'Kalimat terpotong horizontal; irisan bergeser lalu menyatu.',
      'Beberapa salinan teks dengan clip-path pita; offset X per pita.',
      'Sudah (TY50)', 1, 6, 7,
      'Informasi yang Terpotong', 'Anomali',
      '“Tiap divisi pegang sepotong. Tidak ada yang pegang kalimat utuhnya.”',
      'Kalimat teriris 4 (Legal, IT, CS, Marketing) → irisan menyatu di Nexus → CTA',
      'Platform (modul saling terhubung)', '—', '10 dtk', 'Baru'),
    R('TY54', 'Tipografi aksesibel (morph)',
      'Kalimat yang sama berubah dari huruf kecil rapat menjadi besar, renggang, dan kontras tinggi.',
      'Interpolasi ukuran, jarak huruf, kontras; ikon suara sederhana muncul.',
      'Sudah (TY54)', 2, 7, 9,
      'Persetujuan yang Bisa Dibaca', 'Logika dipatahkan',
      '“Persetujuan yang tidak bisa dibaca, bukan persetujuan.”',
      'Kalimat legal kecil → berubah jadi jelas → layar Inclusive Privacy → CTA',
      'Inclusive Privacy', 'inclusive-privacy', '15 dtk', 'M10'),

    # ------------------------------------------------------------------ papan, angka, dan tanda
    R('TY13', 'Marquee brutalist (teks berjalan bertumpuk)',
      'Baris-baris teks raksasa berjalan berlawanan arah, memenuhi layar.',
      'Beberapa pita teks translateX berkecepatan beda; satu pita berhenti dan disorot.',
      'Sudah (TY13)', 1, 7, 7,
      'Yang Mana Punyamu?', 'Anomali',
      '“Semua tulisan ini kewajiban. Yang mana yang sudah kamu kerjakan?”',
      'Pita kewajiban berjalan (catat pemrosesan · nilai risiko · jawab permohonan · lapor insiden) → berhenti & dicentang satu-satu → CTA',
      'Platform, Paparan Sanksi', '—', '15 dtk', 'Baru'),
    R('TY14', 'Papan LED berjalan',
      'Papan LED titik-titik merah/kuning seperti di depan toko; teks berjalan.',
      'Kisi titik (canvas) menyala sesuai bitmap huruf, bergeser per kolom; pendar lembut.',
      'Sudah (TY14)', 3, 8, 7,
      'Buka 24 Jam', 'Relate',
      '“Kalau permohonan hak subjek data punya papan LED: BUKA 24 JAM.”',
      'Papan LED: “TERIMA PERMOHONAN HAPUS DATA” → “TENGGAT 72 JAM” menghitung → formulir DSR asli → CTA',
      'DSR (formulir tersemat, tenggat 72 jam)', 'dsr-form', '15 dtk', 'M07 (varian lokal)'),
    R('TY15', 'Angka digital / odometer',
      'Angka tujuh-segmen atau odometer yang terus berputar.',
      'Digit bergulir vertikal (translateY) dari nilai waktu; segmen menyala lewat kelas.',
      'Sudah (TY15)', 2, 6, 8,
      'Angka yang Mulai Berjalan', 'Anomali',
      '“Angka ini mulai berjalan begitu insiden dicatat.”',
      '72:00:00 mulai turun → tugas fase 1 tercentang satu-satu → templat pemberitahuan → CTA',
      'Manajemen Insiden', 'breach-fase, breach-aksi', '15 dtk', 'P30'),
    R('TY26', 'Angka raksasa (big number)',
      'Satu angka memenuhi layar; keterangan kecil di bawahnya.',
      'Angka fit-to-width, masuk dengan hentakan; hitungan naik.',
      'Sudah (TY26)', 1, 7, 9,
      '2%', 'Anomali',
      '“Angka kecil yang membuat CFO berdiri dari kursinya: 2%.”',
      '2% raksasa → “dari pendapatan tahunan” → pemetaan pasal bersanksi → CTA konsultasi',
      'Paparan Sanksi Administratif', '—', '10 dtk', 'P29 / A08', 'UU PDP Pasal 57 ayat (3): paling tinggi 2%.'),
    R('TY53', 'Kalender sobek',
      'Kalender harian; lembar disobek satu per satu.',
      'Lembar berputar di engsel atas (rotateX) lalu jatuh; angka fit-to-width.',
      'Sudah (TY53)', 2, 6, 8,
      'H-sekian', 'Anomali',
      '“Tiap lembar yang disobek, PP 33 makin dekat.”',
      'Lembar disobek cepat → berhenti di 16 Januari 2027 → daftar siap PP 33 → CTA',
      'Program siap PP 33', '—', '10 dtk', 'P28 / A23', 'Hitung mundur mengikuti tanggal tayang.'),
    R('TY42', 'Rambu & marka jalan',
      'Rambu lalu lintas dan marka jalan dengan pesan kepatuhan.',
      'Bentuk rambu SVG (lingkaran, segitiga, belah ketupat) + huruf tebal; jalan bergerak.',
      'Sudah (TY42)', 2, 7, 7,
      'Rambu-rambu Data Pribadi', 'Relate',
      '“Kalau kewajiban data pribadi dipasang seperti rambu jalan.”',
      'Rambu: WAJIB CATAT · HATI-HATI DATA SPESIFIK · LAPOR 3×24 JAM → peta modul Nexus → CTA',
      'Platform, Insiden', '—', '15 dtk', 'Baru', 'Bentuk rambu umum; tanpa lambang instansi.'),
    R('TY43', 'Spanduk warung tenda',
      'Huruf warna-warni tebal bergradasi seperti spanduk warung kaki lima.',
      'Huruf display + gradasi + garis tepi ganda; kain bergelombang (skew sinus).',
      'Sudah (TY43)', 3, 9, 6,
      'Warung Kepatuhan', 'Relate',
      '“Kalau urusan data pribadi buka warung tenda: SEDIA RoPA, DPIA, DSR. Buka 24 jam.”',
      'Spanduk terbentang → “menu” modul → “bisa dibungkus” (ekspor laporan) → CTA',
      'Platform', '—', '15 dtk', 'Baru (lokal)', 'Gaya huruf umum; jangan meniru spanduk warung tertentu.'),
    R('TY44', 'Papan huruf (letter board)',
      'Papan beralur dengan huruf plastik putih yang dipasang satu-satu.',
      'Huruf masuk ke alur papan dengan bunyi klik; beberapa huruf miring.',
      'Sudah (TY44)', 2, 7, 7,
      'Sedang Tayang', 'Relate',
      '“SEDANG TAYANG: AUDIT. Tanpa gladi resik.”',
      'Huruf dipasang → judul berganti: “SEGERA: FIRE DRILL” → simulasi → CTA',
      'Simulasi & Fire Drill', 'fire-drill-header', '10 dtk', 'M12'),
    R('TY40', 'Letterpress / poster huruf kayu',
      'Poster pengumuman jadul: huruf kayu besar, tinta tidak rata.',
      'Beberapa font display + tekstur tinta (mask bintik), masuk seperti dicap.',
      'Sudah (TY40)', 2, 7, 7,
      'PENGUMUMAN', 'Anomali',
      '“PENGUMUMAN: mulai 16 Januari 2027, ‘nanti saja’ tidak berlaku.”',
      'Poster dicetak baris demi baris → tanggal → program siap PP 33 → CTA',
      'Program siap PP 33', '—', '10 dtk', 'A23 / N08'),
    R('TY39', 'Stensil / cat semprot',
      'Huruf stensil disemprot ke dinding; cat meluber di tepi.',
      'Font stensil + tekstur bintik (canvas hash) + garis lelehan cat turun.',
      'Sudah (TY39)', 2, 7, 5,
      'Dilarang Patuh Setengah-setengah', 'Reverse psychology',
      '“DILARANG PATUH SETENGAH-SETENGAH.”',
      'Tulisan disemprot → panah ke daftar “setengah” (RoPA ada, bukti tidak) → GAP Assessment → CTA',
      'GAP Assessment', 'gap-rekomendasi', '10 dtk', 'Baru', 'Nada keras; cocok organik, bukan iklan korporat.'),
    R('TY41', 'Label maker (pita timbul)',
      'Pita label timbul hitam-putih ditempel di benda-benda.',
      'Pita hitam dengan huruf timbul (text-shadow), keluar dari alat lalu ditempel miring.',
      'Sudah (TY41)', 2, 8, 7,
      'Beri Label Semuanya', 'Relate',
      '“Coba beri label semua data di kantormu. Satu per satu.”',
      'Label DATA PRIBADI ditempel manual, makin kewalahan → pemindaian memberi label otomatis (umum/spesifik) → CTA',
      'Data Discovery', '—', '15 dtk', 'A11 / M15'),
    R('TY52', 'Label nama “HALO”',
      'Stiker label nama bertuliskan tangan.',
      'Kartu stiker + tulisan spidol ditulis; ditempel miring.',
      'Sudah (TY52)', 1, 6, 7,
      'Halo, Nama Saya DPO', 'Relate',
      '“HALO, nama saya: DPO (sejak kemarin sore).”',
      'Stiker ditulis → daftar tugas mendadak panjang → DPO Academy + pendampingan → CTA',
      'DPO Academy', 'dpo-academy', '10 dtk', 'A36 / M20'),
    R('TY55', 'Tabel periodik',
      'Kotak unsur dengan singkatan dua huruf dan nomor.',
      'Grid kotak; kotak menyala berurutan; kotak terpilih membesar.',
      'Sudah (TY55)', 2, 6, 6,
      'Unsur-unsur Kepatuhan', 'Anomali',
      '“Ro. Dp. Ds. Tiga unsur yang wajib ada di kantormu.”',
      'Kotak Ro, Dp, Ds menyala → “bereaksi”: RoPA risiko tinggi → DPIA otomatis → CTA',
      'RoPA, DPIA, DSR', '—', '10 dtk', 'Baru', 'Hindari warna/tata letak yang meniru logo serial TV.'),

    # ------------------------------------------------------------------ dokumen & bacaan
    R('TY19', 'Redaksi (sensor hitam)',
      'Dokumen dengan balok hitam menutupi kata; balok bergeser membuka atau menutup.',
      'Balok scaleX di atas teks; urutan buka mengikuti VO.',
      'Sudah (TY19)', 1, 7, 8,
      'Siapa yang Terakhir Membuka?', 'Anomali',
      '“Siapa yang terakhir membuka data ini? ████████.”',
      'Kalimat dengan nama tertutup balok → balok terbuka: peran + waktu → log audit manusia & AI → CTA',
      'Log audit (platform)', '—', '15 dtk', 'A42'),
    R('TY20', 'Stabilo pada pasal',
      'Teks pasal di kertas; stabilo kuning menyapu frasa penting.',
      'Latar kuning scaleX di belakang frasa, tepi tidak rata (SVG), mengikuti kata VO.',
      'Sudah (TY20)', 1, 6, 9,
      'AI yang Tidak Mengarang Pasal', 'Logika dipatahkan',
      '“AI terbaik untuk DPO bukan yang paling kreatif. Tapi yang tidak mengarang pasal.”',
      'Jawaban AI → bunyi pasal disorot stabilo: diambil dari knowledge base → hasil bisa disunting konsultan → CTA',
      'Telaah Kebijakan, Priva', 'ai-agent-chat, policy-review', '20 dtk', 'M19 / P18 / A35', 'Kutip pasal persis; cek ulang bunyinya.'),
    R('TY21', 'Coret & tulis ulang (koreksi editor)',
      'Naskah diketik, dicoret tinta merah, ditulis ulang di atasnya.',
      'Garis coret digambar (stroke), tanda sisip muncul, teks pengganti ditulis tangan.',
      'Sudah (TY21)', 2, 7, 8,
      'Lebih Tua dari Undang-undangnya', 'Anomali',
      '“Kebijakan privasi di situsmu mungkin lebih tua dari UU PDP.”',
      'Halaman kebijakan “diperbarui 2019” → coretan merah per bab → temuan & rekomendasi → CTA',
      'Telaah Kebijakan (per bab)', 'policy-review', '20 dtk', 'M16', 'Crop angka yang tampil rusak di screenshot.'),
    R('TY22', 'Isi titik-titik',
      'Kalimat dengan ruang kosong bergaris; jawaban muncul, dihapus, diganti.',
      'Garis bawah + teks jawaban ketik/hapus bergantian; tanda tanya bergoyang.',
      'Sudah (TY22)', 1, 6, 8,
      'Isi Titik-titik Ini', 'Reverse psychology',
      '“Jangan isi titik-titik ini kalau belum yakin: data pelanggan kami disimpan di ______.”',
      'Jawaban berubah-ubah (server? laptop? pihak ketiga?) → katalog sistem & sumber data → CTA',
      'Data Discovery, RoPA', '—', '15 dtk', 'Baru (turunan M15)'),
    R('TY25', 'Entri kamus',
      'Halaman kamus: kata, cara baca, kelas kata, definisi, contoh kalimat.',
      'Tata letak serif; definisi muncul per baris; nomor arti bertambah.',
      'Sudah (TY25)', 1, 7, 8,
      'DPO (n.)', 'Relate',
      '“DPO (n.): orang yang ditanya semua hal tentang data, termasuk yang bukan urusannya.”',
      'Arti 1, 2, 3 makin jujur → arti 4: “punya antrean kerja dan asisten AI” → CTA',
      'Dukungan PPDP, Priva', 'ai-agent-home', '15 dtk', 'A40 / A12'),
    R('TY56', 'Daftar isi bertitik',
      'Daftar isi dengan titik-titik penuntun ke nomor halaman.',
      'Titik-titik tumbuh (lebar), nomor halaman menghitung naik.',
      'Sudah (TY56)', 1, 5, 8,
      'Halaman 482', 'Logika dipatahkan',
      '“Bab 1 … hlm. 3. Bab 12 … hlm. 482. Direksi berhenti di hlm. 2.”',
      'Daftar isi memanjang → dilipat jadi satu layar dasbor → CTA',
      'Dasbor kepatuhan', 'dashboard-postur', '10 dtk', 'M01 (potongan)', '“482 halaman” = ilustrasi.'),
    R('TY45', 'Tes mata (papan huruf mengecil)',
      'Papan tes mata: huruf besar di atas, makin kecil ke bawah.',
      'Baris teks dengan ukuran menurun; penunjuk bergerak turun; blur bertambah.',
      'Sudah (TY45)', 1, 9, 9,
      'Baca Baris Paling Bawah', 'Reverse psychology',
      '“Coba baca baris paling bawah. Itu syarat yang baru kamu setujui.”',
      'Papan tes mata berisi kalimat persetujuan → baris bawah tak terbaca → versi jelas & aksesibel → CTA',
      'Inclusive Privacy, Consent', 'inclusive-privacy', '15 dtk', 'M10 / A32'),
    R('TY46', 'Tulisan kecil (fine print) zoom',
      'Kamera menyelam ke tulisan super kecil di pojok halaman.',
      'Zoom berkelanjutan (skala eksponensial) ke teks mikro; ketajaman muncul bertahap.',
      'Sudah (TY46)', 2, 8, 8,
      'Tanda Bintang', 'Anomali',
      '“Pelanggan sudah klik ‘Setuju’. Pertanyaannya: bisa kamu buktikan?”',
      'Tombol Setuju → zoom ke tanda bintang kecil → “bukti: ada/tidak?” → log persetujuan per subjek → CTA',
      'Consent (log & bukti)', 'consent-detail', '15 dtk', 'M08 / P07'),
    R('TY51', 'Zoom tanpa akhir lewat huruf',
      'Kamera masuk ke titik huruf “i”; di dalamnya ada kalimat berikutnya, terus berulang.',
      'Skala eksponensial bertingkat; tiap tingkat dirender saat mendekati ukuran layar.',
      'Sudah (TY51)', 3, 9, 8,
      'Di Dalam Titik Huruf i', 'Anomali',
      '“Di dalam titik huruf ‘i’ ini ada satu kewajiban lagi.”',
      'RoPA → masuk titik: risiko TINGGI → masuk lagi: draf DPIA otomatis → masuk lagi: rencana penanganan risiko → CTA',
      'RoPA → DPIA → Risk Treatment Plan', '—', '20 dtk', 'M05 (varian)'),
    R('TY48', 'Kredit akhir film',
      'Daftar kredit putih di layar hitam bergulir ke atas.',
      'Blok teks translateY linear; kolom peran–nama.',
      'Sudah (TY48)', 1, 8, 8,
      'Film dengan Satu Pemeran', 'Relate',
      '“Pemeran: DPO sebagai Legal. DPO sebagai IT. DPO sebagai CS. DPO sebagai Humas.”',
      'Kredit terus berisi nama yang sama → “Turut membantu: Privasimu Nexus” → CTA',
      'Dukungan PPDP', '—', '15 dtk', 'A06 / A21'),
    R('TY36', 'Subtitle saja di layar hitam',
      'Layar hitam total; hanya subtitle dan suara (langkah kaki, pintu, ketukan).',
      'Teks subtitle + keterangan suara dalam kurung; desain suara jadi “gambar”.',
      'Sudah (TY36)', 1, 8, 8,
      'Selamat Pagi, Kami dari Tim Audit', 'Anomali',
      '“[pintu diketuk] Selamat pagi, kami dari tim audit.”',
      'Dialog tanpa gambar → “[hening panjang]” → layar menyala: dasbor kepatuhan → CTA',
      'Dasbor, GAP Assessment', 'dashboard', '15 dtk', 'Baru (turunan A16)', 'Produksi paling ringan.'),

    # ------------------------------------------------------------------ irama & permainan kata
    R('TY16', 'Karaoke / lyric video',
      'Lirik di layar; bola kecil memantul di atas kata yang sedang dinyanyikan.',
      'Sorot per kata dari timing VO; bola mengikuti parabola antar kata.',
      'Sudah (TY16)', 2, 7, 6,
      'Lagu Wajib Rapat Kepatuhan', 'Relate',
      '“Nyanyikan bersama: ‘Datanya di mana? Di cloud.’”',
      'Bait 1: “Di cloud” → bait 2: “Cloud-nya di negara mana?” (hening) → register transfer lintas negara → CTA',
      'Transfer Data Lintas Negara (TIA)', '—', '20 dtk', 'M14 / A34', 'Melodi orisinal (synth), bukan lagu yang sudah ada.'),
    R('TY17', 'Satu kata per layar',
      'Satu kata besar di tengah, berganti cepat mengikuti suara.',
      'Ganti kata tepat di waktu ucapan; huruf tengah diberi warna sebagai titik fokus.',
      'Sudah (TY17)', 1, 6, 8,
      'Patuh Bukan Perasaan', 'Logika dipatahkan',
      '“Patuh. Bukan. Perasaan.”',
      'Tiga kata → “Ukur.” → skor GAP 81% asli → CTA Start Pre Check',
      'GAP Assessment', 'gap-hasil', '5–10 dtk', 'P01', 'Skor 81% = data demo di screenshot.'),
    R('TY23', 'Cari kata',
      'Kotak huruf acak; kata yang ditemukan dilingkari satu per satu.',
      'Grid huruf; lingkaran kapsul digambar (stroke) di atas kata; penghitung waktu.',
      'Sudah (TY23)', 2, 7, 7,
      'Cari 5 Kewajiban', 'Relate',
      '“Cari 5 kewajiban UU PDP di kotak ini. Waktumu 10 detik.”',
      'Timer berjalan → RoPA, DPIA, DSR, CONSENT, INSIDEN dilingkari → “di Nexus tidak perlu dicari” → CTA',
      'Platform', '—', '15 dtk', 'Baru', 'Mengundang komentar & share.'),
    R('TY24', 'Tuts keyboard',
      'Tuts keyboard besar ditekan satu per satu membentuk pesan.',
      'Kotak tuts 3D semu (bayangan), turun 6 px saat ditekan; SFX key.',
      'Sudah (TY24)', 2, 7, 8,
      'Ctrl + Z', 'Logika dipatahkan',
      '“Semua bisa di-undo. Kecuali data yang sudah bocor.”',
      'Ctrl+Z ditekan berulang, tidak terjadi apa-apa → yang bisa: latihan sebelum kejadian → Fire Drill → CTA',
      'Simulasi & Fire Drill, Insiden', 'fire-drill-header', '10 dtk', 'M12 / P17'),
    R('TY47', 'Rebus emoji',
      'Kalimat yang sebagian katanya diganti emoji; penonton menebak.',
      'Baris campuran teks + emoji (Noto Color Emoji); jawaban terbuka per kata.',
      'Bisa', 1, 6, 6,
      'Tebak Kewajibannya', 'Relate',
      '“Tebak kewajiban PDP dari emoji ini: 📝🔍⏰.”',
      'Tiga teka-teki emoji → jawaban (catat, nilai, lapor tepat waktu) → CTA',
      'Platform', '—', '15 dtk', 'Baru', 'Untuk interaksi organik.'),
    R('TY49', 'Awan kata',
      'Kata-kata berbagai ukuran memenuhi layar; yang paling sering paling besar.',
      'Posisi kata dihitung sekali (spiral), ukuran tumbuh; kata utama menyala.',
      'Sudah (TY49)', 2, 6, 7,
      'Kata Paling Sering Tahun Ini', 'Relate',
      '“Kata yang paling sering diucapkan DPO tahun ini: ‘revisi’.”',
      'Awan kata tumbuh (revisi, rapat, form, tenggat) → kata baru masuk: “tercatat” → CTA',
      'Brand', '—', '10 dtk', 'A22 (potongan)', 'Frekuensi = ilustrasi.'),
    R('TY30', 'Pola kata berulang',
      'Layar penuh kata yang sama seperti wallpaper; satu kata berbeda.',
      'Grid teks; satu sel berubah warna/kata; kamera mendekat ke sel itu.',
      'Sudah (TY30)', 1, 6, 8,
      '12 Definisi Patuh', 'Anomali',
      '“1 grup usaha. 12 anak perusahaan. 12 definisi ‘patuh’.”',
      'Kata PATUH ×12 dengan huruf berbeda-beda → diseragamkan → dasbor grup → CTA konsultasi enterprise',
      'Holding (asesmen & dasbor grup)', 'holding-header', '15 dtk', 'M21 / P25', 'Tanpa nama grup/perusahaan nyata.'),

    # ------------------------------------------------------------------ huruf di ruang
    R('TY27', 'Huruf 3D / isometrik',
      'Huruf berdiri seperti gedung dengan sisi dan bayangan.',
      'Lapisan text-shadow bertumpuk atau CSS 3D; kamera orbit kecil.',
      'Sudah (TY27)', 3, 8, 7,
      'Kota PP 33', 'Anomali',
      '“Bangunan ini selesai 16 Januari 2027. Kantormu sudah punya kuncinya?”',
      'Huruf PP 33 dibangun lantai demi lantai → tanggal muncul → program siap PP 33 → CTA',
      'Program siap PP 33, GAP', '—', '15 dtk', 'P04 / A23'),
    R('TY28', 'Bayangan panjang (long shadow)',
      'Huruf datar dengan bayangan diagonal yang memanjang.',
      'Bayangan dari banyak lapis offset; panjang bayangan = fungsi waktu.',
      'Sudah (TY28)', 1, 5, 7,
      'Bayangan Tenggat', 'Anomali',
      '“Makin dekat tanggalnya, makin panjang bayangannya.”',
      '“16 JAN” → bayangan memanjang menutupi meja kerja → daftar langkah siap PP 33 → CTA',
      'Program siap PP 33', '—', '10 dtk', 'A23'),
    R('TY29', 'Outline + gema',
      'Huruf garis tepi dengan salinan yang mengekor seperti gema.',
      'Salinan teks stroke-only dengan jeda waktu & opasitas menurun.',
      'Sudah (TY29)', 2, 7, 7,
      'Satu Permintaan, Tujuh Gema', 'Relate',
      '“Satu permintaan: ‘hapus data saya’. Tujuh sistem yang harus menjawab.”',
      'Kata HAPUS bergema ke 7 arah → Data Discovery menemukan lokasinya → DSR terlacak sampai selesai → CTA',
      'DSR, Data Discovery', 'dsr-detail', '15 dtk', 'A38', 'Angka 7 = ilustrasi.'),
    R('TY31', 'Teks di jalur / pusaran',
      'Kalimat mengalir mengikuti lengkungan, spiral, atau pusaran.',
      'SVG textPath dengan startOffset dianimasikan; spiral mengecil ke tengah.',
      'Sudah (TY31)', 2, 7, 7,
      'Ke Mana Perginya?', 'Anomali',
      '“Ke mana perginya data setelah tombol ‘Kirim’ ditekan?”',
      'Kata nama–email–NIK berputar masuk pusaran → keluar sebagai baris RoPA: tujuan, penerima, retensi → CTA',
      'RoPA', 'ropa-tersimpan', '15 dtk', 'Baru (turunan M04)'),
    R('TY32', 'Huruf berjatuhan',
      'Huruf lepas dari kalimat, jatuh, memantul, dan menumpuk di bawah.',
      'Lintasan jatuh dihitung dari rumus (tanpa simulasi acak); rotasi dari hash.',
      'Sudah (TY32)', 3, 8, 6,
      '40 Halaman', 'Relate',
      '“Tidak ada yang membaca kebijakan privasi 40 halaman. Termasuk yang menulisnya.”',
      'Paragraf runtuh jadi tumpukan huruf → tersusun ulang jadi temuan per bab → CTA',
      'Telaah Kebijakan', 'policy-review', '15 dtk', 'M16 (varian)', '“40 halaman” = ilustrasi.'),
    R('TY34', 'Kaligram (kata membentuk gambar)',
      'Ratusan kata kecil tersusun membentuk gambar (gembok, perisai).',
      'Kata ditempatkan di titik-titik siluet (dihitung sekali), muncul bergelombang.',
      'Sudah (TY34)', 3, 8, 8,
      'Gembok dari Kata-kata', 'Anomali',
      '“Gembok ini tidak terbuat dari besi, tapi dari catatan.”',
      'Kata RoPA, DPIA, bukti, log, tenggat… berkumpul → membentuk gembok → logo → CTA',
      'Platform', '—', '10 dtk', 'Baru (bumper)'),

    # ------------------------------------------------------------------ tulisan tangan & kuas
    R('TY37', 'Tulisan tangan (write-on)',
      'Kalimat ditulis tangan huruf demi huruf, seperti catatan di kertas.',
      'Font tulisan tangan + pembuka clip-path per huruf; ujung pena mengikuti.',
      'Sudah (TY37)', 2, 6, 8,
      'Catatan Kecil untuk Direksi', 'Relate',
      '“Pak, laporannya 482 halaman. Ringkasannya satu layar.”',
      'Catatan ditulis di kertas tempel → ditempel di tumpukan laporan → dasbor satu layar → CTA',
      'Dasbor kepatuhan', 'dashboard', '10 dtk', 'P32 / M01', '“482 halaman” = ilustrasi.'),
    R('TY38', 'Kaligrafi kuas',
      'Satu kata digores kuas tinta tebal, dengan cipratan kecil.',
      'Masker sapuan (clip-path/mask) membuka teks; tekstur tinta dari turbulence.',
      'Sudah (TY38)', 3, 8, 7,
      'Satu Kata untuk 2027', 'Logika dipatahkan',
      '“Resolusi 2027 kantor ini cukup satu kata.”',
      'Kertas kosong → goresan kuas: RAPI → daftar langkah siap PP 33 → CTA',
      'GAP, program siap PP 33', '—', '10 dtk', 'A24'),
]
